// Generated by the CU CMS. Do not edit.

export type AdmissionOfficesRow = {
  city: string;
  state: string;
  address: string;
  contactName: string;
  phone: string;
  landline: string;
  email: string;
  isCampus: boolean;
};

export type AdmissionOffices = AdmissionOfficesRow[];
