// Generated by the CU CMS. Do not edit.

export type BooksRow = {
  title: string;
  authors: string;
  publisher: string;
  year: number | null;
  isbn: string;
  link: string;
  kind: string;
};

export type Books = BooksRow[];
