// Generated by the CU CMS. Do not edit.

export type CucetSlabsRow = {
  phase: 'phase-1' | 'phase-2';
  band: string;
  value: string;
  note: string;
  order: number;
};

export type CucetSlabs = CucetSlabsRow[];
