// Generated by the CU CMS. Do not edit.

export type Course = {
  name: string;
  lecture: number;
  tutorial: number;
  practical: number;
  credits: number;
  contactHours: number | null;
};

export type Semester = {
  number: number;
  courses: Course[];
};

export type Objective = {
  code: string;
  body: string;
};

export type CurriculumsRow = {
  program: string | null;
  semesters: Semester[];
  objectives: Objective[];
};

export type Curriculums = CurriculumsRow[];
