// Generated by the CU CMS. Do not edit.

export type Member = {
  seat: string;
  position: string;
};

export type GoverningBodyRow = {
  slug: string;
  name: string;
  lede: string;
  members: Member[];
  order: number;
};

export type GoverningBody = GoverningBodyRow[];
