// Generated by the CU CMS. Do not edit.

import type { CmsImage } from '../media';

export type Tag = {
  label: string;
};

export type LaboratoriesRow = {
  slug: string;
  name: string;
  objective: string;
  school: string | null;
  tags: Tag[];
  image: CmsImage | null;
  order: number;
};

export type Laboratories = LaboratoriesRow[];
