// Generated by the CU CMS. Do not edit.

export type PatentsRow = {
  title: string;
  inventors: string;
  number: string;
  status: 'filed' | 'published' | 'granted' | null;
  year: number | null;
  link: string;
};

export type Patents = PatentsRow[];
