// Generated by the CU CMS. Do not edit.

import type { CmsImage } from '../media';

/** The disciplines as the filter rail spells them; the rail's running order, not alphabetical. */
export type ProgramDiscipline =
  | 'Business'
  | 'Computing'
  | 'Applied Health Sciences'
  | 'Engineering'
  | 'Legal Studies'
  | 'Biotechnology'
  | 'Commerce'
  | 'Journalism and Mass Communication'
  | 'Pharmacy'
  | 'Design'
  | 'Hotel Management and Tourism'
  | 'Liberal Arts'
  | 'Architecture and Planning';

export type ProgramLevel = 'UG' | 'PG';

/** One numbered highlight on the program detail page. */
export type ProgramFeature = {
  num: string;
  title: string;
  /** Trailing run of the title, set in the accent colour. */
  titleHighlight: string;
  description: string;
  /** URL, not a `CmsImage`: the detail page's own default array is URLs too. */
  image: string;
};

/** One certification badge on the program detail page. */
export type ProgramCertification = {
  image: string;
};

/**
 * Which of the three card treatments a program takes in the carousel. `active`
 * also marks the card its discipline opens on.
 */
export type ProgramTheme = 'light' | 'dark' | 'active';

export type Program = {
  /** The Strapi entry id — stable, unlike a component id. */
  id: number;
  discipline: ProgramDiscipline;
  programCode: string;
  programShortName: string;
  programName: string;
  level: ProgramLevel;
  durationYears: string;
  cucetCompulsory: boolean;
  cucetScholarshipApplicable: boolean;
  /** Per-semester fee in INR. */
  feePerSemester: number;
  eligibilityCriteria: string;
  /** Short card headline, e.g. `MBA (Applied Finance) with PwC`. */
  title: string;
  theme: ProgramTheme;
  /** Partner key: drives the logo plate, the favicon lookup and the search. */
  logoId: string;
  partner: string;
  description: string;
  format: string;
  duration: string;
  eligibility: string;
  deadline: string;
  image: CmsImage;
  logo: CmsImage | null;
  features: ProgramFeature[];
  certifications: ProgramCertification[];
  roles: string[];

  /** Not modelled in Strapi: ships from the site's constants, fallbacks cover it. */
  about?: {
    body: string;
    facts: { label: string; value: string }[];
    image?: string;
    scope?: string;
  };

  /** The sub-line under "Why Choose …?". Constants-only, like `about`. */
  whyChoose?: string;

  /** Programme codes for the Related Programmes row. Defaults to same-discipline siblings. */
  relatedIds?: string[];

  /** Per-programme placement content. Constants-only, like `about`. */
  placement?: {
    recruiters?: string[];
    avgPackage?: string;
  };
  /** Text description for the Global Certifications section */
  globalCertifications?: string;
};

export type Programs = Program[];
