// Generated by the CU CMS. Do not edit.

export type PublicationsRow = {
  title: string;
  authors: string;
  venue: string;
  year: number | null;
  doi: string;
  link: string;
  quartile: string;
};

export type Publications = PublicationsRow[];
