// Generated by the CU CMS. Do not edit.

import type { CmsImage } from '../media';

export type Point = {
  label: string;
};

export type TeachingPractice = {
  title: string;
  body: string;
  points: Point[];
};

export type EvaluationPractice = {
  title: string;
  body: string;
  points: Point[];
};

export type PlacementStat = {
  value: string;
  label: string;
};

export type Recruiter = {
  name: string;
};

export type Placement = {
  session: string;
  source: string;
  department: string;
  stats: PlacementStat[];
  recruiters: Recruiter[];
};

export type Highlight = {
  icon: 'spark' | 'lab' | 'partners' | 'globe';
  label: string;
  value: string;
};

export type SchoolsRow = {
  discipline: 'applied-health-sciences' | 'architecture-and-planning' | 'biotechnology' | 'business' | 'commerce' | 'computing' | 'design' | 'engineering' | 'hotel-management-and-tourism' | 'journalism-and-mass-communication' | 'legal-studies' | 'liberal-arts' | 'pharmacy';
  name: string;
  tagline: string;
  heroImage: CmsImage | null;
  teachingIntro: string;
  teachingPractices: TeachingPractice[];
  evaluationIntro: string;
  evaluationPractices: EvaluationPractice[];
  teachesAiCompetencies: boolean;
  order: number;
  placement: Placement | null;
  highlights: Highlight[];
};

export type Schools = SchoolsRow[];
