// Generated by the CU CMS. Do not edit.

export type Slab = {
  band: string;
  value: string;
  note: string;
};

export type Point = {
  text: string;
};

export type ScholarshipsRow = {
  slug: string;
  kind: 'merit' | 'concession';
  name: string;
  body: string;
  slabs: Slab[];
  points: Point[];
  continuation: string;
  order: number;
};

export type Scholarships = ScholarshipsRow[];
