// Generated by the CU CMS. Do not edit.

import type { HeroSection } from './types/hero-section';

export type { HeroSection };

export const HERO_SECTION: HeroSection = {
  "heading": "this is not a bad idaea varun",
  "subheading": "Testing subheading 1",
  "fallbackImage": {
    "url": "http://127.0.0.1:1337/uploads/picsum_photos_seed_01b7dc653d53_1400_933_43c84f75db.jpg",
    "alt": "Chandigarh University",
    "width": 1400,
    "height": 933
  },
  "countdownDeadline": "2026-10-20T18:29:59.000Z",
  "countdownLabel": "Testing countdown label 1\nline two",
  "countdownDateLabel": ""
};
