// Generated by the CU CMS. Do not edit.

import type { InternationalSection } from './types/international-section';

export type { InternationalSection };

export const INTERNATIONAL_SECTION: InternationalSection = {
  "heading": "Distinct\n*Global Advantage*",
  "subheading": "With 530+ international collaborations, Chandigarh University opens doors to global exposure, cross-cultural learning opportunities and professional experiences that prepare you to thrive in a global workplace.",
  "cards": [
    {
      "id": "1",
      "title": "Pioneer in AI-Integrated Multidisciplinary Education",
      "text": "Gain proficiency in AI fundamentals and domain-specific advanced modules while engaging in multidisciplinary education across disciplines of engineering, management, social sciences, law, and humanities, preparing for an AI-driven workforce.",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/images_Student_Photos_International_webimage_2_44933abce5.webp",
        "alt": "",
        "width": 1200,
        "height": 721
      },
      "link": null
    },
    {
      "id": "2",
      "title": "Fluid Learning Environment with Innovative Pedagogical Approach",
      "text": "Harness virtual reality and simulation tools to engage in tech-driven, personalised education that integrates cross-domain learning, project-based opportunities, global certifications, and predictive analytics, all tailored to your pace, career goals, and industry-aligned skill development.",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/images_Student_Photos_International_webimage_3_ecd9f5a781.webp",
        "alt": "",
        "width": 1200,
        "height": 553
      },
      "link": null
    },
    {
      "id": "3",
      "title": "Mentorship by AI Experts from Top-Tech Giants",
      "text": "Get expert AI guidance from top professionals at leading tech companies like Google, Microsoft, IBM, and more, empowering you with the skills and knowledge to excel in the tech-driven future.",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/images_Student_Photos_International_webimage_4_590616d39f.webp",
        "alt": "",
        "width": 1200,
        "height": 647
      },
      "link": null
    },
    {
      "id": "4",
      "title": "Centres of Excellence for Cross-Disciplinary Research",
      "text": "Leverage advanced technologies at industry-collaborated Centres of Excellence to undertake groundbreaking research projects in diverse domains, like blockchain, cryptography, neurotechnology, genetic engineering, and more.",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/images_Student_Photos_International_webimage_2_44933abce5.webp",
        "alt": "",
        "width": 1200,
        "height": 721
      },
      "link": null
    },
    {
      "id": "5",
      "title": "Elite and Exclusive Placement Opportunities",
      "text": "Tap into an extensive network of recruiters and land your dream job with the world's leading companies like Microsoft, Google, Amazon, IBM, Wipro, KPMG, Deloitte, Cipla, and more.",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/images_Student_Photos_International_webimage_3_ecd9f5a781.webp",
        "alt": "",
        "width": 1200,
        "height": 553
      },
      "link": null
    },
    {
      "id": "6",
      "title": "Tech-Infused Ecosystem to Nurture Entrepreneurial Ventures",
      "text": "Ignite your entrepreneurial spirit with our tech-powered incubation ecosystem and makerspace, where creativity and collaboration turn ideas into successful ventures.",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/images_Student_Photos_International_webimage_4_590616d39f.webp",
        "alt": "",
        "width": 1200,
        "height": 647
      },
      "link": null
    },
    {
      "id": "7",
      "title": "Ethical AI Practices for Nation Building",
      "text": "Integrate ethical principles in your research and innovation ventures and contribute to a future where AI promotes equality, safeguards freedom, and strengthens the foundation of a democratic and just society.",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/images_Student_Photos_International_webimage_2_44933abce5.webp",
        "alt": "",
        "width": 1200,
        "height": 721
      },
      "link": null
    },
    {
      "id": "8",
      "title": "360-Degree Support in Shaping an Intellectual Identity",
      "text": "Carve out a niche in the professional arena by elevating your career prospects by gaining attributes like versatility, adaptability, critical thinking, and strategic foresight, and emerging as a goal-oriented individual.",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/images_Student_Photos_International_webimage_3_ecd9f5a781.webp",
        "alt": "",
        "width": 1200,
        "height": 553
      },
      "link": null
    }
  ],
  "partnerLogos": [
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_American_University_Washington_DC_d0c1ca91d7.webp",
      "alt": "",
      "width": 2560,
      "height": 793
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_Borough_of_Manhattan_Community_College_of_the_City_University_of_New_York_11e6c417f1.webp",
      "alt": "",
      "width": 300,
      "height": 195
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_Brock_University_Canada_77b87ef24e.webp",
      "alt": "",
      "width": 152,
      "height": 92
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_De_Montfort_University_ada70fdced.webp",
      "alt": "",
      "width": 419,
      "height": 180
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_Friedrich_Schiller_University_Jena_6a0e7f7549.webp",
      "alt": "",
      "width": 960,
      "height": 384
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_Illinois_Institute_of_Technology_Chicago_1f46be209d.webp",
      "alt": "",
      "width": 600,
      "height": 261
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_Jeonbuk_National_University_a483f16e75.webp",
      "alt": "",
      "width": 1058,
      "height": 1059
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_Kent_State_University_USA_6a6f889f3b.webp",
      "alt": "",
      "width": 1400,
      "height": 765
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_logo_Royal_Holloway2x_f8ded23c3e.webp",
      "alt": "",
      "width": 320,
      "height": 160
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_Mid_West_University_Surkhet_Nepal_c42e182eef.webp",
      "alt": "",
      "width": 280,
      "height": 280
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_Middlesex_University_Mauritius_121ae4c43c.webp",
      "alt": "",
      "width": 512,
      "height": 253
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_Northeastern_University_0ce2d204d5.webp",
      "alt": "",
      "width": 2560,
      "height": 1440
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_Palacky_University_ed44e68fc6.webp",
      "alt": "",
      "width": 572,
      "height": 496
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_Pokhara_University_Nepal_7ec15b2693.webp",
      "alt": "",
      "width": 331,
      "height": 301
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_Queen_s_University_Belfast_bfc068cd91.webp",
      "alt": "",
      "width": 1280,
      "height": 462
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_RMIT_5d804d483c.webp",
      "alt": "",
      "width": 2560,
      "height": 901
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_Sapienza_University_of_Rome_f2e865f3de.webp",
      "alt": "",
      "width": 1280,
      "height": 385
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_Sunway_University_SDN_BHD_Malaysia_f05cbc73b7.webp",
      "alt": "",
      "width": 1860,
      "height": 794
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_The_University_of_Newcastle_Australia_41d4981531.webp",
      "alt": "",
      "width": 900,
      "height": 500
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_The_University_of_Western_Ontario_London_Ontario_Canada_Western_37d14acd9f.webp",
      "alt": "",
      "width": 700,
      "height": 400
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_UNICAMP_Universidade_Estadual_de_Campinas_b58d010f9f.webp",
      "alt": "",
      "width": 1280,
      "height": 1357
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_Universidad_Austral_Argentina_40322346d3.webp",
      "alt": "",
      "width": 529,
      "height": 417
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_Universitas_Airlangga_Indonesia_1c8f6a29a9.webp",
      "alt": "",
      "width": 1081,
      "height": 1081
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_Universiti_Sains_Malaysia_5cf8cf0b4d.webp",
      "alt": "",
      "width": 1899,
      "height": 573
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_University_of_Auckland_Faculty_of_Education_and_Social_Work_92da4138e5.webp",
      "alt": "",
      "width": 2560,
      "height": 413
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_University_of_Capetown_14a3a31500.webp",
      "alt": "",
      "width": 1280,
      "height": 1300
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_University_of_Macau_ad2b00ddc4.webp",
      "alt": "",
      "width": 2560,
      "height": 2032
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_University_of_Maryland_Baltimore_County_USA_45a87104a8.webp",
      "alt": "",
      "width": 1024,
      "height": 236
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_University_of_St_Andrews_d0c51c9816.webp",
      "alt": "",
      "width": 1000,
      "height": 439
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_University_of_Szeged_242fffd3a5.webp",
      "alt": "",
      "width": 1271,
      "height": 500
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_University_of_Zagreb_Croatia_Faculty_of_Economics_and_Business_8b6bb3db50.webp",
      "alt": "",
      "width": 373,
      "height": 177
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_Universita_Cattolica_del_Sacro_Cuore_43f214546a.webp",
      "alt": "",
      "width": 189,
      "height": 77
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_Vaal_University_of_Technology_VUT_95a5c91f9f.webp",
      "alt": "",
      "width": 550,
      "height": 178
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_Washington_Adventist_University_365ef5af86.webp",
      "alt": "",
      "width": 1405,
      "height": 250
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_Partner_University_Logos_Partner_University_Logos_Western_Sydney_University_873dcc7a41.webp",
      "alt": "",
      "width": 2364,
      "height": 924
    }
  ]
};
