// Generated by the CU CMS. Do not edit.

import type { ProgramsSection } from './types/programs-section';

export type { ProgramsSection };

export const PROGRAMS_SECTION: ProgramsSection = {
  "heading": "AI-Integrated, Industry-Aligned\n*Programs* Co-Created with Industry Giants",
  "subheading": "Chandigarh University, Uttar Pradesh, offers futuristic academic programs integrating artificial intelligence and aligning with the evolving needs of industry.",
  "cucetEyebrow": "CUCET 2026 · Phase II",
  "cucetHeading": "India’s Premier Scholarship, Unlocking *a World of Opportunities*",
  "cucetDescription": "Chandigarh University Common Entrance Test (CUCET) opens the doors to a world of opportunities and exceptional careers, rewarding academic brilliance and providing financial assistance by offering up to 100% scholarships.",
  "cucetDeadline": "2026-08-31T18:29:59.000Z",
  "cucetDeadlineLabel": "31 August 2026",
  "cucetCtaLabel": "Register for CUCET",
  "cucetCtaLink": "https://cucet.cuchd.in/index.aspx?utm_source=Website&utm_medium=culko",
  "cucetHelpline": "1800-121-288800",
  "slabs": [
    {
      "id": "1",
      "marks": "90+",
      "award": "100% fee waiver"
    },
    {
      "id": "2",
      "marks": "80 – 90",
      "award": "40%"
    },
    {
      "id": "3",
      "marks": "70 – 79.99",
      "award": "30%"
    },
    {
      "id": "4",
      "marks": "60 – 69.99",
      "award": "20%"
    },
    {
      "id": "5",
      "marks": "Scholarship pool",
      "award": "₹50 Crore"
    }
  ]
};
