// Generated by the CU CMS. Do not edit.

import type { StepInsideSection } from './types/step-inside-section';

export type { StepInsideSection };

export const STEP_INSIDE_SECTION: StepInsideSection = {
  "heading": "Step Inside *Chandigarh University - Virtually!*",
  "video": {
    "url": "http://127.0.0.1:1337/uploads/images_traditionsection_thirdsection_vid_20bf6407cf.mp4",
    "mime": "video/mp4"
  },
  "poster": {
    "url": "http://127.0.0.1:1337/uploads/images_traditionsection_thirdsection_poster_0aab0bbca6.webp",
    "alt": "",
    "width": 1280,
    "height": 720
  }
};
