// Generated by the CU CMS. Do not edit.

export type CampusLifeTab =
  | 'Infrastructure'
  | 'AI Labs'
  | 'Events'
  | 'Fests'
  | 'Academic';

export type CampusPhoto = {
  url: string;
  alt: string;
  width: number | null;
  height: number | null;
  /** Small variant for the thumbnail strip. Falls back to `url`. */
  thumb: string;
  /** Portrait re-crop shown below 1024px. Empty falls back to `url`. */
  mobile: string;
};

export type CampusLifeSection = {
  /** Accent-marked headline — see `parseAccentHeading`. */
  heading: string;
  subheading: string;
  ctaLabel: string;
  tabs: Record<CampusLifeTab, CampusPhoto[]>;
};
