// Generated by the CU CMS. Do not edit.

export type FaqTab = 'General' | 'Admissions' | 'Academics' | 'Campus Life';

export type FaqCta = {
  label: string;
  href: string;
};

export type FaqEntry = {
  question: string;
  answer: string;
  /** Carried from Strapi but not currently rendered — the accordion shows the answer only. */
  cta: FaqCta | null;
};

export type FaqSection = {
  /** Accent-marked headline — see `parseAccentHeading`. */
  heading: string;
  tabs: Record<FaqTab, FaqEntry[]>;
};
