// Generated by the CU CMS. Do not edit.

import type { CmsImage } from '../../media';

export type HeroSection = {
  heading: string;
  subheading: string;
  fallbackImage: CmsImage;
  countdownDeadline: string | null;
  countdownLabel: string;
  countdownDateLabel: string;
};
