// Generated by the CU CMS. Do not edit.

import type { CmsImage } from '../../media';

export type MomentImageTreatment = 'cover' | 'contain-banner';

export type MomentTileRow = {
  label: string;
  /** `null` selects the full-width statement layout rather than a label/figure split. */
  value: string | null;
};

export type MomentTile = {
  label: string;
  value: string;
  valueSuffix: string | null;
  /** Empty for a value-only tile — it then centres its value block. */
  rows: MomentTileRow[];
};

export type MomentCard = {
  id: string;
  badge: string;
  /** Headline runs: dark sans, then red italic Georgia, then an optional sans tail. */
  headSans: string;
  headItalic: string;
  headTail: string | null;
  body: string;
  image: CmsImage;
  /** Portrait re-crop shown below `lg`. `null` falls back to `image`. */
  imageMobile: CmsImage | null;
  /** Burned into the photo's bottom-left. `null` where the artwork carries its own title. */
  imageCaption: string | null;
  imageTreatment: MomentImageTreatment;
  tiles: MomentTile[];
};

export type MomentsMilestoneSection = {
  /** Accent-marked headline — see `parseAccentHeading`. */
  heading: string;
  cards: MomentCard[];
};
