// Generated by the CU CMS. Do not edit.

import type { CmsImage } from '../../media';

export type PlacementStream =
  | 'Engineering'
  | 'Business Management'
  | 'Marketing'
  | 'Applied Sciences'
  | 'Hotel Management'
  | 'Pharma';

export type PackageBand = {
  name: string;
  value: number;
};

export type PlacementYear = {
  year: string;
  companiesVisited: number;
  studentsPlaced: number;
  /** e.g. `59.9 LPA`. */
  highestPackage: string;
  /** e.g. `1.7 CR`. `null` for years with no international offer. */
  highestPackageIntl: string | null;
  packages: PackageBand[];
};

export type PlacementMetric = {
  value: string;
  label: string;
};

export type PlacementAchiever = {
  name: string;
  designation: string;
  placedIn: string;
  salaryValue: string;
  salaryUnit: string;
  companyLogo: CmsImage;
  personImage: CmsImage;
};

export type PlacementStory = {
  id: number;
  name: string;
  designation: string;
  companyImage: CmsImage;
  personImage: CmsImage;
  successfulSessions: number;
};

export type PlacementRecruiter = {
  name: string;
  logo: CmsImage;
};

export type PlacementSection = {
  /** Accent-marked headline — see `parseAccentHeading`. */
  heading: string;
  subheading: string;
  ctaLabel: string;
  /** The alumni card beside the dashboard. Plain text, no accent run. */
  alumniHeading: string;
  alumniSubheading: string;
  /** Accent-marked headline above the success-story carousel. */
  storiesHeading: string;
  storiesCtaLabel: string;
  /** Accent-marked headline above the recruiter marquee. */
  networkHeading: string;
  /**
   * The recruiter wall, campus recruiters first. The dashboard's own 3x3 grid
   * takes the head of this list, so the order is load-bearing.
   */
  recruiters: PlacementRecruiter[];
  metrics: PlacementMetric[];
  years: PlacementYear[];
  achievers: PlacementAchiever[];
  stories: Record<PlacementStream, PlacementStory[]>;
};
