// Generated by the CU CMS. Do not edit.

import type { CmsImage } from '../../media';

export type TestimonialReel = {
  id: string;
  /** Overlay caption, drawn bottom-left while the clip is paused. */
  title: string;
  videoLink: string;
  image: CmsImage;
};

export type AchieverVideoCategory = 'Stories' | 'Shorts' | 'Placement' | 'Cultural';

export type AchieverVideo = {
  id: string;
  /** Named `videoTitle` because `CucetAchieversCarousel` reads that key. */
  videoTitle: string;
  videoLink: string;
  /** Unset on most rows — the strip does not filter by it today. */
  category: AchieverVideoCategory | null;
};

export type InstagramReel = {
  id: string;
  title: string;
  name: string;
  url: string;
  poster: CmsImage | null;
};

export type QuoteGroup = 'Alumni' | 'Clubs' | 'Guests';

export type Quote = {
  id: string;
  quote: string;
  name: string;
  role: string;
  affiliation: string;
  photo: CmsImage | null;
};

export type TestimonialSection = {
  /** Accent-marked headline — see `parseAccentHeading`. */
  heading: string;
  testimonials: TestimonialReel[];
  /** Accent-marked headline over the auto-scrolling strip. */
  achieversHeading: string;
  achievers: AchieverVideo[];
  /** The Instagram reel strip on the home page. */
  reels: InstagramReel[];
  /** The Message-tab text testimonials on `/testimonials`, grouped by tab. */
  quotes: Record<QuoteGroup, Quote[]>;
};
