// Generated by the CU CMS. Do not edit.

import type { CmsImage } from '../../media';

export type TraditionStat = {
  /** Display figure, e.g. `100 K`, `250+`, `1.7 CR`. See `parseStatValue`. */
  value: string;
  label: string;
  note: string;
};

export type TraditionSlide = {
  /** Accent-marked headline. `\n` is a line break. */
  title: string;
  description: string;
};

export type TraditionAlumnus = {
  image: CmsImage;
  name: string;
  role: string;
  status: string;
};

export type TraditionHighlight = {
  image: CmsImage;
  title: string;
};

export type TraditionQuickLink = {
  label: string;
  href: string;
};

export type TraditionDepartment = {
  name: string;
  companies: number;
  students: number;
};

export type TraditionImpactRing = {
  label: string;
  value: number;
  /** The reference scale the arc is a fraction of, printed in the legend. */
  total: number;
};

export type TraditionPatent = {
  title: string;
  /** Real application number where there is one; a placeholder key otherwise. */
  applicationId: string;
  author: string;
};

export type TraditionCompanyLogo = {
  name: string;
  logo: CmsImage;
};

export type TraditionPartnerLogo = {
  name: string;
  logo: CmsImage;
};

export type TraditionSection = {
  /** Accent-marked headline — see `parseAccentHeading`. */
  heading: string;
  /** Accent-marked headline above the campus film. */
  filmHeading: string;
  ctaLabel: string;
  opportunitiesText: string;
  stats: TraditionStat[];
  slides: TraditionSlide[];
  alumni: TraditionAlumnus[];
  highlights: TraditionHighlight[];
  quickLinks: TraditionQuickLink[];
  /** Desktop bento, Placement tab. */
  placementMetrics: TraditionStat[];
  departments: TraditionDepartment[];
  /** Desktop bento, Overview tab. */
  overviewMetrics: TraditionStat[];
  /** Desktop bento, Research tab. */
  researchMetrics: TraditionStat[];
  impactRings: TraditionImpactRing[];
  patents: TraditionPatent[];
  researchDomains: string[];
  researchClusters: string[];
  labImages: CmsImage[];
  companyLogos: TraditionCompanyLogo[];
  partnerLogos: TraditionPartnerLogo[];
};
