// Generated by the CU CMS. Do not edit.

import type { AnnouncementBar } from '../types/site/announcement-bar';

export type { AnnouncementBar };

export const ANNOUNCEMENT_BAR: AnnouncementBar = {
  "message": "International Conference On New Media Ecologies: Transforming Communication Paradigms In The Digital Age",
  "ctaLabel": "Register Now",
  "contactLinks": [
    {
      "id": "1",
      "label": "Whatsapp",
      "link": "https://wa.me/9115888961",
      "icon": "whatsapp"
    },
    {
      "id": "2",
      "label": "Call Us",
      "link": "tel:+18002701411",
      "icon": "phone"
    },
    {
      "id": "3",
      "label": "culko.in",
      "link": "https://culko.in",
      "icon": "globe"
    }
  ],
  "socialLinks": [
    {
      "id": "1",
      "platform": "facebook",
      "link": "https://www.facebook.com/chandigarhuniversityUP/"
    },
    {
      "id": "2",
      "platform": "x",
      "link": "https://x.com/CUUttarPradesh"
    },
    {
      "id": "3",
      "platform": "linkedin",
      "link": "https://www.linkedin.com/school/chandigarhuniversityup/"
    },
    {
      "id": "4",
      "platform": "instagram",
      "link": "https://www.instagram.com/chandigarhuniversityup"
    },
    {
      "id": "5",
      "platform": "youtube",
      "link": "https://www.youtube.com/@chandigarhuniversityup"
    },
    {
      "id": "6",
      "platform": "website",
      "link": "https://culko.in"
    }
  ]
};
