// Generated by the CU CMS. Do not edit.

import type { Footer } from '../types/site/footer';

export type { Footer };

export const FOOTER: Footer = {
  "columns": [
    {
      "heading": "Explore",
      "order": 1,
      "links": [
        {
          "label": "About Us",
          "href": "/about",
          "external": false
        },
        {
          "label": "Admissions",
          "href": "/admissions",
          "external": false
        },
        {
          "label": "Academics",
          "href": "/academics",
          "external": false
        },
        {
          "label": "Campus Life",
          "href": "/campus-life",
          "external": false
        }
      ]
    },
    {
      "heading": "AI Innovations",
      "order": 2,
      "links": [
        {
          "label": "AI-Driven Features",
          "href": "/ai-features",
          "external": false
        },
        {
          "label": "AI-Fuelled Research",
          "href": "/ai-features/ai-fuelled-research",
          "external": false
        },
        {
          "label": "AI-Powered Labs",
          "href": "/ai-features/ai-powered-labs-coes",
          "external": false
        }
      ]
    },
    {
      "heading": "Support",
      "order": 3,
      "links": [
        {
          "label": "Contact Us",
          "href": "/contact",
          "external": false
        }
      ]
    },
    {
      "heading": "Visit Here",
      "order": 4,
      "links": [
        {
          "label": "Anti Ragging Cell",
          "href": "#",
          "external": true
        },
        {
          "label": "UGC Compliance",
          "href": "#",
          "external": true
        },
        {
          "label": "UGC e-Samadhan",
          "href": "#",
          "external": true
        },
        {
          "label": "UGC - Public Self Disclosure",
          "href": "#",
          "external": true
        },
        {
          "label": "Declaration of Environmental Clearance",
          "href": "#",
          "external": true
        }
      ]
    }
  ],
  "addressHeading": "Address",
  "address": "Chandigarh University, Lucknow - Kanpur Highway - 27, Unnao, Uttar Pradesh, India",
  "contactHeading": "Get in Touch",
  "helplineLabel": "Helpline",
  "helplineNumber": "1800 270 1411",
  "email": "",
  "socialHeading": "Social Media",
  "socialLinks": [
    {
      "platform": "facebook",
      "link": "https://www.facebook.com/chandigarhuniversityUP/"
    },
    {
      "platform": "instagram",
      "link": "https://www.instagram.com/chandigarhuniversityup"
    },
    {
      "platform": "linkedin",
      "link": "https://www.linkedin.com/school/chandigarhuniversityup/"
    },
    {
      "platform": "youtube",
      "link": "https://www.youtube.com/@chandigarhuniversityup"
    },
    {
      "platform": "x",
      "link": "https://x.com/CUUttarPradesh"
    }
  ],
  "legalNote": "",
  "copyright": ""
};
