// Generated by the CU CMS. Do not edit.

import type { MobileDock } from '../types/site/mobile-dock';

export type { MobileDock };

export const MOBILE_DOCK: MobileDock = {
  "ctaLabel": "testing testing",
  "registerEyebrow": "testing testing",
  "registerHeading": "testing testing",
  "registerDeadlineNote": "testing testing",
  "registerConsent": "testing testing",
  "registerSubmitLabel": "testing testing",
  "registerSuccessTitle": "testing testing",
  "registerSuccessBody": "testing testing",
  "chatTitle": "testing testing",
  "chatStatus": "0000",
  "chatGreeting": "testing testing",
  "chatPlaceholder": "testing testing",
  "chatSuggestions": [
    {
      "id": "1",
      "label": "testing testing"
    },
    {
      "id": "2",
      "label": "testing testing"
    },
    {
      "id": "3",
      "label": "testing testing"
    },
    {
      "id": "4",
      "label": "testing testing"
    }
  ]
};
