// Generated by the CU CMS. Do not edit.

import type { MobileDock } from '../types/site/mobile-dock';

export type { MobileDock };

export const MOBILE_DOCK: MobileDock = {
  "ctaLabel": "Register Now",
  "registerEyebrow": "Apply Today For",
  "registerHeading": "Chandigarh University Programs",
  "registerDeadlineNote": "Registration End Date (Phase - 1): 15 May 2026",
  "registerConsent": "By submitting this form, I agree to receive notifications from the University in the form of SMS/E-mail/Call.",
  "registerSubmitLabel": "APPLY NOW",
  "registerSuccessTitle": "Registration Submitted!",
  "registerSuccessBody": "Our counselors will contact you shortly.",
  "chatTitle": "Ask Us Anything",
  "chatStatus": "Usually replies instantly",
  "chatGreeting": "Hi there! I'm here to help. Ask me anything about us.",
  "chatPlaceholder": "Type your message...",
  "chatSuggestions": [
    {
      "id": "1",
      "label": "Courses offered"
    },
    {
      "id": "2",
      "label": "Fees & scholarships"
    },
    {
      "id": "3",
      "label": "Placements"
    },
    {
      "id": "4",
      "label": "Campus life"
    }
  ]
};
