// Generated by the CU CMS. Do not edit.

import type { Nav } from '../types/site/nav';

export type { Nav };

export const NAV: Nav = {
  "quickLinks": [
    {
      "label": "Placements",
      "href": "/placements",
      "order": 1
    },
    {
      "label": "Campuses",
      "href": "",
      "order": 2
    },
    {
      "label": "International",
      "href": "/international",
      "order": 3
    },
    {
      "label": "News",
      "href": "/news",
      "order": 4
    },
    {
      "label": "Contact Us",
      "href": "/contact",
      "order": 5
    }
  ],
  "partnerLogo": null,
  "columnLogos": [],
  "searchPlaceholder": "Ask anything about us...."
};
