// Generated by the CU CMS. Do not edit.

import type { Routes } from '../types/site/routes';

export type { Routes };

export const ROUTES: Routes = [
  {
    "path": "/",
    "siteSection": null,
    "navLabel": "testing testing",
    "navSummary": "",
    "order": 0,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1513258496099_48168024aec0_38d2e4fa8c.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "surface": "light",
    "cta": null
  },
  {
    "path": "/about",
    "siteSection": "about",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 0,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "what is this ?",
    "eyebrow": "testing testing",
    "title": "testing *testing*",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1497366216548_37526070297c_cc9da0bc35.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 801
    },
    "surface": "light",
    "cta": {
      "eyebrow": "testing testing",
      "title": "testing *testing*",
      "body": "testing testing",
      "primaryLabel": "testing testing",
      "primaryHref": "/admissions/how-to-apply",
      "secondaryLabel": "testing testing",
      "secondaryHref": "/programs",
      "tone": "accent"
    }
  },
  {
    "path": "/academics",
    "siteSection": "academics",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 0,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1513258496099_48168024aec0_38d2e4fa8c.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "surface": "light",
    "cta": {
      "eyebrow": "testing testing",
      "title": "testing *testing*",
      "body": "testing testing",
      "primaryLabel": "testing testing",
      "primaryHref": "/admissions/how-to-apply",
      "secondaryLabel": "testing testing",
      "secondaryHref": "/programs",
      "tone": "accent"
    }
  },
  {
    "path": "/admissions",
    "siteSection": "admissions",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 0,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1523240795612_9a054b0db644_4024e78648.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "surface": "light",
    "cta": {
      "eyebrow": "testing testing",
      "title": "testing *testing*",
      "body": "testing testing",
      "primaryLabel": "testing testing",
      "primaryHref": "/admissions/how-to-apply",
      "secondaryLabel": "testing testing",
      "secondaryHref": "/programs",
      "tone": "accent"
    }
  },
  {
    "path": "/ai-features",
    "siteSection": "ai-features",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 0,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing *testing*",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1503676260728_1c00da094a0b_1593d6bdd5.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 847
    },
    "surface": "light",
    "cta": {
      "eyebrow": "testing testing",
      "title": "testing *testing*",
      "body": "testing testing",
      "primaryLabel": "testing testing",
      "primaryHref": "/admissions/how-to-apply",
      "secondaryLabel": "testing testing",
      "secondaryHref": "/programs",
      "tone": "accent"
    }
  },
  {
    "path": "/campus-life",
    "siteSection": "campus-life",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 0,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1523050854058_8df90110c9f1_5d3933d7b4.png",
      "alt": "testing image",
      "width": 800,
      "height": 600
    },
    "surface": "light",
    "cta": {
      "eyebrow": "testing testing",
      "title": "testing *testing*",
      "body": "testing testing",
      "primaryLabel": "testing testing",
      "primaryHref": "/admissions/how-to-apply",
      "secondaryLabel": "testing testing",
      "secondaryHref": "/programs",
      "tone": "accent"
    }
  },
  {
    "path": "/research",
    "siteSection": "research",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 0,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing *testing*",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1497366216548_37526070297c_cc9da0bc35.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 801
    },
    "surface": "light",
    "cta": {
      "eyebrow": "testing testing",
      "title": "testing *testing*",
      "body": "testing testing",
      "primaryLabel": "testing testing",
      "primaryHref": "/admissions/how-to-apply",
      "secondaryLabel": "testing testing",
      "secondaryHref": "/programs",
      "tone": "accent"
    }
  },
  {
    "path": "/about/vision-mission",
    "siteSection": "about",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 1,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1523240795612_9a054b0db644_4024e78648.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "surface": "light",
    "cta": null
  },
  {
    "path": "/academics/list-of-holidays",
    "siteSection": "academics",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 1,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1562774053_701939374585_d6c47bbbb9.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 786
    },
    "surface": "light",
    "cta": null
  },
  {
    "path": "/admissions/how-to-apply",
    "siteSection": "admissions",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 1,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1531482615713_2afd69097998_6b6c6f5768.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "surface": "light",
    "cta": null
  },
  {
    "path": "/ai-features/ai-powered-learning",
    "siteSection": "ai-features",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 1,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1509062522246_3755977927d7_dd5c6e5f53.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 747
    },
    "surface": "light",
    "cta": null
  },
  {
    "path": "/campus-life/hostels",
    "siteSection": "campus-life",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 1,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1506905925346_21bda4d32df4_3e7d976a76.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "surface": "light",
    "cta": null
  },
  {
    "path": "/research/research-centers",
    "siteSection": "research",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 1,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1523240795612_9a054b0db644_4024e78648.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "surface": "light",
    "cta": null
  },
  {
    "path": "/about/core-values",
    "siteSection": "about",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 2,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1523050854058_8df90110c9f1_5d3933d7b4.png",
      "alt": "testing image",
      "width": 800,
      "height": 600
    },
    "surface": "light",
    "cta": null
  },
  {
    "path": "/academics/teaching-practices",
    "siteSection": "academics",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 2,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1503676260728_1c00da094a0b_1593d6bdd5.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 847
    },
    "surface": "light",
    "cta": null
  },
  {
    "path": "/admissions/scholarships",
    "siteSection": "admissions",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 2,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1524178232363_1fb2b075b655_4844aedea4.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "surface": "light",
    "cta": null
  },
  {
    "path": "/ai-features/ai-fuelled-research",
    "siteSection": "ai-features",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 2,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1513258496099_48168024aec0_38d2e4fa8c.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "surface": "light",
    "cta": null
  },
  {
    "path": "/campus-life/student-clubs",
    "siteSection": "campus-life",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 2,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1519389950473_47ba0277781c_004043fca3.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "surface": "light",
    "cta": null
  },
  {
    "path": "/research/patents-and-publications",
    "siteSection": "research",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 2,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1531482615713_2afd69097998_6b6c6f5768.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "surface": "light",
    "cta": null
  },
  {
    "path": "/about/leadership",
    "siteSection": "about",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 3,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1519389950473_47ba0277781c_004043fca3.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "surface": "light",
    "cta": null
  },
  {
    "path": "/academics/system-of-evaluation",
    "siteSection": "academics",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 3,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1509062522246_3755977927d7_dd5c6e5f53.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 747
    },
    "surface": "light",
    "cta": null
  },
  {
    "path": "/admissions/admission-criteria",
    "siteSection": "admissions",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 3,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1571260899304_425eee4c7efc_5ce92f65fd.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "surface": "light",
    "cta": null
  },
  {
    "path": "/ai-features/ai-powered-labs-coes",
    "siteSection": "ai-features",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 3,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1517486808906_6ca8b3f04846_4d025ae68f.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 1552
    },
    "surface": "light",
    "cta": null
  },
  {
    "path": "/campus-life/sports-and-fitness",
    "siteSection": "campus-life",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 3,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1541339907198_e08756dedf3f_6466a1a79a.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "surface": "light",
    "cta": null
  },
  {
    "path": "/research/startups-and-incubation",
    "siteSection": "research",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 3,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1524178232363_1fb2b075b655_4844aedea4.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "surface": "light",
    "cta": null
  },
  {
    "path": "/about/awards-and-recognitions",
    "siteSection": "about",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 4,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1522202176988_66273c2fd55f_e8afb4bee4.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "surface": "light",
    "cta": null
  },
  {
    "path": "/academics/professional-bodies",
    "siteSection": "academics",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 4,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1517486808906_6ca8b3f04846_4d025ae68f.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 1552
    },
    "surface": "light",
    "cta": null
  },
  {
    "path": "/admissions/course-fees",
    "siteSection": "admissions",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 4,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1523050854058_8df90110c9f1_5d3933d7b4.png",
      "alt": "testing image",
      "width": 800,
      "height": 600
    },
    "surface": "light",
    "cta": null
  },
  {
    "path": "/ai-features/smart-campus-features",
    "siteSection": "ai-features",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 4,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1571260899304_425eee4c7efc_5ce92f65fd.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "surface": "light",
    "cta": null
  },
  {
    "path": "/campus-life/library-and-e-resources",
    "siteSection": "campus-life",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 4,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1522202176988_66273c2fd55f_e8afb4bee4.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "surface": "light",
    "cta": null
  },
  {
    "path": "/about/cu-edge",
    "siteSection": "about",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 5,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1541339907198_e08756dedf3f_6466a1a79a.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "surface": "light",
    "cta": null
  },
  {
    "path": "/academics/futuristic-laboratories",
    "siteSection": "academics",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 5,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1524178232363_1fb2b075b655_4844aedea4.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "surface": "light",
    "cta": null
  },
  {
    "path": "/admissions/hostel-fees",
    "siteSection": "admissions",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 5,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1497366216548_37526070297c_cc9da0bc35.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 801
    },
    "surface": "light",
    "cta": null
  },
  {
    "path": "/ai-features/ai-competencies",
    "siteSection": "ai-features",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 5,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1562774053_701939374585_d6c47bbbb9.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 786
    },
    "surface": "light",
    "cta": null
  },
  {
    "path": "/about/recognition-and-approvals",
    "siteSection": "about",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 6,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1531482615713_2afd69097998_6b6c6f5768.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "surface": "light",
    "cta": null
  },
  {
    "path": "/admissions/admission-offices",
    "siteSection": "admissions",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 6,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1506905925346_21bda4d32df4_3e7d976a76.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "surface": "light",
    "cta": null
  },
  {
    "path": "/admissions/education-loan",
    "siteSection": "admissions",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 7,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1541339907198_e08756dedf3f_6466a1a79a.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "surface": "light",
    "cta": null
  },
  {
    "path": "/admissions/advanced-credit-program",
    "siteSection": "admissions",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 8,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1522202176988_66273c2fd55f_e8afb4bee4.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "surface": "light",
    "cta": null
  },
  {
    "path": "/admissions/faqs",
    "siteSection": "admissions",
    "navLabel": "testing testing",
    "navSummary": "testing testing",
    "order": 9,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1519389950473_47ba0277781c_004043fca3.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "surface": "light",
    "cta": null
  },
  {
    "path": "/contact",
    "siteSection": null,
    "navLabel": "testing testing",
    "navSummary": "",
    "order": 100,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1517486808906_6ca8b3f04846_4d025ae68f.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 1552
    },
    "surface": "light",
    "cta": {
      "eyebrow": "testing testing",
      "title": "testing testing",
      "body": "testing testing",
      "primaryLabel": "testing testing",
      "primaryHref": "/admissions/how-to-apply",
      "secondaryLabel": "",
      "secondaryHref": "",
      "tone": "accent"
    }
  },
  {
    "path": "/international",
    "siteSection": null,
    "navLabel": "testing testing",
    "navSummary": "",
    "order": 101,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing *testing*",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1509062522246_3755977927d7_dd5c6e5f53.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 747
    },
    "surface": "light",
    "cta": {
      "eyebrow": "testing testing",
      "title": "testing *testing*",
      "body": "testing testing",
      "primaryLabel": "testing testing",
      "primaryHref": "/admissions/how-to-apply",
      "secondaryLabel": "testing testing",
      "secondaryHref": "/programs",
      "tone": "accent"
    }
  },
  {
    "path": "/news",
    "siteSection": null,
    "navLabel": "testing testing",
    "navSummary": "",
    "order": 102,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1503676260728_1c00da094a0b_1593d6bdd5.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 847
    },
    "surface": "light",
    "cta": {
      "eyebrow": "testing testing",
      "title": "testing *testing*",
      "body": "testing testing",
      "primaryLabel": "testing testing",
      "primaryHref": "/admissions/how-to-apply",
      "secondaryLabel": "testing testing",
      "secondaryHref": "/programs",
      "tone": "accent"
    }
  },
  {
    "path": "/placements",
    "siteSection": null,
    "navLabel": "testing testing",
    "navSummary": "",
    "order": 103,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1571260899304_425eee4c7efc_5ce92f65fd.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "surface": "light",
    "cta": {
      "eyebrow": "testing testing",
      "title": "testing *testing*",
      "body": "testing testing",
      "primaryLabel": "testing testing",
      "primaryHref": "/admissions/how-to-apply",
      "secondaryLabel": "testing testing",
      "secondaryHref": "/programs",
      "tone": "accent"
    }
  },
  {
    "path": "/programs",
    "siteSection": null,
    "navLabel": "testing testing",
    "navSummary": "",
    "order": 104,
    "seoTitle": "testing testing",
    "seoDescription": "testing testing",
    "canonical": "",
    "eyebrow": "testing testing",
    "title": "testing testing",
    "lede": "",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1506905925346_21bda4d32df4_3e7d976a76.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "surface": "light",
    "cta": {
      "eyebrow": "testing testing",
      "title": "testing *testing*",
      "body": "testing testing",
      "primaryLabel": "testing testing",
      "primaryHref": "/admissions/how-to-apply",
      "secondaryLabel": "testing testing",
      "secondaryHref": "/admissions/course-fees",
      "tone": "accent"
    }
  }
];
