// Generated by the CU CMS. Do not edit.

import type { Sections } from '../types/site/sections';

export type { Sections };

export const SECTIONS: Sections = [
  {
    "slug": "about",
    "label": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "order": 1,
    "routes": null,
    "navHref": "/about",
    "hasDropdown": true,
    "listsPrograms": false
  },
  {
    "slug": "academics",
    "label": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "order": 2,
    "routes": null,
    "navHref": "/academics",
    "hasDropdown": true,
    "listsPrograms": false
  },
  {
    "slug": "admissions",
    "label": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "order": 3,
    "routes": null,
    "navHref": "/admissions",
    "hasDropdown": true,
    "listsPrograms": false
  },
  {
    "slug": "campus-life",
    "label": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "order": 4,
    "routes": null,
    "navHref": "/campus-life",
    "hasDropdown": true,
    "listsPrograms": false
  },
  {
    "slug": "research",
    "label": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "order": 5,
    "routes": null,
    "navHref": "/research",
    "hasDropdown": true,
    "listsPrograms": false
  },
  {
    "slug": "ai-features",
    "label": "testing testing",
    "title": "testing testing",
    "lede": "testing testing",
    "order": 6,
    "routes": null,
    "navHref": "/ai-features",
    "hasDropdown": true,
    "listsPrograms": false
  }
];
