// Generated by the CU CMS. Do not edit.

import type { CmsImage } from './media';

export type InternationalCard = {
  id: string;
  title: string;
  text: string;
  image: CmsImage;
  link: string | null;
};

export type InternationalSection = {
  /** Accent-marked headline — see `parseAccentHeading`. */
  heading: string;
  subheading: string;
  cards: InternationalCard[];
  partnerLogos: CmsImage[];
};
