// Generated by the CU CMS. Do not edit.

export type CmsImage = {
  url: string;
  alt: string;
  width: number | null;
  height: number | null;
};

export type CmsVideo = {
  url: string;
  /** MIME type, used for the `<source type>` hint. */
  mime: string;
};
