// Generated by the CU CMS. Do not edit.

export type ChatSuggestion = {
  id: string;
  label: string;
};

export type MobileDock = {
  ctaLabel: string;
  registerEyebrow: string;
  registerHeading: string;
  registerDeadlineNote: string;
  registerConsent: string;
  registerSubmitLabel: string;
  registerSuccessTitle: string;
  registerSuccessBody: string;
  chatTitle: string;
  chatStatus: string;
  chatGreeting: string;
  chatPlaceholder: string;
  chatSuggestions: ChatSuggestion[];
};
