// Generated by the CU CMS. Do not edit.

import type { CmsImage } from './media';

export type NewsTabGroup = 'signature-events' | 'celebrity-news' | 'academic-archives';

/**
 * Which surface a collapsed tab paints. Positional, exactly as the static data
 * had it: only `white` is actually branched on, for the last rail.
 */
export type NewsTabTheme = 'active' | 'light' | 'white';

export type NewsStory = {
  /** Accent-marked headline. `\n` is the line break the tall card renders. */
  title: string;
  description: string;
  image: CmsImage;
};

export type NewsTab = {
  /** Position in the rail. Also the value `activeTab` holds. */
  id: number;
  /** Accent-marked label — the grey lead-in, then the red run. */
  label: string;
  theme: NewsTabTheme;
  stories: NewsStory[];
};

export type NewsArticle = {
  titleAccent: string;
  titleLead: string;
  titleHighlight: string;
  titleTail: string;
  image: CmsImage;
  author: {
    name: string;
    role: string;
    avatar: CmsImage;
  };
};

export type NewsSection = {
  /** Accent-marked headline — see `parseAccentHeading`. */
  heading: string;
  tabs: NewsTab[];
  articles: NewsArticle[];
};
