// Generated by the CU CMS. Do not edit.

export type ScholarshipSlab = {
  id: string;
  marks: string;
  award: string;
};

export type ProgramsSection = {
  /** Accent-marked headline — see `parseAccentHeading`. */
  heading: string;
  subheading: string;
  cucetEyebrow: string;
  /** Accent-marked headline — see `parseAccentHeading`. */
  cucetHeading: string;
  cucetDescription: string;
  /** ISO 8601. `null` retires the countdown and leaves the closing line alone. */
  cucetDeadline: string | null;
  cucetDeadlineLabel: string;
  cucetCtaLabel: string;
  cucetCtaLink: string;
  cucetHelpline: string;
  slabs: ScholarshipSlab[];
};
