// Generated by the CU CMS. Do not edit.

import type { CmsImage } from './media';

export type SeeUsIcon =
  | 'building'
  | 'book'
  | 'cpu'
  | 'sports'
  | 'tree'
  | 'microscope'
  | 'bed'
  | 'utensils';

export type SeeUsCategory = {
  id: string;
  /** `\n` is a line break — the strip labels are two lines wherever they fit. */
  title: string;
  icon: SeeUsIcon;
  videoUrl: string;
  image: CmsImage;
};

export type SeeUsCarouselItem = {
  id: string;
  title: string;
  videoLink: string;
  image: CmsImage;
};

export type SeeUsInActionSection = {
  /** Accent-marked headline — see `parseAccentHeading`. */
  heading: string;
  subheading: string;
  categories: SeeUsCategory[];
  carousel: SeeUsCarouselItem[];
};
