// Generated by the CU CMS. Do not edit.

import type { CmsImage, CmsVideo } from './media';

export type StepInsideSection = {
  /** Accent-marked headline — see `parseAccentHeading`. */
  heading: string;
  video: CmsVideo;
  poster: CmsImage;
};
