// Generated by the CU CMS. Do not edit.

export type Paragraph = {
  text: string;
};

export type AdmissionStep = {
  title: string;
  body: string;
};

export type Point = {
  label: string;
};

export type Practice = {
  title: string;
  body: string;
  points: Point[];
};

export type Academics = {
  intro: Paragraph[];
  teachingLede: string;
  evaluationLede: string;
  professionalBodiesLede: string;
  labsLede: string;
  holidaysTitle: string;
  holidaysPeriod: string;
  admissionSteps: AdmissionStep[];
  teachingDesignGoals: Practice[];
};
