// Generated by the CU CMS. Do not edit.

export type CriterionPoint = {
  text: string;
};

export type Criterion = {
  title: string;
  body: string;
  points: CriterionPoint[];
};

export type Pathway = {
  label: string;
  level: 'UG' | 'PG' | 'both' | null;
  requirement: string;
  href: string;
};

export type EdgeStat = {
  value: string;
  label: string;
};

export type Admissions = {
  scholarshipLede: string;
  cucetScholarshipBody: string;
  cucetScholarshipCap: string;
  meritContinuation: string;
  concessionContinuation: string;
  scholarshipSpecialNote: string;
  admissionCriteriaLede: string;
  generalCriteria: Criterion[];
  pathways: Pathway[];
  edgeStats: EdgeStat[];
};
