// Generated by the CU CMS. Do not edit.

export type Paragraph = {
  text: string;
};

export type AiFeatures = {
  intro: Paragraph[];
  competenciesIntro: string;
  competencySchools: string[];
};
