// Generated by the CU CMS. Do not edit.

import type { CmsImage } from '../media';

export type Facility = {
  name: string;
  body: string;
  image: CmsImage | null;
};

export type Fact = {
  label: string;
  value: string;
};

export type CampusLife = {
  facilities: Facility[];
  hostelFacts: Fact[];
};
