// Generated by the CU CMS. Do not edit.

export type FeeRow = {
  label: string;
  amount: string;
};

export type ScholarshipTier = {
  band: string;
  scholarshipAmount: string;
  amountToPay: string;
};

export type CourseFees = {
  programDuration: string;
  programFees: FeeRow[];
  scholarshipTiers: ScholarshipTier[];
};
