// Generated by the CU CMS. Do not edit.

export type Room = {
  roomType: string;
  audience: 'indian' | 'saarc' | 'international';
  rate: string;
  period: string;
  note: string;
};

export type HostelFees = {
  lede: string;
  rooms: Room[];
  note: string;
};
