// Generated by the CU CMS. Do not edit.

import type { CmsImage } from '../media';

export type Step = {
  num: string;
  title: string;
  body: string;
  ctaLabel: string;
  ctaHref: string;
  image: CmsImage | null;
};

export type HowToApply = {
  heading: string;
  lede: string;
  steps: Step[];
  outcomeTitle: string;
  outcomeBody: string;
};
