// Generated by the CU CMS. Do not edit.

import type { CmsImage } from '../media';

export type Paragraph = {
  text: string;
};

export type Block = {
  anchorId: string;
  index: string;
  label: string;
  title: string;
  paragraphs: Paragraph[];
};

export type Chip = {
  label: string;
};

export type GalleryGroup = {
  groupId: string;
  label: string;
  images: CmsImage[];
};

export type LeavesRow = {
  siteRoute: string | null;
  intro: string;
  blocks: Block[];
  chips: Chip[];
  gallery: GalleryGroup[];
};

export type Leaves = LeavesRow[];
