// Generated by the CU CMS. Do not edit.

export type ContactIcon = 'whatsapp' | 'phone' | 'globe';

export type SocialPlatform =
  | 'facebook'
  | 'x'
  | 'linkedin'
  | 'instagram'
  | 'youtube'
  | 'website';

export type ContactLink = {
  id: string;
  label: string;
  link: string;
  icon: ContactIcon;
};

export type SocialLink = {
  id: string;
  platform: SocialPlatform;
  link: string;
};

export type AnnouncementBar = {
  message: string;
  ctaLabel: string;
  contactLinks: ContactLink[];
  socialLinks: SocialLink[];
};
