// Generated by the CU CMS. Do not edit.

import type { CmsImage } from '../media';

export type CtaBand = {
  eyebrow: string;
  title: string;
  body: string;
  primaryLabel: string;
  primaryHref: string;
  secondaryLabel: string;
  secondaryHref: string;
  tone: 'accent' | 'neutral' | null;
};

export type RoutesRow = {
  path: string;
  siteSection: string | null;
  navLabel: string;
  navSummary: string;
  order: number;
  seoTitle: string;
  seoDescription: string;
  canonical: string;
  eyebrow: string;
  title: string;
  lede: string;
  heroImage: CmsImage | null;
  surface: 'light' | 'dark';
  cta: CtaBand | null;
};

export type Routes = RoutesRow[];
