// Generated by the CU CMS. Do not edit.

export type SectionsRow = {
  slug: string;
  label: string;
  title: string;
  lede: string;
  order: number;
  routes: string | null;
  navHref: string;
  hasDropdown: boolean;
  listsPrograms: boolean;
};

export type Sections = SectionsRow[];
