// Generated by the CU CMS. Do not edit.

import type { AdmissionOffices } from '../types/data/admission-offices';

export type { AdmissionOffices };

export const ADMISSION_OFFICES: AdmissionOffices = [
  {
    "city": "testing testing",
    "state": "0000",
    "address": "testing testing",
    "contactName": "testing testing",
    "phone": "0000",
    "landline": "0000",
    "email": "",
    "isCampus": false
  },
  {
    "city": "testing testing",
    "state": "0000",
    "address": "testing testing",
    "contactName": "testing testing",
    "phone": "0000",
    "landline": "0000",
    "email": "",
    "isCampus": false
  },
  {
    "city": "testing testing",
    "state": "0000",
    "address": "testing testing",
    "contactName": "testing testing",
    "phone": "0000",
    "landline": "0000",
    "email": "",
    "isCampus": false
  },
  {
    "city": "testing testing",
    "state": "0000",
    "address": "testing testing",
    "contactName": "testing testing",
    "phone": "0000",
    "landline": "0000",
    "email": "",
    "isCampus": false
  },
  {
    "city": "testing testing",
    "state": "0000",
    "address": "testing testing",
    "contactName": "testing testing",
    "phone": "0000",
    "landline": "0000",
    "email": "",
    "isCampus": false
  },
  {
    "city": "testing testing",
    "state": "0000",
    "address": "testing testing",
    "contactName": "testing testing",
    "phone": "0000",
    "landline": "0000",
    "email": "",
    "isCampus": false
  },
  {
    "city": "testing testing",
    "state": "0000",
    "address": "testing testing",
    "contactName": "testing testing",
    "phone": "0000",
    "landline": "0000",
    "email": "",
    "isCampus": false
  },
  {
    "city": "testing testing",
    "state": "0000",
    "address": "testing testing",
    "contactName": "testing testing",
    "phone": "0000",
    "landline": "0000",
    "email": "",
    "isCampus": false
  },
  {
    "city": "testing testing",
    "state": "0000",
    "address": "testing testing",
    "contactName": "testing testing",
    "phone": "0000",
    "landline": "0000",
    "email": "",
    "isCampus": false
  },
  {
    "city": "testing testing",
    "state": "0000",
    "address": "testing testing",
    "contactName": "testing testing",
    "phone": "0000",
    "landline": "0000",
    "email": "",
    "isCampus": false
  },
  {
    "city": "testing testing",
    "state": "0000",
    "address": "testing testing",
    "contactName": "testing testing",
    "phone": "0000",
    "landline": "0000",
    "email": "",
    "isCampus": false
  },
  {
    "city": "testing testing",
    "state": "0000",
    "address": "testing testing",
    "contactName": "testing testing",
    "phone": "0000",
    "landline": "0000",
    "email": "",
    "isCampus": false
  },
  {
    "city": "testing testing",
    "state": "0000",
    "address": "testing testing",
    "contactName": "testing testing",
    "phone": "0000",
    "landline": "",
    "email": "",
    "isCampus": false
  },
  {
    "city": "testing testing",
    "state": "0000",
    "address": "testing testing",
    "contactName": "testing testing",
    "phone": "0000",
    "landline": "0000",
    "email": "",
    "isCampus": false
  },
  {
    "city": "testing testing",
    "state": "0000",
    "address": "testing testing",
    "contactName": "testing testing",
    "phone": "0000",
    "landline": "",
    "email": "",
    "isCampus": false
  },
  {
    "city": "testing testing",
    "state": "0000",
    "address": "testing testing",
    "contactName": "testing testing",
    "phone": "0000",
    "landline": "0000",
    "email": "",
    "isCampus": false
  },
  {
    "city": "testing testing",
    "state": "0000",
    "address": "testing testing",
    "contactName": "testing testing",
    "phone": "0000",
    "landline": "",
    "email": "",
    "isCampus": false
  },
  {
    "city": "testing testing",
    "state": "0000",
    "address": "testing testing",
    "contactName": "testing testing",
    "phone": "0000",
    "landline": "",
    "email": "",
    "isCampus": false
  },
  {
    "city": "testing testing",
    "state": "0000",
    "address": "testing testing",
    "contactName": "testing testing",
    "phone": "0000",
    "landline": "0000",
    "email": "",
    "isCampus": false
  },
  {
    "city": "testing testing",
    "state": "0000",
    "address": "testing testing",
    "contactName": "testing testing",
    "phone": "0000",
    "landline": "0000",
    "email": "",
    "isCampus": false
  },
  {
    "city": "testing testing",
    "state": "0000",
    "address": "testing testing",
    "contactName": "testing testing",
    "phone": "0000",
    "landline": "",
    "email": "",
    "isCampus": false
  },
  {
    "city": "testing testing",
    "state": "0000",
    "address": "testing testing",
    "contactName": "testing testing",
    "phone": "0000",
    "landline": "0000",
    "email": "",
    "isCampus": false
  },
  {
    "city": "testing testing",
    "state": "0000",
    "address": "testing testing",
    "contactName": "testing testing",
    "phone": "0000",
    "landline": "",
    "email": "",
    "isCampus": false
  },
  {
    "city": "testing testing",
    "state": "0000",
    "address": "#401, 4th Floor, Royal Centre, Ulubari, Guwahati, Assam 781007",
    "contactName": "testing testing",
    "phone": "0000",
    "landline": "",
    "email": "",
    "isCampus": false
  },
  {
    "city": "testing testing",
    "state": "0000",
    "address": "testing testing",
    "contactName": "testing testing",
    "phone": "0000",
    "landline": "",
    "email": "",
    "isCampus": false
  },
  {
    "city": "testing testing",
    "state": "0000",
    "address": "testing testing",
    "contactName": "testing testing",
    "phone": "0000",
    "landline": "",
    "email": "",
    "isCampus": false
  },
  {
    "city": "testing testing",
    "state": "0000",
    "address": "testing testing",
    "contactName": "testing testing",
    "phone": "0000",
    "landline": "0000",
    "email": "",
    "isCampus": false
  },
  {
    "city": "testing testing",
    "state": "0000",
    "address": "testing testing",
    "contactName": "testing testing",
    "phone": "0000",
    "landline": "0000",
    "email": "",
    "isCampus": false
  },
  {
    "city": "testing testing",
    "state": "0000",
    "address": "testing testing",
    "contactName": "testing testing",
    "phone": "0000",
    "landline": "0000",
    "email": "",
    "isCampus": false
  },
  {
    "city": "testing testing",
    "state": "0000",
    "address": "testing testing",
    "contactName": "testing testing",
    "phone": "0000",
    "landline": "",
    "email": "",
    "isCampus": false
  },
  {
    "city": "testing testing",
    "state": "0000",
    "address": "testing testing",
    "contactName": "testing testing",
    "phone": "0000",
    "landline": "",
    "email": "",
    "isCampus": false
  },
  {
    "city": "testing testing",
    "state": "0000",
    "address": "testing testing",
    "contactName": "testing testing",
    "phone": "0000",
    "landline": "",
    "email": "",
    "isCampus": false
  },
  {
    "city": "testing testing",
    "state": "0000",
    "address": "testing testing",
    "contactName": "testing testing",
    "phone": "0000",
    "landline": "",
    "email": "",
    "isCampus": false
  }
];
