// Generated by the CU CMS. Do not edit.

import type { CucetSlabs } from '../types/data/cucet-slabs';

export type { CucetSlabs };

export const CUCET_SLABS: CucetSlabs = [
  {
    "phase": "phase-2",
    "band": "testing testing",
    "value": "0000",
    "note": "",
    "order": 100
  },
  {
    "phase": "phase-2",
    "band": "testing testing",
    "value": "0000",
    "note": "",
    "order": 101
  },
  {
    "phase": "phase-2",
    "band": "testing testing",
    "value": "0000",
    "note": "",
    "order": 102
  },
  {
    "phase": "phase-2",
    "band": "testing testing",
    "value": "0000",
    "note": "",
    "order": 103
  },
  {
    "phase": "phase-2",
    "band": "testing testing",
    "value": "0000",
    "note": "",
    "order": 104
  },
  {
    "phase": "phase-2",
    "band": "testing testing",
    "value": "0000",
    "note": "",
    "order": 105
  }
];
