// Generated by the CU CMS. Do not edit.

import type { GoverningBody } from '../types/data/governing-body';

export type { GoverningBody };

export const GOVERNING_BODY: GoverningBody = [
  {
    "slug": "governing-body",
    "name": "testing testing",
    "lede": "",
    "members": [
      {
        "seat": "testing testing",
        "position": "testing testing"
      },
      {
        "seat": "testing testing",
        "position": "testing testing"
      },
      {
        "seat": "testing testing",
        "position": "testing testing"
      },
      {
        "seat": "testing testing",
        "position": "testing testing"
      },
      {
        "seat": "testing testing",
        "position": "testing testing"
      },
      {
        "seat": "testing testing",
        "position": "testing testing"
      },
      {
        "seat": "testing testing",
        "position": "testing testing"
      }
    ],
    "order": 1
  },
  {
    "slug": "academic-council",
    "name": "testing testing",
    "lede": "",
    "members": [
      {
        "seat": "testing testing",
        "position": ""
      },
      {
        "seat": "testing testing",
        "position": ""
      },
      {
        "seat": "testing testing",
        "position": ""
      },
      {
        "seat": "testing testing",
        "position": ""
      },
      {
        "seat": "testing testing",
        "position": ""
      },
      {
        "seat": "testing testing",
        "position": ""
      },
      {
        "seat": "testing testing",
        "position": ""
      },
      {
        "seat": "testing testing",
        "position": ""
      },
      {
        "seat": "testing testing",
        "position": ""
      },
      {
        "seat": "testing testing",
        "position": ""
      },
      {
        "seat": "testing testing",
        "position": ""
      },
      {
        "seat": "testing testing",
        "position": ""
      }
    ],
    "order": 2
  },
  {
    "slug": "executive-council",
    "name": "testing testing",
    "lede": "",
    "members": [
      {
        "seat": "testing testing",
        "position": ""
      },
      {
        "seat": "testing testing",
        "position": ""
      },
      {
        "seat": "testing testing",
        "position": ""
      },
      {
        "seat": "testing testing",
        "position": ""
      },
      {
        "seat": "testing testing",
        "position": ""
      },
      {
        "seat": "testing testing",
        "position": ""
      },
      {
        "seat": "testing testing",
        "position": ""
      },
      {
        "seat": "testing testing",
        "position": ""
      },
      {
        "seat": "testing testing",
        "position": ""
      }
    ],
    "order": 3
  }
];
