// Generated by the CU CMS. Do not edit.

import type { GoverningBody } from '../types/data/governing-body';

export type { GoverningBody };

export const GOVERNING_BODY: GoverningBody = [
  {
    "slug": "governing-body",
    "name": "The Governing Body",
    "lede": "",
    "members": [
      {
        "seat": "The Chancellor",
        "position": "Chairperson"
      },
      {
        "seat": "Vice Chancellor",
        "position": "Member"
      },
      {
        "seat": "Three persons nominated by the Trust, out of whom two shall be eminent educationist",
        "position": "Member"
      },
      {
        "seat": "One expert member of management or information technology",
        "position": "Member"
      },
      {
        "seat": "One expert of finance, nominated by the Chancellor",
        "position": "Member"
      },
      {
        "seat": "One officer of the State Government not below the rank of Joint Secretary to the Government of Uttar Pradesh",
        "position": "Member"
      },
      {
        "seat": "Registrar",
        "position": "Ex-officio Member Secretary"
      }
    ],
    "order": 1
  },
  {
    "slug": "academic-council",
    "name": "The Academic Council",
    "lede": "",
    "members": [
      {
        "seat": "The Vice-Chancellor — Chairman",
        "position": ""
      },
      {
        "seat": "One eminent academician nominated by the State Govt. as its representative",
        "position": ""
      },
      {
        "seat": "Dean of Academic Affairs",
        "position": ""
      },
      {
        "seat": "Dean Students Welfare",
        "position": ""
      },
      {
        "seat": "Dean of Faculties",
        "position": ""
      },
      {
        "seat": "Heads of University Departments of Studies",
        "position": ""
      },
      {
        "seat": "Controller of Examinations",
        "position": ""
      },
      {
        "seat": "Two University Professors who are not Heads of Departments, by rotation according to seniority",
        "position": ""
      },
      {
        "seat": "Two Associate Professors and two Assistant Professors from the University Teaching Departments, by rotation according to seniority",
        "position": ""
      },
      {
        "seat": "Librarian",
        "position": ""
      },
      {
        "seat": "Four persons being specialists in different branches of knowledge, not being employees of the University, to be nominated by the Chancellor",
        "position": ""
      },
      {
        "seat": "Registrar — Ex-officio Member Secretary",
        "position": ""
      }
    ],
    "order": 2
  },
  {
    "slug": "executive-council",
    "name": "The Executive Council",
    "lede": "",
    "members": [
      {
        "seat": "Vice-Chancellor — Chairperson",
        "position": ""
      },
      {
        "seat": "Three members to be nominated by the Governing Body",
        "position": ""
      },
      {
        "seat": "Two eminent educationists nominated by the Chancellor",
        "position": ""
      },
      {
        "seat": "One officer of the State Government not below the rank of Joint Secretary to the Government of Uttar Pradesh",
        "position": ""
      },
      {
        "seat": "One Professor of the University",
        "position": ""
      },
      {
        "seat": "One Associate Professor of the University",
        "position": ""
      },
      {
        "seat": "One eminent educationist not below the rank of Associate Professor, from the panel of three names to be approved by the State Government",
        "position": ""
      },
      {
        "seat": "Registrar — Ex-officio Member Secretary",
        "position": ""
      },
      {
        "seat": "Finance Officer — Invited member",
        "position": ""
      }
    ],
    "order": 3
  }
];
