// Generated by the CU CMS. Do not edit.

import type { Holidays } from '../types/data/holidays';

export type { Holidays };

export const HOLIDAYS: Holidays = [
  {
    "event": "testing testing",
    "year": 2020,
    "date": "testing testing",
    "day": "testing testing",
    "order": 1
  },
  {
    "event": "testing testing",
    "year": 2020,
    "date": "testing testing",
    "day": "testing testing",
    "order": 2
  },
  {
    "event": "testing testing",
    "year": 2020,
    "date": "testing testing",
    "day": "testing testing",
    "order": 3
  },
  {
    "event": "testing testing",
    "year": 2020,
    "date": "testing testing",
    "day": "testing testing",
    "order": 4
  },
  {
    "event": "testing testing",
    "year": 2020,
    "date": "testing testing",
    "day": "testing testing",
    "order": 5
  },
  {
    "event": "testing testing",
    "year": 2020,
    "date": "testing testing",
    "day": "testing testing",
    "order": 6
  },
  {
    "event": "testing testing",
    "year": 2020,
    "date": "testing testing",
    "day": "testing testing",
    "order": 7
  },
  {
    "event": "testing testing",
    "year": 2020,
    "date": "testing testing",
    "day": "testing testing",
    "order": 8
  },
  {
    "event": "testing testing",
    "year": 2020,
    "date": "testing testing",
    "day": "testing testing",
    "order": 9
  },
  {
    "event": "testing testing",
    "year": 2020,
    "date": "testing testing",
    "day": "testing testing",
    "order": 10
  },
  {
    "event": "testing testing",
    "year": 2020,
    "date": "testing testing",
    "day": "testing testing",
    "order": 11
  },
  {
    "event": "testing testing",
    "year": 2020,
    "date": "testing testing",
    "day": "testing testing",
    "order": 12
  },
  {
    "event": "testing testing",
    "year": 2020,
    "date": "testing testing",
    "day": "testing testing",
    "order": 13
  }
];
