// Generated by the CU CMS. Do not edit.

import type { Holidays } from '../types/data/holidays';

export type { Holidays };

export const HOLIDAYS: Holidays = [
  {
    "event": "Makar Sankranti",
    "year": 2026,
    "date": "January 14",
    "day": "Wednesday",
    "order": 1
  },
  {
    "event": "Republic Day",
    "year": 2026,
    "date": "January 26",
    "day": "Monday",
    "order": 2
  },
  {
    "event": "Holi",
    "year": 2026,
    "date": "March 04",
    "day": "Wednesday",
    "order": 3
  },
  {
    "event": "Eid al-Fitr",
    "year": 2026,
    "date": "March 20",
    "day": "Friday",
    "order": 4
  },
  {
    "event": "Shri Ram Navami",
    "year": 2026,
    "date": "March 27",
    "day": "Friday",
    "order": 5
  },
  {
    "event": "Dr. B.R. Ambedkar Jayanti",
    "year": 2026,
    "date": "April 14",
    "day": "Tuesday",
    "order": 6
  },
  {
    "event": "Eid al-Adha",
    "year": 2026,
    "date": "May 27",
    "day": "Wednesday",
    "order": 7
  },
  {
    "event": "Independence Day",
    "year": 2026,
    "date": "August 15",
    "day": "Saturday",
    "order": 8
  },
  {
    "event": "Mahatma Gandhi Jayanti",
    "year": 2026,
    "date": "October 02",
    "day": "Friday",
    "order": 9
  },
  {
    "event": "Dussehra",
    "year": 2026,
    "date": "October 20",
    "day": "Tuesday",
    "order": 10
  },
  {
    "event": "Deepawali",
    "year": 2026,
    "date": "November 09",
    "day": "Monday",
    "order": 11
  },
  {
    "event": "Gurupurab, Birthday Shri Gurunanak Dev Ji",
    "year": 2026,
    "date": "November 24",
    "day": "Tuesday",
    "order": 12
  },
  {
    "event": "Christmas",
    "year": 2026,
    "date": "December 25",
    "day": "Friday",
    "order": 13
  }
];
