// Generated by the CU CMS. Do not edit.

import type { Laboratories } from '../types/data/laboratories';

export type { Laboratories };

export const LABORATORIES: Laboratories = [
  {
    "slug": "centre-of-immersive-pharmacology",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1531482615713_2afd69097998_6b6c6f5768.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "order": 1
  },
  {
    "slug": "ba-psychology",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1523240795612_9a054b0db644_4024e78648.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "order": 2
  },
  {
    "slug": "physics-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1524178232363_1fb2b075b655_4844aedea4.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "order": 3
  },
  {
    "slug": "chemistry-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1562774053_701939374585_d6c47bbbb9.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 786
    },
    "order": 4
  },
  {
    "slug": "cell-biology-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1513258496099_48168024aec0_38d2e4fa8c.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "order": 5
  },
  {
    "slug": "biochemistry-and-metabolism-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1517486808906_6ca8b3f04846_4d025ae68f.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 1552
    },
    "order": 6
  },
  {
    "slug": "laboratory-techniques-in-biotechnology-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1509062522246_3755977927d7_dd5c6e5f53.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 747
    },
    "order": 7
  },
  {
    "slug": "design-and-modelling-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1503676260728_1c00da094a0b_1593d6bdd5.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 847
    },
    "order": 8
  },
  {
    "slug": "civil-workshop",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1571260899304_425eee4c7efc_5ce92f65fd.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "order": 9
  },
  {
    "slug": "building-information-modelling-bim-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1506905925346_21bda4d32df4_3e7d976a76.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "order": 10
  },
  {
    "slug": "building-materials-and-concrete-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1522202176988_66273c2fd55f_e8afb4bee4.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "order": 11
  },
  {
    "slug": "advanced-structural-design-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1523050854058_8df90110c9f1_5d3933d7b4.png",
      "alt": "testing image",
      "width": 800,
      "height": 600
    },
    "order": 12
  },
  {
    "slug": "geotechnical-engineering-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1541339907198_e08756dedf3f_6466a1a79a.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "order": 13
  },
  {
    "slug": "environmental-engineering-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1519389950473_47ba0277781c_004043fca3.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "order": 14
  },
  {
    "slug": "engineering-surveying-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1497366216548_37526070297c_cc9da0bc35.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 801
    },
    "order": 15
  },
  {
    "slug": "transportation-engineering-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1531482615713_2afd69097998_6b6c6f5768.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "order": 16
  },
  {
    "slug": "project-management-software-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1523240795612_9a054b0db644_4024e78648.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "order": 17
  },
  {
    "slug": "contract-management-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1524178232363_1fb2b075b655_4844aedea4.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "order": 18
  },
  {
    "slug": "robotics-automation-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1562774053_701939374585_d6c47bbbb9.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 786
    },
    "order": 19
  },
  {
    "slug": "smart-machining-and-fabrication-smf-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1513258496099_48168024aec0_38d2e4fa8c.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "order": 20
  },
  {
    "slug": "drone-technology-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1517486808906_6ca8b3f04846_4d025ae68f.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 1552
    },
    "order": 21
  },
  {
    "slug": "electric-vehicles-technology-evt-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1509062522246_3755977927d7_dd5c6e5f53.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 747
    },
    "order": 22
  },
  {
    "slug": "sustainable-tribology-materials-research-stmr-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1503676260728_1c00da094a0b_1593d6bdd5.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 847
    },
    "order": 23
  },
  {
    "slug": "advanced-computational-research-acr-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1571260899304_425eee4c7efc_5ce92f65fd.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "order": 24
  },
  {
    "slug": "circuit-innovators-hub",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1506905925346_21bda4d32df4_3e7d976a76.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "order": 25
  },
  {
    "slug": "nano-electronics-with-ai-ml-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1522202176988_66273c2fd55f_e8afb4bee4.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "order": 26
  },
  {
    "slug": "cst-microwave-studio",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1523050854058_8df90110c9f1_5d3933d7b4.png",
      "alt": "testing image",
      "width": 800,
      "height": 600
    },
    "order": 27
  },
  {
    "slug": "microelectronics-and-vlsi-circuit-design-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1541339907198_e08756dedf3f_6466a1a79a.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "order": 28
  },
  {
    "slug": "ai-driven-advanced-signal-processing-asp-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1519389950473_47ba0277781c_004043fca3.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "order": 29
  },
  {
    "slug": "control-system-and-automation-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1497366216548_37526070297c_cc9da0bc35.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 801
    },
    "order": 30
  },
  {
    "slug": "microprocessor-and-embedded-system-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1531482615713_2afd69097998_6b6c6f5768.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "order": 31
  },
  {
    "slug": "speech-and-image-processing-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1523240795612_9a054b0db644_4024e78648.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "order": 32
  },
  {
    "slug": "electronic-design-automation-eda-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1524178232363_1fb2b075b655_4844aedea4.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "order": 33
  },
  {
    "slug": "internet-of-things-iot-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1562774053_701939374585_d6c47bbbb9.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 786
    },
    "order": 34
  },
  {
    "slug": "printed-circuit-board-pcb-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1513258496099_48168024aec0_38d2e4fa8c.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "order": 35
  },
  {
    "slug": "intelligent-ev-systems-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1517486808906_6ca8b3f04846_4d025ae68f.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 1552
    },
    "order": 36
  },
  {
    "slug": "electrical-network-design-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1509062522246_3755977927d7_dd5c6e5f53.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 747
    },
    "order": 37
  },
  {
    "slug": "simu-machines-innovation-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1503676260728_1c00da094a0b_1593d6bdd5.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 847
    },
    "order": 38
  },
  {
    "slug": "vr-ar-development-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1571260899304_425eee4c7efc_5ce92f65fd.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "order": 39
  },
  {
    "slug": "cybersecurity-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1506905925346_21bda4d32df4_3e7d976a76.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "order": 40
  },
  {
    "slug": "data-science-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1522202176988_66273c2fd55f_e8afb4bee4.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "order": 41
  },
  {
    "slug": "blockchain-technology-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1523050854058_8df90110c9f1_5d3933d7b4.png",
      "alt": "testing image",
      "width": 800,
      "height": 600
    },
    "order": 42
  },
  {
    "slug": "ai-and-machine-learning-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1541339907198_e08756dedf3f_6466a1a79a.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "order": 43
  },
  {
    "slug": "cloud-computing-lab",
    "name": "testing testing",
    "objective": "testing testing",
    "school": null,
    "tags": [],
    "image": {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1519389950473_47ba0277781c_004043fca3.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 800
    },
    "order": 44
  }
];
