// Generated by the CU CMS. Do not edit.

import type { Leaders } from '../types/data/leaders';

export type { Leaders };

export const LEADERS: Leaders = [
  {
    "slug": "chancellor",
    "name": "Satnam Singh Sandhu",
    "role": "Chancellor, Chandigarh University",
    "photo": {
      "url": "http://127.0.0.1:1337/uploads/images_leadership_chancellor_e59d1a3176.webp",
      "alt": "",
      "width": 760,
      "height": 950
    },
    "message": [
      {
        "text": "We offer meticulously designed programs in emerging fields like Artificial Intelligence and Data Science equipping students with the skills and knowledge needed to thrive in the rapidly changing workforce ecosystem. Sustainability is at the core of our values, and our campus boasts energy-efficient infrastructure, ensuring a sustainable environment for generations to come in line with the sustainable development goals of the United Nations."
      },
      {
        "text": "Through strategic partnerships with prestigious international institutions and industry leaders, we aim to provide our students with unparalleled opportunities for global exposure and industry insights, enriching their academic journey and broadening their perspectives."
      },
      {
        "text": "We look forward to welcoming you to our campus and providing you with a plethora of opportunities to help you realise your career aspirations."
      }
    ],
    "showOnProgrammePages": true,
    "order": 1
  },
  {
    "slug": "pro-chancellor",
    "name": "Mrs. Damandeep Kaur Sandhu",
    "role": "Pro-Chancellor, Chandigarh University, UP",
    "photo": {
      "url": "http://127.0.0.1:1337/uploads/images_leadership_pro_chancellor_f54f890e33.webp",
      "alt": "",
      "width": 760,
      "height": 950
    },
    "message": [
      {
        "text": "Our approach to education is rooted in research and innovation, incorporating futuristic methods such as the integration of Artificial Intelligence within academics and on campus, as well as purposeful engagement."
      },
      {
        "text": "Every student who graduates from CU-UP will carry more than a degree. They will be equipped with the confidence to lead, make responsible choices, and contribute to a sustainable and inclusive world. Our strong foundation in research, innovation, and experiential learning ensures that we bridge the gap between theory and life, preparing our students for real-world challenges."
      },
      {
        "text": "At the heart of our vision lies the belief that education is incomplete without sustainability, inclusion, and social responsibility, which is why CU-UP stands as a symbol of nurturing minds that think differently, build creatively, and lead the future with confidence."
      },
      {
        "text": "It is my earnest aspiration that each graduate of Chandigarh University, Uttar Pradesh, leaves with knowledge, courage, integrity, and a vision to shape a brighter and more meaningful future."
      }
    ],
    "showOnProgrammePages": false,
    "order": 2
  },
  {
    "slug": "group-vice-chancellor",
    "name": "Prof. (Dr.) Vikas Rai Bhatnagar",
    "role": "Group Vice Chancellor, Chandigarh University",
    "photo": {
      "url": "http://127.0.0.1:1337/uploads/images_leadership_group_vice_chancellor_03e51bf1e9.webp",
      "alt": "",
      "width": 760,
      "height": 950
    },
    "message": [
      {
        "text": "I extend my warmest greetings to our students, parents, faculty, and all stakeholders who have reposed their trust in us. Together, we share a profound responsibility: shaping the careers of the next generation and, in doing so, actively contributing to the vital task of nation-building."
      },
      {
        "text": "Chandigarh University, Lucknow Campus is uniquely poised to conceptualize, design, and institute the 'next practices' in higher education. We firmly believe that a motivated, happy, and talented faculty is the cornerstone of a truly enriching learning experience. By cultivating a thoughtful management ecosystem, we empower our educators to design relevant curricula and innovative pedagogies. In this vibrant environment, learning becomes a deeply social process. Through peer-to-peer engagement, our students learn to challenge assumptions, absorb deep knowledge, and develop the practical skills necessary to thrive in their chosen careers."
      },
      {
        "text": "Our campus is unconditionally student-centric. To us, this means scientifically aligning the inherent strengths of our students with tailored learning experiences and future career choices. This precision-driven approach ensures that our learners are not just prepared for the job market, but are destined to lead it."
      },
      {
        "text": "Guided by an energetic and visionary leadership team, we proactively anticipate emerging educational trends to keep our curriculum well ahead of the curve. Our mission is to seamlessly integrate rapid technological advancements while ensuring our students firmly hone their humanistic values, empathy, and ethics."
      },
      {
        "text": "I welcome you all to a transformative journey of growth, innovation, and excellence at Chandigarh University, Lucknow Campus."
      }
    ],
    "showOnProgrammePages": false,
    "order": 3
  },
  {
    "slug": "vice-chancellor",
    "name": "Prof. (Dr.) Vinith Kumar Nair",
    "role": "Vice Chancellor, Chandigarh University, UP",
    "photo": {
      "url": "http://127.0.0.1:1337/uploads/images_leadership_vice_chancellor_59c9957f48.webp",
      "alt": "",
      "width": 760,
      "height": 950
    },
    "message": [
      {
        "text": "At Chandigarh University, Uttar Pradesh Campus, we are committed to delivering world-class education that empowers students to become future-ready professionals, innovators, and responsible global citizens. As a multidisciplinary institution, we combine academic excellence with experiential learning, research, innovation, and industry engagement to prepare our students for the opportunities of a rapidly evolving world."
      },
      {
        "text": "Our future-focused programmes are designed in collaboration with industry and delivered by accomplished faculty who bring together academic expertise and professional experience. By integrating Artificial Intelligence, advanced digital technologies, and interdisciplinary learning into our curriculum, we equip students with the knowledge, skills, and mindset needed to excel in emerging fields and dynamic career landscapes."
      },
      {
        "text": "Innovation and sustainability are central to our institutional philosophy. Through cutting-edge research, entrepreneurial initiatives, energy-efficient infrastructure, and practices aligned with the United Nations Sustainable Development Goals, we foster an environment that encourages creativity, responsibility, and meaningful societal impact. Our strong partnerships with leading industries, research organisations, and international universities provide students with valuable opportunities for global exposure, internships, collaborative research, and experiential learning, ensuring they graduate with both competence and confidence."
      },
      {
        "text": "At Chandigarh University, Uttar Pradesh Campus, we believe education extends beyond the classroom. We are dedicated to nurturing leadership, integrity, lifelong learning, and a spirit of innovation that enables every student to realize their full potential."
      },
      {
        "text": "We look forward to welcoming you to our vibrant academic community and partnering with you on a transformative journey towards excellence, innovation, and success."
      }
    ],
    "showOnProgrammePages": false,
    "order": 4
  },
  {
    "slug": "pro-vice-chancellor",
    "name": "Dr. Thipendra P. Singh",
    "role": "Pro Vice Chancellor, Chandigarh University UP",
    "photo": {
      "url": "http://127.0.0.1:1337/uploads/images_leadership_pro_vice_chancellor_51716189e6.webp",
      "alt": "",
      "width": 760,
      "height": 950
    },
    "message": [
      {
        "text": "Chandigarh University is not merely responding to the fourth industrial revolution — we are driving it."
      },
      {
        "text": "The 21st century demands a paradigm shift in how we perceive and deliver education. At the heart of our institutional philosophy is a bold and transformative vision — to create an AI-empowered learning ecosystem that is agile, personalized, ethical, and globally relevant. Our aim is not just to educate for today's jobs but to prepare future-ready individuals equipped with cognitive agility and emotional intelligence to thrive in unknown futures."
      },
      {
        "text": "We have embraced AI not as a technological add-on but as a core strategic enabler of our mission — to provide accessible, interdisciplinary, and human-centered education. Our Centre of Excellence in Artificial Intelligence is the heart of our commitment to technological leadership. This world-class facility is aimed to serve as a hub for research, innovation, and cross-disciplinary collaboration."
      },
      {
        "text": "What makes our university truly unique is how AI permeates our campus life. Our classrooms are no longer confined to four walls. With AI-enabled adaptive learning platforms, we offer personalized learning paths that adjust to each student's pace and style."
      },
      {
        "text": "In our journey toward global excellence, we have established robust international collaborations with leading universities, AI research labs, and innovation centers across the world. Our students benefit from exchange programs, virtual research internships, and dual-degree opportunities with institutions at the forefront of AI. Simultaneously, we maintain deep industry linkages through partnerships with AI leaders like Microsoft, Google, NVIDIA, IBM, and many more."
      },
      {
        "text": "Internships, hackathons, innovation challenges, and co-incubation platforms allow our students to move seamlessly from classroom to lab to startup. We do not see ourselves as an ivory tower but as a platform for transformation — where learning meets action and ideas meet impact."
      },
      {
        "text": "As Pro Vice Chancellor, I reaffirm our university's dedication to transformative education, research excellence, and ethical leadership in the age of AI. We are more than a university — we are a movement. And the future, powered by purpose and intelligence, begins here."
      }
    ],
    "showOnProgrammePages": false,
    "order": 5
  }
];
