// Generated by the CU CMS. Do not edit.

import type { Patents } from '../types/data/patents';

export type { Patents };

export const PATENTS: Patents = [
  {
    "title": "Artificial intelligence Based market forecasting devices",
    "inventors": "Dr Uma Shankar Yadav, Dr Ajay Kumar Yadav",
    "number": "438059-001",
    "status": "published",
    "year": null,
    "link": ""
  },
  {
    "title": "Artificial intelligence-powered system for social media data tracking",
    "inventors": "Chandigarh University Uttar Pradesh, Dr Uma Shankar Yadav, Dr Ajay Kumar Yadav, Dr Alok kumar, Dr Bhanu Pratap Singh",
    "number": "448887-001",
    "status": "published",
    "year": null,
    "link": ""
  },
  {
    "title": "Smart AI whiteboard for Teaching",
    "inventors": "Chandigarh University Uttar Pradesh, Dr Om Prakash Dwivedi, Dr Ajay Kumar Yadav, Dr Shyam Sumanta Das, Dr Pardhi Joshi, Dr Dileep Kumar, Dr Anand Kumar Mihsra",
    "number": "452558-001",
    "status": "published",
    "year": null,
    "link": ""
  },
  {
    "title": "AI powered cyber security thread detection system for IOT Devices",
    "inventors": "Dr Atul Kumar",
    "number": "6431651",
    "status": "published",
    "year": null,
    "link": ""
  },
  {
    "title": "Health care monitoring devices",
    "inventors": "Chandigarh University Uttar Pradesh, Dr Atul kumar, Dr Uma shankar yadav, Dr Ashutosh Bajpai, Dr Bhanupratap singh, Dr Amit Kumar Mishra, Dr Shushil Kumar Mishra, Mr Shasank Srivastava",
    "number": "6457576",
    "status": "published",
    "year": null,
    "link": ""
  },
  {
    "title": "Artifial intelligence based agile project management kiosk",
    "inventors": "Dr Aswani kumar gupta",
    "number": "426868-001",
    "status": "published",
    "year": null,
    "link": ""
  },
  {
    "title": "Predictive analytics based options trading processing apparatusd",
    "inventors": "Chandigarh University Uttar Pradesh, Dr Alka Singh , Dr Uma Shankar Yadav, Dr Ajay Kumar Yadav",
    "number": "450222-001",
    "status": "published",
    "year": null,
    "link": ""
  },
  {
    "title": "artificial intellegence based device for promotion, survey and marketing of handicraft products",
    "inventors": "Chandigarh University Uttar Pradesh, Dr Uma Shankar Yadav, Dr. Alok Kumar, Dr. Amit Khare, Dr Ajay Kumar Yadav, Dr Ashutosh Bajpai, Dr Amit Kishore",
    "number": "462420-001",
    "status": "filed",
    "year": null,
    "link": ""
  },
  {
    "title": "Artificial intelligence-based device media communication",
    "inventors": "Chandigarh University Uttar Pradesh, Dr Uma shankar yadav, Dr Alok Kumar, Dr. Amit khare, Dr Ajay Kumar Yadav, Dr Ashutosh Bajpai, Dr Amit Kishore",
    "number": "462424-001",
    "status": "filed",
    "year": null,
    "link": ""
  },
  {
    "title": "Artificial intellignce based leagle language converter devices",
    "inventors": "Chandigarh University Uttar Pradesh, Dr uma shankar yadav, Dr Abhishek Singh, Dr Manoj Singh, Mr Raunak Tiwari, Mr Lakashy Saini, Dr Ashutosh Bajpai",
    "number": "458716-001",
    "status": "filed",
    "year": null,
    "link": ""
  },
  {
    "title": "artificial intelligence based tablet for recruitement Process",
    "inventors": "Dr Uma shankar yadav",
    "number": "462465-001",
    "status": "filed",
    "year": null,
    "link": ""
  },
  {
    "title": "I-INTEGRATED ASSISTANT DEVICE FOR BUSINESS MANAGEMENT",
    "inventors": "Dr Shraddha Verma, Dr Kahksha Safi",
    "number": "459564-001",
    "status": "published",
    "year": null,
    "link": ""
  },
  {
    "title": "Laboratory Apparatus for Functional Molecule Engineering and Predictive Biological Modelling",
    "inventors": "Chandigarh University Uttar Pradesh, Dr. Sameeta Sahoo ,Dr. Ajay Kumar Yadav, Dr. Shyam S. Das, Dr. Sapna Baluni",
    "number": "468075-001",
    "status": "filed",
    "year": null,
    "link": ""
  },
  {
    "title": "Device for Targeted Gene Editing",
    "inventors": "Chandigarh University Uttar Pradesh, Dr. Gurminder Kaur, Dr. Raghvendra Tiwari, Harshit Kumar Sharma",
    "number": "465661-001",
    "status": "filed",
    "year": null,
    "link": ""
  },
  {
    "title": "MXene-Embedded Filtration System for Pollutant Removal from Water",
    "inventors": "Chandigarh University Uttar Pradesh, Dr. Pradeep Kumar Pandey, Dr. Subhendu Chakroborty",
    "number": "465659-001",
    "status": "filed",
    "year": null,
    "link": ""
  },
  {
    "title": "Targeted Nanoparticle- Based Medical Therapy Device",
    "inventors": "Dr. Subhendu Chakroborty, Dr. Sameeta Sahoo, Dr. Pradeep Kumar Pandey, Dr. Shyam S. Das",
    "number": "450756-001",
    "status": "published",
    "year": null,
    "link": ""
  },
  {
    "title": "A METHOD FOR PRODUCING A FOOD SUPPLEMENT FROM MICROALGAE FOR ELDERLY AND ICU PATIENTS",
    "inventors": "Dr. Pritikrishna Majhi, Dr. Subhendu Chakroborty, Prof. (Dr) Ajay Kumar Yadav",
    "number": "202431049820",
    "status": "filed",
    "year": null,
    "link": ""
  },
  {
    "title": "AI Based Craime Detection Device In cyber security",
    "inventors": "Dr Atul kumar",
    "number": "456799-001",
    "status": "published",
    "year": null,
    "link": ""
  }
];
