// Generated by the CU CMS. Do not edit.

import type { Publications } from '../types/data/publications';

export type { Publications };

export const PUBLICATIONS: Publications = [
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": ""
  },
  {
    "title": "testing testing",
    "authors": "",
    "venue": "testing testing",
    "year": 1900,
    "doi": "",
    "link": "",
    "quartile": "testing testing"
  }
];
