// Generated by the CU CMS. Do not edit.

import type { Publications } from '../types/data/publications';

export type { Publications };

export const PUBLICATIONS: Publications = [
  {
    "title": "Nitrogen dioxide gas sensing using surface plasmon resonance sensor",
    "authors": "",
    "venue": "Modern Physics Letters B",
    "year": 2025,
    "doi": "",
    "link": "",
    "quartile": "Q3"
  },
  {
    "title": "Enhanced SqueezeNet model for detecting IoT-Bot attacks: A comprehensive approach",
    "authors": "",
    "venue": "MethodsX",
    "year": 2025,
    "doi": "",
    "link": "",
    "quartile": "Q2"
  },
  {
    "title": "Engineering poloxamer copolymers for in situ gelling systems: Structural, compositional, and functional modifications",
    "authors": "",
    "venue": "European Polymer Journal",
    "year": 2025,
    "doi": "",
    "link": "",
    "quartile": "Q1"
  },
  {
    "title": "Optimized dielectric-plasmonic interfaces for long-range surface plasmon resonance sensors",
    "authors": "",
    "venue": "Journal of Computational Electronics",
    "year": 2025,
    "doi": "",
    "link": "",
    "quartile": "Q3"
  },
  {
    "title": "Role of crystal orientations and loading conditions on the microstructure evolution and void evolution dynamics in single crystal iron: An atomistic investigation",
    "authors": "",
    "venue": "Mechanics of Materials",
    "year": 2025,
    "doi": "",
    "link": "",
    "quartile": "Q1"
  },
  {
    "title": "Gender Inequality and Human Development in India: An Empirical Analysis",
    "authors": "",
    "venue": "Sexuality, Gender and Policy",
    "year": 2025,
    "doi": "",
    "link": "",
    "quartile": "Q1"
  },
  {
    "title": "An Investigation on the Effect of Mango Seed and Pongamia Oil-Based Cutting Fluids on Surface Morphology During Turning of AISI 304 Steel",
    "authors": "",
    "venue": "Lubricants",
    "year": 2025,
    "doi": "",
    "link": "",
    "quartile": "Q2"
  },
  {
    "title": "Theoretical investigation on the adsorption behaviour of tyramine neurotransmitter onto B12N12 nanocage",
    "authors": "",
    "venue": "Diamond and Related Materials",
    "year": 2025,
    "doi": "",
    "link": "",
    "quartile": "Q1"
  },
  {
    "title": "Performance-Emission Optimization of a Diesel Engine Blended With Biodiesel and Pentanol",
    "authors": "",
    "venue": "Energy Science and Engineering",
    "year": 2025,
    "doi": "",
    "link": "",
    "quartile": "Q1"
  },
  {
    "title": "Analyzing the Factors of Business Digitalization and Their Impact on the Entrepreneurial Growth of the Handmade Toy Industry",
    "authors": "",
    "venue": "Electronic journal of electronic system in developmening countries",
    "year": 2025,
    "doi": "",
    "link": "",
    "quartile": "Q2"
  },
  {
    "title": "MXene-enhanced CO₂ sensors: a comprehensive review on mechanisms, challenges, and environmental impact",
    "authors": "",
    "venue": "Discover Applied Sciences",
    "year": 2025,
    "doi": "",
    "link": "",
    "quartile": "Q1"
  },
  {
    "title": "Microbial interventions for abiotic and biotic stress management in plants-A brief review",
    "authors": "",
    "venue": "Journal of Biological Control",
    "year": 2025,
    "doi": "",
    "link": "",
    "quartile": "Q4"
  },
  {
    "title": "A review of emerging trends in nanomaterial-driven AI for biomedical applications",
    "authors": "",
    "venue": "RSC Nanoscale Advances",
    "year": 2025,
    "doi": "",
    "link": "",
    "quartile": "Q1"
  },
  {
    "title": "Enhancement of dielectric and electrical properties of polyvinyl alcohol-NaNbO3-copper nanoparticle composite films",
    "authors": "",
    "venue": "Journal of Molecular Liquids",
    "year": 2025,
    "doi": "",
    "link": "",
    "quartile": "Q1"
  },
  {
    "title": "Drug release potential of polyacrylamide grafted-Assam Bora rice polysaccharide graft copolymer (ABRS-g-PAM) as effective controlled release polymer",
    "authors": "",
    "venue": "Carbohydrate Research",
    "year": 2025,
    "doi": "",
    "link": "",
    "quartile": "Q2"
  },
  {
    "title": "Nanoarchitectonics Application and Research Progress in Cancer Treatment",
    "authors": "",
    "venue": "BioNanoScience",
    "year": 2025,
    "doi": "",
    "link": "",
    "quartile": "Q2"
  },
  {
    "title": "Impact of strain and electron–phonon coupling on thermoelectric performance of Germanene",
    "authors": "",
    "venue": "Physica E: Low-Dimensional Systems and Nanostructures",
    "year": 2025,
    "doi": "",
    "link": "",
    "quartile": "Q1"
  },
  {
    "title": "Highly Green Fluorescent Carbon Dots from Gallic Acid: A Turn-On Sensor toward Pb2+ Ions",
    "authors": "",
    "venue": "ACS Omega",
    "year": 2025,
    "doi": "",
    "link": "",
    "quartile": "Q1"
  },
  {
    "title": "Rules to identify and track the evolution dynamics of {101̄2} twin variants in hexagonal close-packed metals",
    "authors": "",
    "venue": "Mechanics of Materials",
    "year": 2025,
    "doi": "",
    "link": "",
    "quartile": "Q1"
  },
  {
    "title": "Impact of Entrepreneurial Leadership, Talent Management, Social Media, Artificial Intelligence and Digital Technology on Business Performance in Handicraft Industry: An Analysis of Innovation as Moderating Construct",
    "authors": "",
    "venue": "FIIB Business Review",
    "year": 2025,
    "doi": "",
    "link": "",
    "quartile": "Q1"
  },
  {
    "title": "A Real-Time Object Detection System with Audio Feedback for Visually Impaired Persons",
    "authors": "",
    "venue": "2025 International Conference on Intelligent Control, Computing and Communications, IC3 2025",
    "year": 2025,
    "doi": "",
    "link": "",
    "quartile": "Conference Paper"
  },
  {
    "title": "SwinTrans Classifiers - A Framework for Multi-leaf and Multi-disease Classification and Detection in Computer Vision",
    "authors": "",
    "venue": "Journal of Agricultural, Biological, and Environmental Statistics",
    "year": 2025,
    "doi": "",
    "link": "",
    "quartile": "Q2"
  },
  {
    "title": "Optimising Lead-Free Cs2BiAgI6 Perovskite Solar Cells for enhanced performance and stability",
    "authors": "",
    "venue": "Journal of Integrated Science and Technology",
    "year": 2025,
    "doi": "",
    "link": "",
    "quartile": "Q1"
  },
  {
    "title": "Deep Learning-based Optimized Model for Emotional Psychological Disorder Activities Identification in Smart Healthcare System",
    "authors": "",
    "venue": "Journal of Research, Innovation and Technologies",
    "year": 2025,
    "doi": "",
    "link": "",
    "quartile": "Q4"
  },
  {
    "title": "Unraveling India's cultural diplomacy with Fiji: a decade of engagement (2014 &minus; 2025)",
    "authors": "",
    "venue": "Cogent Social Sciences",
    "year": 2025,
    "doi": "",
    "link": "",
    "quartile": "Q2"
  },
  {
    "title": "Application of response surface methodology on performance and emission characteristics of a diesel engine fueled with diesel, pentanol, and biogas",
    "authors": "",
    "venue": "Environmental Science and Pollution Research",
    "year": 2025,
    "doi": "",
    "link": "",
    "quartile": "Q1"
  },
  {
    "title": "Prevalence of Noise-Induced Hearing Loss among Truck Drivers: A Cross-Sectional Study in Lucknow",
    "authors": "",
    "venue": "Noise and Health",
    "year": 2025,
    "doi": "",
    "link": "",
    "quartile": "Q3"
  },
  {
    "title": "Formation of a nitrobenzoxadiazole-based yellow fluorophore for the selective spectrofluorimetric determination of the antifungal drug pimaricin in ophthalmic pharmaceutical formulations",
    "authors": "",
    "venue": "Spectroscopy Letters",
    "year": 2025,
    "doi": "",
    "link": "",
    "quartile": "Q3"
  },
  {
    "title": "Plasmonic Sensing of Human Teeth: A Molybdenum Ditelluride-Black Phosphorus-Based Surface Plasmon Resonance Approach",
    "authors": "",
    "venue": "Plasmonics",
    "year": 2025,
    "doi": "",
    "link": "",
    "quartile": "Q1"
  },
  {
    "title": "Multivariate Lifetime Prediction Model for Energy Efficient Region-Based Wireless Sensor Network",
    "authors": "",
    "venue": "IET Wireless Sensor Systems",
    "year": 2025,
    "doi": "",
    "link": "",
    "quartile": "Q2"
  },
  {
    "title": "A Novel Methodology to Predict Flood and Landslide Disasters using Learning Assisted Artificial Intelligence (AI) Logic",
    "authors": "",
    "venue": "conference proceeding",
    "year": 2025,
    "doi": "",
    "link": "",
    "quartile": "Conference Paper"
  },
  {
    "title": "One-pot synthesis of waste poly (vinyl-chloride) derived carbon dots for antimicrobial applications",
    "authors": "",
    "venue": "Journal of Molecular Liquids",
    "year": 2025,
    "doi": "",
    "link": "",
    "quartile": "Q1"
  },
  {
    "title": "Design of a Silicon and Tantalum Diselenide-Based Multilayer Surface Plasmon Resonance Sensor for Early Detection of Skin Cancer",
    "authors": "",
    "venue": "Plasmonics",
    "year": 2025,
    "doi": "",
    "link": "",
    "quartile": "Q3"
  },
  {
    "title": "Workplace spirituality empowered by spiritual leadership to promote organizational effectiveness: A bibliometric analysis",
    "authors": "",
    "venue": "Purushartha",
    "year": 2024,
    "doi": "",
    "link": "",
    "quartile": "Q2"
  },
  {
    "title": "An Operative Expectation of Parkinson's Ailment Using a Hybrid Machine Learning and Artificial Intelligence Systems",
    "authors": "",
    "venue": "SN Computer Science",
    "year": 2024,
    "doi": "",
    "link": "",
    "quartile": "Q2"
  },
  {
    "title": "Bio-based fabrication of palladium nanoparticles by using Aegle marmelos leaf extract for biomedical applications: Cytotoxicity, cell imaging studies in HeLa cells and antioxidant activity",
    "authors": "",
    "venue": "Inorganic Chemistry Communications",
    "year": 2024,
    "doi": "",
    "link": "",
    "quartile": "Q1"
  },
  {
    "title": "Impact of entrepreneurial leadership, Social media, digital technology, Entrepreneurial orientation and innovation on business performance in the handicraft sector: Talent management as mediating construct",
    "authors": "",
    "venue": "Journal of Innovation and Entrepreneurship",
    "year": 2024,
    "doi": "",
    "link": "",
    "quartile": "Q1"
  },
  {
    "title": "Impact of entrepreneurial orientation and ESG on environmental performance: moderating impact of digital transformation and technological innovation as a mediating construct using Sobel test",
    "authors": "",
    "venue": "Journal of Innovation and Entrepreneurship",
    "year": 2024,
    "doi": "",
    "link": "",
    "quartile": "Q1"
  },
  {
    "title": "Investigating CuO-ZrO2 Mixed Metal Oxide Nanocomposites for Electrochemical Sensing of Food Colors",
    "authors": "",
    "venue": "Luminescence",
    "year": 2024,
    "doi": "",
    "link": "",
    "quartile": "Q2"
  },
  {
    "title": "Empowering NGOs with Remote Sensing and CNN-LSTM Models for Social and Environmental Transformation",
    "authors": "",
    "venue": "Remote Sensing in Earth Systems Sciences",
    "year": 2024,
    "doi": "",
    "link": "",
    "quartile": "Q2"
  },
  {
    "title": "Synthesis, Biological Evaluation and Molecular Modeling Studies of Novel Tribromo-substituted Imidazole Analogs",
    "authors": "",
    "venue": "Journal of Molecular Liquids",
    "year": 2024,
    "doi": "",
    "link": "",
    "quartile": "Q1"
  },
  {
    "title": "Silver nanoparticle for biomedical applications: A review",
    "authors": "",
    "venue": "Hybrid Advances",
    "year": 2024,
    "doi": "",
    "link": "",
    "quartile": "Q2"
  },
  {
    "title": "Evaluation of microwave irradiated Polyacrylamide grafted Opuntia leaf mucilage graft copolymer (OPM-g-PAM) as effective controlled release polymer for release of Rosuvastastin as model drug",
    "authors": "",
    "venue": "International Journal of Biological Macromolecules",
    "year": 2024,
    "doi": "",
    "link": "",
    "quartile": "Q1"
  },
  {
    "title": "Impact of Corporate Innovation, Technological Innovation and ESG on Environmental Performance: Moderation Test of Entrepreneurial Orientation and Technological Innovation as Mediator Using Sobel Test",
    "authors": "",
    "venue": "International Journal of Sustainable Development and Planning",
    "year": 2024,
    "doi": "",
    "link": "",
    "quartile": "Q3"
  },
  {
    "title": "Structural, electrical, optical and magnetic properties of Bi2-xLaxFeCrO6 (x = 0.4, 0.6) double perovskites for device applications",
    "authors": "",
    "venue": "Journal of the Korean Ceramic Society",
    "year": 2024,
    "doi": "",
    "link": "",
    "quartile": "Q2"
  },
  {
    "title": "Stimuli-responsive nanogels: A smart material for biomedical applications",
    "authors": "",
    "venue": "Journal of Molecular Liquids",
    "year": 2024,
    "doi": "",
    "link": "",
    "quartile": "Q1"
  },
  {
    "title": "stimulation of Single-Point Cutting Tool for Prediction of Wear and Temperature in Turning Operation",
    "authors": "",
    "venue": "Lecture Notes in Mechanical Engineering",
    "year": 2024,
    "doi": "",
    "link": "",
    "quartile": "Q4/Conference Paper"
  },
  {
    "title": "Detecting Paddy Leaf Diseases Using MobileNetV2 and Machine Learning Techniques",
    "authors": "",
    "venue": "Proceedings - 2024 International Conference on Progressive Innovations in Intelligent Systems and Data Science, ICPIDS 2024",
    "year": 2024,
    "doi": "",
    "link": "",
    "quartile": "Conference Paper"
  },
  {
    "title": "Revolutionizing B2B E-Commerce: A Legal Study on the Transformative Impact of Hybrid AI Integration",
    "authors": "",
    "venue": "Proceedings of the 4th International Conference on Ubiquitous Computing and Intelligent Information Systems, ICUIS",
    "year": 2024,
    "doi": "",
    "link": "",
    "quartile": "Conference Paper"
  },
  {
    "title": "Explainable Machine Learning: A brief survey on history, research areas, approaches and challenges",
    "authors": "",
    "venue": "2024 International Conference on Augmented Reality, Intelligent Systems, and Industrial Automation, ARIIA",
    "year": 2024,
    "doi": "",
    "link": "",
    "quartile": "Conference Paper"
  }
];
