// Generated by the CU CMS. Do not edit.

import type { ResearchCentres } from '../types/data/research-centres';

export type { ResearchCentres };

export const RESEARCH_CENTRES: ResearchCentres = [
  {
    "slug": "cradle",
    "name": "Centre for Research and AI Development Learning Ecosystem",
    "acronym": "CRADLE",
    "lede": "The CRADLE Cell at Chandigarh University, Uttar Pradesh, is dedicated to encouraging research through artificial intelligence and building partnerships around the world for technological transformation and societal betterment.",
    "focusAreas": [],
    "image": null,
    "order": 1
  },
  {
    "slug": "caira",
    "name": "Centre for Artificial Intelligence Research and Applications",
    "acronym": "CAIRA",
    "lede": "Artificial intelligence (AI) is poised to revolutionise every industry and aspect of human life. Chandigarh University, Uttar Pradesh, has established the Centre for Artificial Intelligence Research and Applications (CAIRA) to foster the responsible development of AI. As a first-of-its-kind initiative among regional universities, CAIRA focuses on advancing interdisciplinary AI research across scientific, technological, societal, business, and educational fields. The Centre aims to lead AI innovation and develop real-world solutions that address contemporary challenges.",
    "focusAreas": [],
    "image": null,
    "order": 2
  }
];
