// Generated by the CU CMS. Do not edit.

import type { Schools } from '../types/data/schools';

export type { Schools };

export const SCHOOLS: Schools = [
  {
    "discipline": "applied-health-sciences",
    "name": "Applied Health Sciences",
    "tagline": "Unravel Mysteries: Explore Our Applied Sciences Programs!",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/images_our_programes_assets_new_LMS_304_d5cfb5cf68.webp",
      "alt": "",
      "width": 1200,
      "height": 667
    },
    "teachingIntro": "At Chandigarh University, we believe in the power of a unified yet distinct educational journey, seamlessly extending from our faculty philosophy down to the individual schools within each faculty. Our commitment is to ensure that the pedagogical approaches at the school level not only resonate with the overarching goals of the faculty but are also meticulously adapted to meet the unique demands and aspirations of each school's discipline.\n\nBy aligning the educational strategies across schools and faculties, we not only ensure a coherent educational philosophy but also enrich the learning journey by facilitating cross-disciplinary insights and opportunities. This approach allows students to benefit from a broad-based education while gaining deep expertise in their chosen fields.",
    "teachingPractices": [],
    "evaluationIntro": "At Chandigarh University, we believe that assessment is a crucial part of the learning process — not just a measure of what you've learned, but a way to enhance your educational journey and prepare you for the challenges of the real world. Our innovative assessment practices are designed to align with our commitment to personalized learning, ensuring that every student can thrive and reach their full potential.\n\nThrough a variety of engaging, practical, and reflective assessment methods, we aim to equip our students with the skills, knowledge, and mindset needed for success in their chosen fields.",
    "evaluationPractices": [],
    "teachesAiCompetencies": false,
    "order": 1
  },
  {
    "discipline": "architecture-and-planning",
    "name": "Architecture and Planning",
    "tagline": "Build a Future of Design Excellence",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/images_our_programes_assets_new_LAR_201_d941717776.webp",
      "alt": "",
      "width": 2000,
      "height": 1000
    },
    "teachingIntro": "At Chandigarh University, we believe in the power of a unified yet distinct educational journey, seamlessly extending from our faculty philosophy down to the individual schools within each faculty. Our commitment is to ensure that the pedagogical approaches at the school level not only resonate with the overarching goals of the faculty but are also meticulously adapted to meet the unique demands and aspirations of each school's discipline.\n\nBy aligning the educational strategies across schools and faculties, we not only ensure a coherent educational philosophy but also enrich the learning journey by facilitating cross-disciplinary insights and opportunities. This approach allows students to benefit from a broad-based education while gaining deep expertise in their chosen fields.",
    "teachingPractices": [],
    "evaluationIntro": "At Chandigarh University, we believe that assessment is a crucial part of the learning process — not just a measure of what you've learned, but a way to enhance your educational journey and prepare you for the challenges of the real world. Our innovative assessment practices are designed to align with our commitment to personalized learning, ensuring that every student can thrive and reach their full potential.\n\nThrough a variety of engaging, practical, and reflective assessment methods, we aim to equip our students with the skills, knowledge, and mindset needed for success in their chosen fields.",
    "evaluationPractices": [],
    "teachesAiCompetencies": false,
    "order": 2
  },
  {
    "discipline": "biotechnology",
    "name": "Biotechnology",
    "tagline": "3 programmes in Biotechnology, across undergraduate and postgraduate study.",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/images_our_programes_assets_new_LMS_305_27d01b032a.webp",
      "alt": "",
      "width": 1200,
      "height": 667
    },
    "teachingIntro": "At Chandigarh University, we believe in the power of a unified yet distinct educational journey, seamlessly extending from our faculty philosophy down to the individual schools within each faculty. Our commitment is to ensure that the pedagogical approaches at the school level not only resonate with the overarching goals of the faculty but are also meticulously adapted to meet the unique demands and aspirations of each school's discipline.\n\nBy aligning the educational strategies across schools and faculties, we not only ensure a coherent educational philosophy but also enrich the learning journey by facilitating cross-disciplinary insights and opportunities. This approach allows students to benefit from a broad-based education while gaining deep expertise in their chosen fields.",
    "teachingPractices": [],
    "evaluationIntro": "At Chandigarh University, we believe that assessment is a crucial part of the learning process — not just a measure of what you've learned, but a way to enhance your educational journey and prepare you for the challenges of the real world. Our innovative assessment practices are designed to align with our commitment to personalized learning, ensuring that every student can thrive and reach their full potential.\n\nThrough a variety of engaging, practical, and reflective assessment methods, we aim to equip our students with the skills, knowledge, and mindset needed for success in their chosen fields.",
    "evaluationPractices": [],
    "teachesAiCompetencies": false,
    "order": 3
  },
  {
    "discipline": "business",
    "name": "Business",
    "tagline": "Strategize, Lead, Succeed; Explore Our Management Programs!",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/images_our_programes_assets_new_LMB_301_b902279bce.webp",
      "alt": "",
      "width": 1200,
      "height": 667
    },
    "teachingIntro": "At Chandigarh University, we believe in the power of a unified yet distinct educational journey, seamlessly extending from our faculty philosophy down to the individual schools within each faculty. Our commitment is to ensure that the pedagogical approaches at the school level not only resonate with the overarching goals of the faculty but are also meticulously adapted to meet the unique demands and aspirations of each school's discipline.\n\nBy aligning the educational strategies across schools and faculties, we not only ensure a coherent educational philosophy but also enrich the learning journey by facilitating cross-disciplinary insights and opportunities. This approach allows students to benefit from a broad-based education while gaining deep expertise in their chosen fields.",
    "teachingPractices": [],
    "evaluationIntro": "At Chandigarh University, we believe that assessment is a crucial part of the learning process — not just a measure of what you've learned, but a way to enhance your educational journey and prepare you for the challenges of the real world. Our innovative assessment practices are designed to align with our commitment to personalized learning, ensuring that every student can thrive and reach their full potential.\n\nThrough a variety of engaging, practical, and reflective assessment methods, we aim to equip our students with the skills, knowledge, and mindset needed for success in their chosen fields.",
    "evaluationPractices": [],
    "teachesAiCompetencies": false,
    "order": 4
  },
  {
    "discipline": "commerce",
    "name": "Commerce",
    "tagline": "Unlock Business Acumen. Choose Our Commerce Programs",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/images_our_programes_assets_new_LCO_701_7623d3233e.webp",
      "alt": "",
      "width": 1200,
      "height": 667
    },
    "teachingIntro": "At Chandigarh University, we believe in the power of a unified yet distinct educational journey, seamlessly extending from our faculty philosophy down to the individual schools within each faculty. Our commitment is to ensure that the pedagogical approaches at the school level not only resonate with the overarching goals of the faculty but are also meticulously adapted to meet the unique demands and aspirations of each school's discipline.\n\nBy aligning the educational strategies across schools and faculties, we not only ensure a coherent educational philosophy but also enrich the learning journey by facilitating cross-disciplinary insights and opportunities. This approach allows students to benefit from a broad-based education while gaining deep expertise in their chosen fields.",
    "teachingPractices": [],
    "evaluationIntro": "At Chandigarh University, we believe that assessment is a crucial part of the learning process — not just a measure of what you've learned, but a way to enhance your educational journey and prepare you for the challenges of the real world. Our innovative assessment practices are designed to align with our commitment to personalized learning, ensuring that every student can thrive and reach their full potential.\n\nThrough a variety of engaging, practical, and reflective assessment methods, we aim to equip our students with the skills, knowledge, and mindset needed for success in their chosen fields.",
    "evaluationPractices": [],
    "teachesAiCompetencies": false,
    "order": 5
  },
  {
    "discipline": "computing",
    "name": "Computing",
    "tagline": "Code Your Dreams: Explore Our Computing Programs!",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/images_our_programes_assets_new_LMC_301_5032c18406.webp",
      "alt": "",
      "width": 1200,
      "height": 667
    },
    "teachingIntro": "At Chandigarh University, we believe in the power of a unified yet distinct educational journey, seamlessly extending from our faculty philosophy down to the individual schools within each faculty. Our commitment is to ensure that the pedagogical approaches at the school level not only resonate with the overarching goals of the faculty but are also meticulously adapted to meet the unique demands and aspirations of each school's discipline.\n\nBy aligning the educational strategies across schools and faculties, we not only ensure a coherent educational philosophy but also enrich the learning journey by facilitating cross-disciplinary insights and opportunities. This approach allows students to benefit from a broad-based education while gaining deep expertise in their chosen fields.",
    "teachingPractices": [],
    "evaluationIntro": "At Chandigarh University, we believe that assessment is a crucial part of the learning process — not just a measure of what you've learned, but a way to enhance your educational journey and prepare you for the challenges of the real world. Our innovative assessment practices are designed to align with our commitment to personalized learning, ensuring that every student can thrive and reach their full potential.\n\nThrough a variety of engaging, practical, and reflective assessment methods, we aim to equip our students with the skills, knowledge, and mindset needed for success in their chosen fields.",
    "evaluationPractices": [],
    "teachesAiCompetencies": false,
    "order": 6
  },
  {
    "discipline": "design",
    "name": "Design",
    "tagline": "Unleash Creativity with Advanced & Industry-Aligned Design Programs",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/images_our_programes_assets_new_LDE_701_339d994012.webp",
      "alt": "",
      "width": 2000,
      "height": 1000
    },
    "teachingIntro": "At Chandigarh University, we believe in the power of a unified yet distinct educational journey, seamlessly extending from our faculty philosophy down to the individual schools within each faculty. Our commitment is to ensure that the pedagogical approaches at the school level not only resonate with the overarching goals of the faculty but are also meticulously adapted to meet the unique demands and aspirations of each school's discipline.\n\nBy aligning the educational strategies across schools and faculties, we not only ensure a coherent educational philosophy but also enrich the learning journey by facilitating cross-disciplinary insights and opportunities. This approach allows students to benefit from a broad-based education while gaining deep expertise in their chosen fields.",
    "teachingPractices": [],
    "evaluationIntro": "At Chandigarh University, we believe that assessment is a crucial part of the learning process — not just a measure of what you've learned, but a way to enhance your educational journey and prepare you for the challenges of the real world. Our innovative assessment practices are designed to align with our commitment to personalized learning, ensuring that every student can thrive and reach their full potential.\n\nThrough a variety of engaging, practical, and reflective assessment methods, we aim to equip our students with the skills, knowledge, and mindset needed for success in their chosen fields.",
    "evaluationPractices": [],
    "teachesAiCompetencies": false,
    "order": 7
  },
  {
    "discipline": "engineering",
    "name": "Engineering",
    "tagline": "Lead the Way in Engineering. Innovate Your Future",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/images_our_programes_assets_new_LCS_301_9e30f96813.webp",
      "alt": "",
      "width": 1200,
      "height": 667
    },
    "teachingIntro": "At Chandigarh University, we believe in the power of a unified yet distinct educational journey, seamlessly extending from our faculty philosophy down to the individual schools within each faculty. Our commitment is to ensure that the pedagogical approaches at the school level not only resonate with the overarching goals of the faculty but are also meticulously adapted to meet the unique demands and aspirations of each school's discipline.\n\nBy aligning the educational strategies across schools and faculties, we not only ensure a coherent educational philosophy but also enrich the learning journey by facilitating cross-disciplinary insights and opportunities. This approach allows students to benefit from a broad-based education while gaining deep expertise in their chosen fields.",
    "teachingPractices": [],
    "evaluationIntro": "At Chandigarh University, we believe that assessment is a crucial part of the learning process — not just a measure of what you've learned, but a way to enhance your educational journey and prepare you for the challenges of the real world. Our innovative assessment practices are designed to align with our commitment to personalized learning, ensuring that every student can thrive and reach their full potential.\n\nThrough a variety of engaging, practical, and reflective assessment methods, we aim to equip our students with the skills, knowledge, and mindset needed for success in their chosen fields.",
    "evaluationPractices": [],
    "teachesAiCompetencies": false,
    "order": 8
  },
  {
    "discipline": "hotel-management-and-tourism",
    "name": "Hotel Management and Tourism",
    "tagline": "Crafting Leaders for Global Hospitality Excellence",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/images_our_programes_assets_new_LHM_701_6d7b293b28.webp",
      "alt": "",
      "width": 2000,
      "height": 1000
    },
    "teachingIntro": "At Chandigarh University, we believe in the power of a unified yet distinct educational journey, seamlessly extending from our faculty philosophy down to the individual schools within each faculty. Our commitment is to ensure that the pedagogical approaches at the school level not only resonate with the overarching goals of the faculty but are also meticulously adapted to meet the unique demands and aspirations of each school's discipline.\n\nBy aligning the educational strategies across schools and faculties, we not only ensure a coherent educational philosophy but also enrich the learning journey by facilitating cross-disciplinary insights and opportunities. This approach allows students to benefit from a broad-based education while gaining deep expertise in their chosen fields.",
    "teachingPractices": [],
    "evaluationIntro": "At Chandigarh University, we believe that assessment is a crucial part of the learning process — not just a measure of what you've learned, but a way to enhance your educational journey and prepare you for the challenges of the real world. Our innovative assessment practices are designed to align with our commitment to personalized learning, ensuring that every student can thrive and reach their full potential.\n\nThrough a variety of engaging, practical, and reflective assessment methods, we aim to equip our students with the skills, knowledge, and mindset needed for success in their chosen fields.",
    "evaluationPractices": [],
    "teachesAiCompetencies": false,
    "order": 9
  },
  {
    "discipline": "journalism-and-mass-communication",
    "name": "Journalism and Mass Communication",
    "tagline": "1 programme in Journalism and Mass Communication, at undergraduate level.",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/images_our_programes_assets_new_LBA_703_52dd862c89.webp",
      "alt": "",
      "width": 1200,
      "height": 667
    },
    "teachingIntro": "At Chandigarh University, we believe in the power of a unified yet distinct educational journey, seamlessly extending from our faculty philosophy down to the individual schools within each faculty. Our commitment is to ensure that the pedagogical approaches at the school level not only resonate with the overarching goals of the faculty but are also meticulously adapted to meet the unique demands and aspirations of each school's discipline.\n\nBy aligning the educational strategies across schools and faculties, we not only ensure a coherent educational philosophy but also enrich the learning journey by facilitating cross-disciplinary insights and opportunities. This approach allows students to benefit from a broad-based education while gaining deep expertise in their chosen fields.",
    "teachingPractices": [],
    "evaluationIntro": "At Chandigarh University, we believe that assessment is a crucial part of the learning process — not just a measure of what you've learned, but a way to enhance your educational journey and prepare you for the challenges of the real world. Our innovative assessment practices are designed to align with our commitment to personalized learning, ensuring that every student can thrive and reach their full potential.\n\nThrough a variety of engaging, practical, and reflective assessment methods, we aim to equip our students with the skills, knowledge, and mindset needed for success in their chosen fields.",
    "evaluationPractices": [],
    "teachesAiCompetencies": false,
    "order": 10
  },
  {
    "discipline": "legal-studies",
    "name": "Legal Studies",
    "tagline": "Transform Society with Legal Expertise",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/images_our_programes_assets_new_LLA_301_69200c6ef2.webp",
      "alt": "",
      "width": 1200,
      "height": 667
    },
    "teachingIntro": "At Chandigarh University, we believe in the power of a unified yet distinct educational journey, seamlessly extending from our faculty philosophy down to the individual schools within each faculty. Our commitment is to ensure that the pedagogical approaches at the school level not only resonate with the overarching goals of the faculty but are also meticulously adapted to meet the unique demands and aspirations of each school's discipline.\n\nBy aligning the educational strategies across schools and faculties, we not only ensure a coherent educational philosophy but also enrich the learning journey by facilitating cross-disciplinary insights and opportunities. This approach allows students to benefit from a broad-based education while gaining deep expertise in their chosen fields.",
    "teachingPractices": [],
    "evaluationIntro": "At Chandigarh University, we believe that assessment is a crucial part of the learning process — not just a measure of what you've learned, but a way to enhance your educational journey and prepare you for the challenges of the real world. Our innovative assessment practices are designed to align with our commitment to personalized learning, ensuring that every student can thrive and reach their full potential.\n\nThrough a variety of engaging, practical, and reflective assessment methods, we aim to equip our students with the skills, knowledge, and mindset needed for success in their chosen fields.",
    "evaluationPractices": [],
    "teachesAiCompetencies": false,
    "order": 11
  },
  {
    "discipline": "liberal-arts",
    "name": "Liberal Arts",
    "tagline": "Empower With Versatility & Futuristic Liberal Arts Programs",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/images_our_programes_assets_new_LBA_701_b3c1e9fb2d.webp",
      "alt": "",
      "width": 2000,
      "height": 1000
    },
    "teachingIntro": "At Chandigarh University, we believe in the power of a unified yet distinct educational journey, seamlessly extending from our faculty philosophy down to the individual schools within each faculty. Our commitment is to ensure that the pedagogical approaches at the school level not only resonate with the overarching goals of the faculty but are also meticulously adapted to meet the unique demands and aspirations of each school's discipline.\n\nBy aligning the educational strategies across schools and faculties, we not only ensure a coherent educational philosophy but also enrich the learning journey by facilitating cross-disciplinary insights and opportunities. This approach allows students to benefit from a broad-based education while gaining deep expertise in their chosen fields.",
    "teachingPractices": [],
    "evaluationIntro": "At Chandigarh University, we believe that assessment is a crucial part of the learning process — not just a measure of what you've learned, but a way to enhance your educational journey and prepare you for the challenges of the real world. Our innovative assessment practices are designed to align with our commitment to personalized learning, ensuring that every student can thrive and reach their full potential.\n\nThrough a variety of engaging, practical, and reflective assessment methods, we aim to equip our students with the skills, knowledge, and mindset needed for success in their chosen fields.",
    "evaluationPractices": [],
    "teachesAiCompetencies": false,
    "order": 12
  },
  {
    "discipline": "pharmacy",
    "name": "Pharmacy",
    "tagline": "Innovate for a Healthier Tomorrow with Pharma Sciences",
    "heroImage": {
      "url": "http://127.0.0.1:1337/uploads/images_our_programes_assets_new_LPH_201_d4d387e2f1.webp",
      "alt": "",
      "width": 1200,
      "height": 667
    },
    "teachingIntro": "At Chandigarh University, we believe in the power of a unified yet distinct educational journey, seamlessly extending from our faculty philosophy down to the individual schools within each faculty. Our commitment is to ensure that the pedagogical approaches at the school level not only resonate with the overarching goals of the faculty but are also meticulously adapted to meet the unique demands and aspirations of each school's discipline.\n\nBy aligning the educational strategies across schools and faculties, we not only ensure a coherent educational philosophy but also enrich the learning journey by facilitating cross-disciplinary insights and opportunities. This approach allows students to benefit from a broad-based education while gaining deep expertise in their chosen fields.",
    "teachingPractices": [],
    "evaluationIntro": "At Chandigarh University, we believe that assessment is a crucial part of the learning process — not just a measure of what you've learned, but a way to enhance your educational journey and prepare you for the challenges of the real world. Our innovative assessment practices are designed to align with our commitment to personalized learning, ensuring that every student can thrive and reach their full potential.\n\nThrough a variety of engaging, practical, and reflective assessment methods, we aim to equip our students with the skills, knowledge, and mindset needed for success in their chosen fields.",
    "evaluationPractices": [],
    "teachesAiCompetencies": false,
    "order": 13
  }
];
