// Generated by the CU CMS. Do not edit.

import type { Scholarships } from '../types/data/scholarships';

export type { Scholarships };

export const SCHOLARSHIPS: Scholarships = [
  {
    "slug": "jee-mains",
    "kind": "merit",
    "name": "testing testing",
    "body": "testing testing",
    "slabs": [
      {
        "band": "testing testing",
        "value": "0000",
        "note": ""
      },
      {
        "band": "testing testing",
        "value": "0000",
        "note": ""
      },
      {
        "band": "testing testing",
        "value": "0000",
        "note": ""
      },
      {
        "band": "testing testing",
        "value": "0000",
        "note": ""
      },
      {
        "band": "testing testing",
        "value": "0000",
        "note": ""
      }
    ],
    "points": [],
    "continuation": "",
    "order": 1
  },
  {
    "slug": "mba-entrance",
    "kind": "merit",
    "name": "testing testing",
    "body": "",
    "slabs": [
      {
        "band": "testing testing",
        "value": "0000",
        "note": ""
      },
      {
        "band": "testing testing",
        "value": "0000",
        "note": ""
      },
      {
        "band": "testing testing",
        "value": "0000",
        "note": ""
      }
    ],
    "points": [],
    "continuation": "testing testing",
    "order": 2
  },
  {
    "slug": "ug-12th",
    "kind": "merit",
    "name": "testing testing",
    "body": "",
    "slabs": [
      {
        "band": "testing testing",
        "value": "0000",
        "note": ""
      },
      {
        "band": "testing testing",
        "value": "0000",
        "note": ""
      },
      {
        "band": "testing testing",
        "value": "0000",
        "note": ""
      }
    ],
    "points": [],
    "continuation": "testing testing",
    "order": 3
  },
  {
    "slug": "lateral-entry",
    "kind": "merit",
    "name": "testing testing",
    "body": "",
    "slabs": [
      {
        "band": "testing testing",
        "value": "0000",
        "note": ""
      },
      {
        "band": "testing testing",
        "value": "0000",
        "note": ""
      },
      {
        "band": "testing testing",
        "value": "0000",
        "note": ""
      }
    ],
    "points": [],
    "continuation": "",
    "order": 4
  },
  {
    "slug": "pg-graduation",
    "kind": "merit",
    "name": "testing testing",
    "body": "",
    "slabs": [
      {
        "band": "testing testing",
        "value": "0000",
        "note": ""
      },
      {
        "band": "testing testing",
        "value": "0000",
        "note": ""
      },
      {
        "band": "testing testing",
        "value": "0000",
        "note": ""
      },
      {
        "band": "testing testing",
        "value": "0000",
        "note": ""
      }
    ],
    "points": [],
    "continuation": "testing testing",
    "order": 5
  },
  {
    "slug": "gate",
    "kind": "merit",
    "name": "testing testing",
    "body": "",
    "slabs": [],
    "points": [
      {
        "text": "testing testing"
      },
      {
        "text": "testing testing"
      },
      {
        "text": "testing testing"
      },
      {
        "text": "testing testing"
      },
      {
        "text": "testing testing"
      }
    ],
    "continuation": "",
    "order": 6
  },
  {
    "slug": "ncsc",
    "kind": "merit",
    "name": "testing testing",
    "body": "",
    "slabs": [],
    "points": [
      {
        "text": "testing testing"
      },
      {
        "text": "testing testing"
      }
    ],
    "continuation": "",
    "order": 7
  },
  {
    "slug": "architecture",
    "kind": "merit",
    "name": "testing testing",
    "body": "testing testing",
    "slabs": [
      {
        "band": "testing testing",
        "value": "0000",
        "note": "testing testing"
      },
      {
        "band": "testing testing",
        "value": "0000",
        "note": "testing testing"
      },
      {
        "band": "testing testing",
        "value": "0000",
        "note": "testing testing"
      },
      {
        "band": "testing testing",
        "value": "0000",
        "note": ""
      }
    ],
    "points": [],
    "continuation": "",
    "order": 8
  },
  {
    "slug": "cgpa",
    "kind": "merit",
    "name": "testing testing",
    "body": "testing testing",
    "slabs": [],
    "points": [],
    "continuation": "",
    "order": 9
  },
  {
    "slug": "ladakh",
    "kind": "merit",
    "name": "testing testing",
    "body": "testing testing",
    "slabs": [],
    "points": [
      {
        "text": "testing testing"
      },
      {
        "text": "testing testing"
      },
      {
        "text": "testing testing"
      },
      {
        "text": "testing testing"
      }
    ],
    "continuation": "",
    "order": 10
  },
  {
    "slug": "cv-raman",
    "kind": "merit",
    "name": "testing testing",
    "body": "testing testing",
    "slabs": [
      {
        "band": "testing testing",
        "value": "0000",
        "note": ""
      },
      {
        "band": "testing testing",
        "value": "0000",
        "note": ""
      },
      {
        "band": "testing testing",
        "value": "0000",
        "note": ""
      },
      {
        "band": "testing testing",
        "value": "0000",
        "note": ""
      },
      {
        "band": "testing testing",
        "value": "0000",
        "note": ""
      }
    ],
    "points": [],
    "continuation": "testing testing",
    "order": 11
  },
  {
    "slug": "old-student",
    "kind": "concession",
    "name": "testing testing",
    "body": "testing testing",
    "slabs": [],
    "points": [],
    "continuation": "",
    "order": 100
  },
  {
    "slug": "single-girl-child",
    "kind": "concession",
    "name": "testing testing",
    "body": "testing testing",
    "slabs": [],
    "points": [],
    "continuation": "",
    "order": 101
  },
  {
    "slug": "teachers-ward",
    "kind": "concession",
    "name": "testing testing",
    "body": "testing testing",
    "slabs": [],
    "points": [],
    "continuation": "",
    "order": 102
  },
  {
    "slug": "sibling",
    "kind": "concession",
    "name": "testing testing",
    "body": "testing testing",
    "slabs": [],
    "points": [],
    "continuation": "",
    "order": 103
  },
  {
    "slug": "girl-sibling",
    "kind": "concession",
    "name": "testing testing",
    "body": "testing testing",
    "slabs": [],
    "points": [],
    "continuation": "",
    "order": 104
  },
  {
    "slug": "afews",
    "kind": "concession",
    "name": "testing testing",
    "body": "testing testing",
    "slabs": [],
    "points": [
      {
        "text": "testing testing"
      },
      {
        "text": "testing testing"
      },
      {
        "text": "testing testing"
      }
    ],
    "continuation": "",
    "order": 105
  },
  {
    "slug": "staff",
    "kind": "concession",
    "name": "testing testing",
    "body": "",
    "slabs": [],
    "points": [
      {
        "text": "testing testing"
      },
      {
        "text": "testing testing"
      }
    ],
    "continuation": "",
    "order": 106
  },
  {
    "slug": "orphan",
    "kind": "concession",
    "name": "testing testing",
    "body": "",
    "slabs": [],
    "points": [
      {
        "text": "testing testing"
      },
      {
        "text": "testing testing"
      }
    ],
    "continuation": "",
    "order": 107
  },
  {
    "slug": "early-bird",
    "kind": "concession",
    "name": "testing testing",
    "body": "testing testing",
    "slabs": [],
    "points": [
      {
        "text": "testing testing"
      },
      {
        "text": "testing testing"
      }
    ],
    "continuation": "",
    "order": 108
  },
  {
    "slug": "alumni",
    "kind": "concession",
    "name": "testing testing",
    "body": "testing testing",
    "slabs": [],
    "points": [],
    "continuation": "",
    "order": 109
  },
  {
    "slug": "gyan-kashi",
    "kind": "concession",
    "name": "testing testing",
    "body": "testing testing",
    "slabs": [],
    "points": [
      {
        "text": "testing testing"
      },
      {
        "text": "testing testing"
      },
      {
        "text": "testing testing"
      },
      {
        "text": "testing testing"
      }
    ],
    "continuation": "",
    "order": 110
  },
  {
    "slug": "kalpana-chawla",
    "kind": "concession",
    "name": "testing testing",
    "body": "testing testing",
    "slabs": [],
    "points": [
      {
        "text": "testing testing"
      },
      {
        "text": "testing testing"
      },
      {
        "text": "testing testing"
      }
    ],
    "continuation": "",
    "order": 111
  },
  {
    "slug": "vikram-batra",
    "kind": "concession",
    "name": "testing testing",
    "body": "testing testing",
    "slabs": [],
    "points": [
      {
        "text": "testing testing"
      },
      {
        "text": "testing testing"
      },
      {
        "text": "testing testing"
      },
      {
        "text": "testing testing"
      }
    ],
    "continuation": "",
    "order": 112
  }
];
