// Generated by the CU CMS. Do not edit.

import type { ThrustAreas } from '../types/data/thrust-areas';

export type { ThrustAreas };

export const THRUST_AREAS: ThrustAreas = [
  {
    "slug": "ai-and-machine-learning",
    "name": "testing testing",
    "body": "testing testing",
    "order": 1
  },
  {
    "slug": "deep-tech-research",
    "name": "testing testing",
    "body": "testing testing",
    "order": 2
  },
  {
    "slug": "nonlinear-dynamics",
    "name": "testing testing",
    "body": "testing testing",
    "order": 3
  },
  {
    "slug": "computational-linguistics",
    "name": "testing testing",
    "body": "testing testing",
    "order": 4
  },
  {
    "slug": "advanced-finance-and-strategic-management",
    "name": "testing testing",
    "body": "testing testing",
    "order": 5
  },
  {
    "slug": "nanomaterials-technology",
    "name": "testing testing",
    "body": "testing testing",
    "order": 6
  },
  {
    "slug": "genome-editing-and-transcriptomics",
    "name": "testing testing",
    "body": "testing testing",
    "order": 7
  },
  {
    "slug": "algal-technology",
    "name": "testing testing",
    "body": "testing testing",
    "order": 8
  },
  {
    "slug": "computational-epidemiology",
    "name": "testing testing",
    "body": "testing testing",
    "order": 9
  },
  {
    "slug": "human-resource-practices",
    "name": "testing testing",
    "body": "testing testing",
    "order": 10
  },
  {
    "slug": "indian-knowledge-system",
    "name": "testing testing",
    "body": "testing testing",
    "order": 11
  },
  {
    "slug": "ai-powered-financial-solutions",
    "name": "testing testing",
    "body": "testing testing",
    "order": 12
  },
  {
    "slug": "waste-management",
    "name": "testing testing",
    "body": "testing testing",
    "order": 13
  },
  {
    "slug": "sociology",
    "name": "testing testing",
    "body": "testing testing",
    "order": 14
  },
  {
    "slug": "smart-legal-research",
    "name": "testing testing",
    "body": "testing testing",
    "order": 15
  }
];
