// Generated by the CU CMS. Do not edit.

import type { About } from '../types/pages/about';

export type { About };

export const ABOUT: About = {
  "vision": "testing testing",
  "mission": [
    {
      "title": "testing testing",
      "body": "testing testing"
    },
    {
      "title": "testing testing",
      "body": "testing testing"
    },
    {
      "title": "testing testing",
      "body": "testing testing"
    },
    {
      "title": "testing testing",
      "body": "testing testing"
    },
    {
      "title": "testing testing",
      "body": "testing testing"
    },
    {
      "title": "testing testing",
      "body": "testing testing"
    },
    {
      "title": "testing testing",
      "body": "testing testing"
    },
    {
      "title": "testing testing",
      "body": "testing testing"
    }
  ],
  "coreValuesIntro": "0000",
  "coreValues": [
    {
      "name": "testing testing",
      "points": [
        {
          "text": "testing testing"
        },
        {
          "text": "testing testing"
        }
      ]
    },
    {
      "name": "testing testing",
      "points": [
        {
          "text": "testing testing"
        },
        {
          "text": "testing testing"
        }
      ]
    },
    {
      "name": "testing testing",
      "points": [
        {
          "text": "testing testing"
        },
        {
          "text": "testing testing"
        }
      ]
    },
    {
      "name": "testing testing",
      "points": [
        {
          "text": "testing testing"
        },
        {
          "text": "testing testing"
        }
      ]
    }
  ],
  "cuEdge": [
    {
      "title": "testing testing",
      "body": "testing testing"
    },
    {
      "title": "testing testing",
      "body": "testing testing"
    },
    {
      "title": "testing testing",
      "body": "testing testing"
    }
  ],
  "universityExperience": [
    {
      "title": "testing testing",
      "body": "testing testing"
    },
    {
      "title": "testing testing",
      "body": "testing testing"
    },
    {
      "title": "testing testing",
      "body": "testing testing"
    },
    {
      "title": "testing testing",
      "body": "testing testing"
    },
    {
      "title": "testing testing",
      "body": "testing testing"
    },
    {
      "title": "testing testing",
      "body": "testing testing"
    }
  ],
  "recognitions": [
    {
      "figure": "#19",
      "title": "testing testing",
      "body": "testing testing"
    },
    {
      "figure": "#31",
      "title": "testing testing",
      "body": "testing testing"
    },
    {
      "figure": "#32",
      "title": "testing testing",
      "body": "testing testing"
    },
    {
      "figure": "#15",
      "title": "testing testing",
      "body": "testing testing"
    },
    {
      "figure": "#14",
      "title": "testing testing",
      "body": "testing testing"
    },
    {
      "figure": "#1",
      "title": "testing testing",
      "body": "testing testing"
    },
    {
      "figure": "",
      "title": "testing testing",
      "body": "testing testing"
    },
    {
      "figure": "",
      "title": "testing testing",
      "body": "testing testing"
    },
    {
      "figure": "",
      "title": "testing testing",
      "body": "testing testing"
    }
  ],
  "approvalsLede": "testing testing",
  "approvals": [
    {
      "acronym": "testing testing",
      "name": "testing testing",
      "body": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1506905925346_21bda4d32df4_3e7d976a76.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "acronym": "testing testing",
      "name": "testing testing",
      "body": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1522202176988_66273c2fd55f_e8afb4bee4.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "acronym": "testing testing",
      "name": "testing testing",
      "body": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1523050854058_8df90110c9f1_5d3933d7b4.png",
        "alt": "testing image",
        "width": 800,
        "height": 600
      }
    },
    {
      "acronym": "testing testing",
      "name": "testing testing",
      "body": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1541339907198_e08756dedf3f_6466a1a79a.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "acronym": "testing testing",
      "name": "testing testing",
      "body": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1519389950473_47ba0277781c_004043fca3.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    }
  ],
  "leadershipIntro": "testing testing"
};
