// Generated by the CU CMS. Do not edit.

import type { Academics } from '../types/pages/academics';

export type { Academics };

export const ACADEMICS: Academics = {
  "intro": [],
  "teachingLede": "testing testing\n\ntesting testing",
  "evaluationLede": "testing testing\n\ntesting testing",
  "professionalBodiesLede": "testing testing",
  "labsLede": "testing testing",
  "holidaysTitle": "testing testing",
  "holidaysPeriod": "testing testing",
  "admissionSteps": [
    {
      "title": "testing testing",
      "body": "testing testing"
    },
    {
      "title": "testing testing",
      "body": "testing testing"
    },
    {
      "title": "testing testing",
      "body": "testing testing"
    }
  ],
  "teachingDesignGoals": [
    {
      "title": "testing testing",
      "body": "testing testing",
      "points": []
    },
    {
      "title": "testing testing",
      "body": "testing testing",
      "points": []
    },
    {
      "title": "testing testing",
      "body": "testing testing",
      "points": []
    }
  ]
};
