// Generated by the CU CMS. Do not edit.

import type { Academics } from '../types/pages/academics';

export type { Academics };

export const ACADEMICS: Academics = {
  "intro": [],
  "teachingLede": "At Chandigarh University, we believe in the power of a unified yet distinct educational journey, seamlessly extending from our faculty philosophy down to the individual schools within each faculty. Our commitment is to ensure that the pedagogical approaches at the school level not only resonate with the overarching goals of the faculty but are also meticulously adapted to meet the unique demands and aspirations of each school's discipline.\n\nBy aligning the educational strategies across schools and faculties, we not only ensure a coherent educational philosophy but also enrich the learning journey by facilitating cross-disciplinary insights and opportunities. This approach allows students to benefit from a broad-based education while gaining deep expertise in their chosen fields.",
  "evaluationLede": "At Chandigarh University, we believe that assessment is a crucial part of the learning process — not just a measure of what you've learned, but a way to enhance your educational journey and prepare you for the challenges of the real world. Our innovative assessment practices are designed to align with our commitment to personalized learning, ensuring that every student can thrive and reach their full potential.\n\nThrough a variety of engaging, practical, and reflective assessment methods, we aim to equip our students with the skills, knowledge, and mindset needed for success in their chosen fields.",
  "professionalBodiesLede": "The Professional Bodies are organisations designed to advance members' intellectual capabilities through an open exchange of information.",
  "labsLede": "Futuristic Labs: the catalyst for future-ready minds. Forty-four teaching and research laboratories across the campus, from the Centre of Immersive Pharmacology to the AI and Machine Learning Lab.",
  "holidaysTitle": "Holiday calendar for Chandigarh University, Unnao, Uttar Pradesh",
  "holidaysPeriod": "January – December 2026",
  "admissionSteps": [
    {
      "title": "Sign Up",
      "body": "Register for CUCET by providing your basic details — name, email, mobile number, state and gender."
    },
    {
      "title": "Apply for CUCET",
      "body": "You receive a confirmation on your registered number and email. Log in with those credentials and complete the eligibility and scholarship test application."
    },
    {
      "title": "Admission",
      "body": "On clearing CUCET, submit your admission application. Merit-based scholarship is assessed automatically from your result."
    }
  ],
  "teachingDesignGoals": [
    {
      "title": "Align with faculty vision",
      "body": "Ensure that the teaching and learning environment within each school is in harmony with the faculty's objectives, fostering a cohesive educational experience across levels.",
      "points": []
    },
    {
      "title": "Focus on multidisciplinary integration",
      "body": "Provide a learning approach that bridges the gap between various programs within the school, promoting interdisciplinary understanding and collaboration.",
      "points": []
    },
    {
      "title": "Meet unique disciplinary needs",
      "body": "Address the specific requirements and challenges of each school's discipline, ensuring that the education provided is both relevant and impactful.",
      "points": []
    }
  ]
};
