// Generated by the CU CMS. Do not edit.

import type { Admissions } from '../types/pages/admissions';

export type { Admissions };

export const ADMISSIONS: Admissions = {
  "scholarshipLede": "testing testing",
  "cucetScholarshipBody": "testing testing",
  "cucetScholarshipCap": "testing testing",
  "meritContinuation": "testing testing",
  "concessionContinuation": "testing testing",
  "scholarshipSpecialNote": "testing testing",
  "admissionCriteriaLede": "testing testing",
  "generalCriteria": [
    {
      "title": "testing testing",
      "body": "testing testing",
      "points": []
    },
    {
      "title": "testing testing",
      "body": "testing testing",
      "points": []
    },
    {
      "title": "testing testing",
      "body": "testing testing",
      "points": [
        {
          "text": "testing testing"
        },
        {
          "text": "testing testing"
        },
        {
          "text": "testing testing"
        },
        {
          "text": "testing testing"
        }
      ]
    },
    {
      "title": "testing testing",
      "body": "testing testing",
      "points": []
    },
    {
      "title": "testing testing",
      "body": "testing testing",
      "points": []
    },
    {
      "title": "testing testing",
      "body": "testing testing",
      "points": []
    }
  ],
  "pathways": [],
  "edgeStats": []
};
