// Generated by the CU CMS. Do not edit.

import type { Admissions } from '../types/pages/admissions';

export type { Admissions };

export const ADMISSIONS: Admissions = {
  "scholarshipLede": "Scholarship/Concession Schemes for the Session 2026-2027. The CUCET scholarship is assessed automatically from your entrance test score; every other scheme below is applied for at admission.",
  "cucetScholarshipBody": "The CUCET Scholarship is granted based on performance in the Chandigarh University Common Entrance Test (CUCET). This scholarship policy applies to all the applicants aspiring to pursue Undergraduate (UG) and Postgraduate (PG) programs at Chandigarh University, Uttar Pradesh.",
  "cucetScholarshipCap": "Maximum 5% of total intake seats in each course shall be offered under the scheme.",
  "meritContinuation": "For renewal of scholarship it is mandatory that the students admitted under all the above schemes shall have to maintain a minimum of 7.5 CGPA in regular semester exam in first chance without any semester drop (with NO “E”, “F”, “I” or “Not Qualified” grades) failing which the scholarship shall be discontinued.",
  "concessionContinuation": "For renewal it is mandatory that students admitted under the above schemes shall not have any semester/year drop and NO “E”, “F”, “I” or “Not Qualified” grades in the regular semester exam in first chance, failing which the concession shall be discontinued.",
  "scholarshipSpecialNote": "If the scholarship gets discontinued in one year due to not maintaining the mandatory requirements, and in the coming year the student maintains the minimum mandatory criteria, the student can apply for the scholarship again — however, in that case the student would be eligible for only 50 percent of the earlier sanctioned scholarship in the consequent year of study.",
  "admissionCriteriaLede": "Every programme is admitted on merit, through CUCET or an equivalent national entrance test. The general rules are below; the programme-specific requirement is printed against each course.",
  "generalCriteria": [
    {
      "title": "Entrance test",
      "body": "Admission to UG and PG programmes is through the Chandigarh University Common Entrance Test (CUCET), which doubles as the eligibility and scholarship test. Registering for CUCET is the first step of the application for every programme that requires it.",
      "points": []
    },
    {
      "title": "Merit basis",
      "body": "Students must have secured admission on a merit basis through the entrance test or the selection process of Chandigarh University as detailed in the prospectus.",
      "points": []
    },
    {
      "title": "National test equivalence",
      "body": "Scores from national-level entrance tests are recognised for scholarship assessment alongside CUCET.",
      "points": [
        {
          "text": "Engineering UG — JEE (Main) All India Rank"
        },
        {
          "text": "MBA — CAT, MAT, CMAT, ATMA or XAT percentile"
        },
        {
          "text": "B.Arch — NATA score or JEE (Main) Paper II percentile"
        },
        {
          "text": "M.E. programmes — GATE score, for the fellowship"
        }
      ]
    },
    {
      "title": "Lateral entry",
      "body": "Diploma holders are admitted through the Lateral Entry Entrance Test, and their scholarship is assessed on diploma marks rather than 10+2 marks.",
      "points": []
    },
    {
      "title": "Marks calculation",
      "body": "Marks percentage will be calculated from all appearing subjects (including additional subjects) in the Detail Marks Card.",
      "points": []
    },
    {
      "title": "Bridge courses",
      "body": "Where a programme assumes background a candidate does not have — Mathematics or introductory computing, for instance — the university offers a compulsory 3-credit bridge course as per university norms rather than refusing the application.",
      "points": []
    }
  ],
  "pathways": [],
  "edgeStats": []
};
