// Generated by the CU CMS. Do not edit.

import type { AdvancedCredit } from '../types/pages/advanced-credit';

export type { AdvancedCredit };

export const ADVANCED_CREDIT: AdvancedCredit = {
  "lede": "testing testing",
  "about": [
    {
      "text": "testing testing"
    },
    {
      "text": "testing testing"
    },
    {
      "text": "testing testing"
    }
  ],
  "stats": [
    {
      "value": "0000",
      "label": "testing testing"
    },
    {
      "value": "0000",
      "label": "testing testing"
    },
    {
      "value": "0000",
      "label": "testing testing"
    }
  ],
  "facts": [
    {
      "label": "testing testing",
      "value": "0000"
    },
    {
      "label": "testing testing",
      "value": "0000"
    },
    {
      "label": "testing testing",
      "value": "0000"
    },
    {
      "label": "testing testing",
      "value": "0000"
    }
  ],
  "benefits": [
    {
      "title": "testing testing",
      "body": "testing testing"
    },
    {
      "title": "testing testing",
      "body": "testing testing"
    },
    {
      "title": "testing testing",
      "body": "testing testing"
    },
    {
      "title": "testing testing",
      "body": "testing testing"
    },
    {
      "title": "testing testing",
      "body": "testing testing"
    }
  ],
  "objectives": [
    {
      "text": "testing testing"
    },
    {
      "text": "testing testing"
    },
    {
      "text": "testing testing"
    }
  ],
  "creditNote": "testing testing",
  "tracks": [
    {
      "name": "testing testing",
      "courses": [
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        }
      ]
    },
    {
      "name": "testing testing",
      "courses": [
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        }
      ]
    },
    {
      "name": "testing testing",
      "courses": [
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        }
      ]
    },
    {
      "name": "testing testing",
      "courses": [
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        },
        {
          "name": "testing testing"
        }
      ]
    }
  ],
  "enrolSteps": [
    {
      "title": "testing testing",
      "body": "testing testing"
    },
    {
      "title": "testing testing",
      "body": "testing testing"
    },
    {
      "title": "testing testing",
      "body": "testing testing"
    },
    {
      "title": "testing testing",
      "body": "testing testing"
    }
  ],
  "highlights": [
    {
      "text": "testing testing"
    },
    {
      "text": "testing testing"
    },
    {
      "text": "testing testing"
    },
    {
      "text": "testing testing"
    },
    {
      "text": "testing testing"
    },
    {
      "text": "testing testing"
    },
    {
      "text": "testing testing"
    },
    {
      "text": "testing testing"
    }
  ],
  "contactName": "testing testing",
  "contactPhone": "0000",
  "contactEmail": "testing testing"
};
