// Generated by the CU CMS. Do not edit.

import type { CampusLife } from '../types/pages/campus-life';

export type { CampusLife };

export const CAMPUS_LIFE: CampusLife = {
  "facilities": [
    {
      "name": "Food Courts",
      "body": "Catering to diverse tastes and dietary preferences, our food courts offer a wide variety of nutritious and flavourful meals.",
      "image": null
    },
    {
      "name": "Libraries",
      "body": "A haven for knowledge seekers, our libraries house an extensive collection of books, research papers, digital resources, and academic journals.",
      "image": null
    },
    {
      "name": "Banking",
      "body": "The university campus hosts full-fledged banking facilities, including ATMs, student-friendly loan services, and online transaction support.",
      "image": null
    },
    {
      "name": "Healthcare",
      "body": "Student well-being is our top priority, and our healthcare facilities ensure immediate medical assistance in times of need.",
      "image": null
    },
    {
      "name": "Transportation",
      "body": "Efficient and well-maintained transport services connect students and staff to and from the university with ease.",
      "image": null
    },
    {
      "name": "Sports",
      "body": "Our world-class sports facilities foster physical fitness, teamwork, and competitive spirit.",
      "image": null
    },
    {
      "name": "Gyms",
      "body": "State-of-the-art gyms offer modern workout equipment, personal training sessions, and group fitness classes.",
      "image": null
    },
    {
      "name": "Classrooms",
      "body": "Equipped with smart boards, ergonomic seating and high-speed internet connectivity to enhance the learning experience.",
      "image": null
    },
    {
      "name": "Laundry",
      "body": "Laundry service is available on campus at an additional charge; it is not included in the hostel fee.",
      "image": null
    }
  ],
  "hostelFacts": [
    {
      "label": "Blocks",
      "value": "Separate boys' and girls' hostels, 11 storeys, triquetra plan"
    },
    {
      "label": "Rooms",
      "value": "4-seater air-conditioned rooms with individual bed, almirah and study table"
    },
    {
      "label": "Meals",
      "value": "Three meals a day plus evening tea and snacks"
    },
    {
      "label": "Included",
      "value": "Gym, sports, salon and Wi-Fi access"
    },
    {
      "label": "Fee, SAARC",
      "value": "INR 1,45,000 per year"
    },
    {
      "label": "Fee, non-SAARC",
      "value": "USD 2,250 per year"
    }
  ]
};
