// Generated by the CU CMS. Do not edit.

import type { CampusLife } from '../types/pages/campus-life';

export type { CampusLife };

export const CAMPUS_LIFE: CampusLife = {
  "facilities": [
    {
      "name": "testing testing",
      "body": "testing testing",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1497366216548_37526070297c_cc9da0bc35.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 801
      }
    },
    {
      "name": "testing testing",
      "body": "testing testing",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1531482615713_2afd69097998_6b6c6f5768.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "body": "testing testing",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1523240795612_9a054b0db644_4024e78648.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "body": "testing testing",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1524178232363_1fb2b075b655_4844aedea4.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "body": "testing testing",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1562774053_701939374585_d6c47bbbb9.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 786
      }
    },
    {
      "name": "testing testing",
      "body": "testing testing",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1513258496099_48168024aec0_38d2e4fa8c.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "body": "testing testing",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1517486808906_6ca8b3f04846_4d025ae68f.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 1552
      }
    },
    {
      "name": "testing testing",
      "body": "testing testing",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1509062522246_3755977927d7_dd5c6e5f53.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 747
      }
    },
    {
      "name": "testing testing",
      "body": "testing testing",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1503676260728_1c00da094a0b_1593d6bdd5.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 847
      }
    }
  ],
  "hostelFacts": [
    {
      "label": "testing testing",
      "value": "0000"
    },
    {
      "label": "testing testing",
      "value": "0000"
    },
    {
      "label": "testing testing",
      "value": "0000"
    },
    {
      "label": "testing testing",
      "value": "0000"
    },
    {
      "label": "testing testing",
      "value": "0000"
    },
    {
      "label": "testing testing",
      "value": "0000"
    }
  ]
};
