// Generated by the CU CMS. Do not edit.

import type { CourseFees } from '../types/pages/course-fees';

export type { CourseFees };

export const COURSE_FEES: CourseFees = {
  "programDuration": "0000",
  "programFees": [
    {
      "label": "testing testing",
      "amount": "0000"
    },
    {
      "label": "testing testing",
      "amount": "0000"
    },
    {
      "label": "testing testing",
      "amount": "0000"
    }
  ],
  "scholarshipTiers": [
    {
      "band": "0000",
      "scholarshipAmount": "0000",
      "amountToPay": "0000"
    },
    {
      "band": "0000",
      "scholarshipAmount": "0000",
      "amountToPay": "0000"
    },
    {
      "band": "0000",
      "scholarshipAmount": "0000",
      "amountToPay": "0000"
    },
    {
      "band": "0000",
      "scholarshipAmount": "0000",
      "amountToPay": "0000"
    },
    {
      "band": "0000",
      "scholarshipAmount": "0000",
      "amountToPay": "0000"
    },
    {
      "band": "0000",
      "scholarshipAmount": "0000",
      "amountToPay": "0000"
    }
  ]
};
