// Generated by the CU CMS. Do not edit.

import type { HowToApply } from '../types/pages/how-to-apply';

export type { HowToApply };

export const HOW_TO_APPLY: HowToApply = {
  "heading": "testing testing",
  "lede": "testing testing",
  "steps": [
    {
      "num": "",
      "title": "testing testing",
      "body": "testing testing",
      "ctaLabel": "",
      "ctaHref": "",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1506905925346_21bda4d32df4_3e7d976a76.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "num": "",
      "title": "testing testing",
      "body": "testing testing",
      "ctaLabel": "",
      "ctaHref": "",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1522202176988_66273c2fd55f_e8afb4bee4.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "num": "",
      "title": "testing testing",
      "body": "testing testing",
      "ctaLabel": "",
      "ctaHref": "",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1523050854058_8df90110c9f1_5d3933d7b4.png",
        "alt": "testing image",
        "width": 800,
        "height": 600
      }
    }
  ],
  "outcomeTitle": "testing testing",
  "outcomeBody": "testing testing"
};
