// Generated by the CU CMS. Do not edit.

import type { HowToApply } from '../types/pages/how-to-apply';

export type { HowToApply };

export const HOW_TO_APPLY: HowToApply = {
  "heading": "Six steps, all online",
  "lede": "The steps to apply to Chandigarh University Uttar Pradesh, from registering for CUCET to confirming your seat.",
  "steps": [
    {
      "num": "",
      "title": "Sign Up",
      "body": "Register for CUCET by providing your basic details — name, email, mobile number, state and gender.",
      "ctaLabel": "",
      "ctaHref": "",
      "image": null
    },
    {
      "num": "",
      "title": "Apply for CUCET",
      "body": "You receive a confirmation on your registered number and email. Log in with those credentials and complete the eligibility and scholarship test application.",
      "ctaLabel": "",
      "ctaHref": "",
      "image": null
    },
    {
      "num": "",
      "title": "Admission",
      "body": "On clearing CUCET, submit your admission application. Merit-based scholarship is assessed automatically from your result.",
      "ctaLabel": "",
      "ctaHref": "",
      "image": null
    }
  ],
  "outcomeTitle": "A CUCET score",
  "outcomeBody": "Your result arrives shortly after you sit the test, and it is what every scholarship band below is assessed from."
};
