// Generated by the CU CMS. Do not edit.

import type { International } from '../types/pages/international';

export type { International };

export const INTERNATIONAL: International = {
  "cohortHeading": "Shape your *global* future",
  "cohortBody": [
    {
      "text": "Witness the CU UP Excellence. 40+ partner universities across the globe."
    }
  ],
  "cohortStats": [],
  "cohortImage": null,
  "shiftHeading": "Study here, *and abroad*",
  "shiftBody": [
    {
      "text": "Applications for the 2026 session are open. Exchange and credit-transfer options are available from the first year."
    }
  ]
};
