// Generated by the CU CMS. Do not edit.

import type { Leaves } from '../types/pages/leaves';

export type { Leaves };

export const LEAVES: Leaves = [
  {
    "siteRoute": "uanh0am3iv0pqy798kw1a9fi",
    "intro": "testing testing",
    "blocks": [
      {
        "anchorId": "gamified-learning",
        "index": "0000",
        "label": "testing testing",
        "title": "testing testing",
        "paragraphs": [
          {
            "text": "testing testing"
          }
        ]
      },
      {
        "anchorId": "predictive-analytics",
        "index": "0000",
        "label": "testing testing",
        "title": "testing testing",
        "paragraphs": [
          {
            "text": "testing testing"
          }
        ]
      },
      {
        "anchorId": "personalised-paths",
        "index": "0000",
        "label": "testing testing",
        "title": "testing testing",
        "paragraphs": [
          {
            "text": "testing testing"
          }
        ]
      },
      {
        "anchorId": "data-driven-insights",
        "index": "0000",
        "label": "testing testing",
        "title": "testing testing",
        "paragraphs": [
          {
            "text": "testing testing"
          }
        ]
      },
      {
        "anchorId": "virtual-assistance",
        "index": "0000",
        "label": "testing testing",
        "title": "testing testing",
        "paragraphs": [
          {
            "text": "testing testing"
          }
        ]
      }
    ],
    "chips": [],
    "gallery": [
      {
        "groupId": "learning",
        "label": "testing testing",
        "images": [
          {
            "url": "http://127.0.0.1:1337/uploads/testing_photo_1513258496099_48168024aec0_38d2e4fa8c.jpg",
            "alt": "testing image",
            "width": 1200,
            "height": 800
          }
        ]
      }
    ]
  },
  {
    "siteRoute": "gjfuvlgvx6o4zxdqbawaeubd",
    "intro": "testing testing",
    "blocks": [
      {
        "anchorId": "coe-marketing",
        "index": "0000",
        "label": "testing testing",
        "title": "testing testing",
        "paragraphs": [
          {
            "text": "testing testing"
          }
        ]
      },
      {
        "anchorId": "coe-computer-vision",
        "index": "0000",
        "label": "testing testing",
        "title": "testing testing",
        "paragraphs": [
          {
            "text": "testing testing"
          }
        ]
      }
    ],
    "chips": [],
    "gallery": [
      {
        "groupId": "labs",
        "label": "testing testing",
        "images": [
          {
            "url": "http://127.0.0.1:1337/uploads/testing_photo_1517486808906_6ca8b3f04846_4d025ae68f.jpg",
            "alt": "testing image",
            "width": 1200,
            "height": 1552
          }
        ]
      }
    ]
  },
  {
    "siteRoute": "ot802sqv7f4fvczh6j741n20",
    "intro": "testing testing",
    "blocks": [
      {
        "anchorId": "connected-campus",
        "index": "0000",
        "label": "testing testing",
        "title": "testing testing",
        "paragraphs": [
          {
            "text": "testing testing"
          },
          {
            "text": "testing testing"
          }
        ]
      },
      {
        "anchorId": "safety-and-green-living",
        "index": "0000",
        "label": "testing testing",
        "title": "testing testing",
        "paragraphs": [
          {
            "text": "testing testing"
          },
          {
            "text": "testing testing"
          }
        ]
      },
      {
        "anchorId": "adaptive-infrastructure",
        "index": "0000",
        "label": "testing testing",
        "title": "testing testing",
        "paragraphs": [
          {
            "text": "testing testing"
          },
          {
            "text": "testing testing"
          }
        ]
      },
      {
        "anchorId": "sustainable-operations",
        "index": "0000",
        "label": "testing testing",
        "title": "testing testing",
        "paragraphs": [
          {
            "text": "testing testing"
          },
          {
            "text": "testing testing"
          }
        ]
      }
    ],
    "chips": [],
    "gallery": [
      {
        "groupId": "campus",
        "label": "testing testing",
        "images": [
          {
            "url": "http://127.0.0.1:1337/uploads/testing_photo_1509062522246_3755977927d7_dd5c6e5f53.jpg",
            "alt": "testing image",
            "width": 1200,
            "height": 747
          }
        ]
      }
    ]
  },
  {
    "siteRoute": "kt4ydrdbk5lgn9eob88jrc8y",
    "intro": "testing testing\n\ntesting testing",
    "blocks": [
      {
        "anchorId": "research-and-innovation",
        "index": "0000",
        "label": "testing testing",
        "title": "testing testing",
        "paragraphs": [
          {
            "text": "testing testing"
          },
          {
            "text": "testing testing"
          },
          {
            "text": "testing testing"
          },
          {
            "text": "testing testing"
          }
        ]
      },
      {
        "anchorId": "objectives",
        "index": "0000",
        "label": "testing testing",
        "title": "testing testing",
        "paragraphs": [
          {
            "text": "testing testing"
          }
        ]
      }
    ],
    "chips": [],
    "gallery": []
  },
  {
    "siteRoute": "eogwa0bgoblhmy9cto6rv49u",
    "intro": "testing testing",
    "blocks": [
      {
        "anchorId": "facilities",
        "index": "0000",
        "label": "testing testing",
        "title": "testing testing",
        "paragraphs": [
          {
            "text": "testing testing"
          },
          {
            "text": "testing testing"
          }
        ]
      },
      {
        "anchorId": "training",
        "index": "0000",
        "label": "testing testing",
        "title": "testing testing",
        "paragraphs": [
          {
            "text": "testing testing"
          },
          {
            "text": "testing testing"
          }
        ]
      },
      {
        "anchorId": "wellness",
        "index": "0000",
        "label": "testing testing",
        "title": "testing testing",
        "paragraphs": [
          {
            "text": "testing testing"
          },
          {
            "text": "testing testing"
          }
        ]
      },
      {
        "anchorId": "gym-equipment",
        "index": "0000",
        "label": "testing testing",
        "title": "testing testing",
        "paragraphs": [
          {
            "text": "testing testing"
          }
        ]
      },
      {
        "anchorId": "fitness-programs",
        "index": "0000",
        "label": "testing testing",
        "title": "testing testing",
        "paragraphs": [
          {
            "text": "testing testing"
          }
        ]
      }
    ],
    "chips": [],
    "gallery": [
      {
        "groupId": "grounds",
        "label": "testing testing",
        "images": [
          {
            "url": "http://127.0.0.1:1337/uploads/testing_photo_1503676260728_1c00da094a0b_1593d6bdd5.jpg",
            "alt": "testing image",
            "width": 1200,
            "height": 847
          }
        ]
      }
    ]
  },
  {
    "siteRoute": "t33zw71dvqcirpeyf71thzle",
    "intro": "testing testing",
    "blocks": [
      {
        "anchorId": "academic-resources",
        "index": "0000",
        "label": "testing testing",
        "title": "testing testing",
        "paragraphs": [
          {
            "text": "testing testing"
          }
        ]
      },
      {
        "anchorId": "study-spaces",
        "index": "0000",
        "label": "testing testing",
        "title": "testing testing",
        "paragraphs": [
          {
            "text": "testing testing"
          }
        ]
      },
      {
        "anchorId": "technology",
        "index": "0000",
        "label": "testing testing",
        "title": "testing testing",
        "paragraphs": [
          {
            "text": "testing testing"
          }
        ]
      }
    ],
    "chips": [],
    "gallery": [
      {
        "groupId": "library",
        "label": "testing testing",
        "images": [
          {
            "url": "http://127.0.0.1:1337/uploads/testing_photo_1571260899304_425eee4c7efc_5ce92f65fd.jpg",
            "alt": "testing image",
            "width": 1200,
            "height": 800
          }
        ]
      }
    ]
  },
  {
    "siteRoute": "d75ye9hnmqok9jg4sqww2p6v",
    "intro": "testing testing",
    "blocks": [
      {
        "anchorId": "accommodation",
        "index": "0000",
        "label": "testing testing",
        "title": "testing testing",
        "paragraphs": [
          {
            "text": "testing testing"
          },
          {
            "text": "testing testing"
          }
        ]
      },
      {
        "anchorId": "living",
        "index": "0000",
        "label": "testing testing",
        "title": "testing testing",
        "paragraphs": [
          {
            "text": "testing testing"
          },
          {
            "text": "testing testing"
          }
        ]
      },
      {
        "anchorId": "services",
        "index": "0000",
        "label": "testing testing",
        "title": "testing testing",
        "paragraphs": [
          {
            "text": "testing testing"
          },
          {
            "text": "testing testing"
          }
        ]
      },
      {
        "anchorId": "allotment",
        "index": "0000",
        "label": "testing testing",
        "title": "testing testing",
        "paragraphs": [
          {
            "text": "testing testing"
          }
        ]
      }
    ],
    "chips": [],
    "gallery": [
      {
        "groupId": "hostel",
        "label": "testing testing",
        "images": [
          {
            "url": "http://127.0.0.1:1337/uploads/testing_photo_1506905925346_21bda4d32df4_3e7d976a76.jpg",
            "alt": "testing image",
            "width": 1200,
            "height": 800
          }
        ]
      },
      {
        "groupId": "around",
        "label": "testing testing",
        "images": [
          {
            "url": "http://127.0.0.1:1337/uploads/testing_photo_1522202176988_66273c2fd55f_e8afb4bee4.jpg",
            "alt": "testing image",
            "width": 1200,
            "height": 800
          }
        ]
      }
    ]
  },
  {
    "siteRoute": "t54ydssbth4jk4m4sh0pgzw0",
    "intro": "testing testing",
    "blocks": [
      {
        "anchorId": "campus-events",
        "index": "0000",
        "label": "testing testing",
        "title": "testing testing",
        "paragraphs": [
          {
            "text": "testing testing"
          }
        ]
      },
      {
        "anchorId": "cultural",
        "index": "0000",
        "label": "testing testing",
        "title": "testing testing",
        "paragraphs": [
          {
            "text": "testing testing"
          }
        ]
      },
      {
        "anchorId": "competitions",
        "index": "0000",
        "label": "testing testing",
        "title": "testing testing",
        "paragraphs": [
          {
            "text": "testing testing"
          }
        ]
      },
      {
        "anchorId": "community",
        "index": "0000",
        "label": "testing testing",
        "title": "testing testing",
        "paragraphs": [
          {
            "text": "testing testing"
          }
        ]
      }
    ],
    "chips": [
      {
        "label": "testing testing"
      },
      {
        "label": "testing testing"
      },
      {
        "label": "testing testing"
      },
      {
        "label": "testing testing"
      },
      {
        "label": "testing testing"
      },
      {
        "label": "testing testing"
      }
    ],
    "gallery": [
      {
        "groupId": "fests",
        "label": "testing testing",
        "images": [
          {
            "url": "http://127.0.0.1:1337/uploads/testing_photo_1523050854058_8df90110c9f1_5d3933d7b4.png",
            "alt": "testing image",
            "width": 800,
            "height": 600
          }
        ]
      },
      {
        "groupId": "events",
        "label": "testing testing",
        "images": [
          {
            "url": "http://127.0.0.1:1337/uploads/testing_photo_1541339907198_e08756dedf3f_6466a1a79a.jpg",
            "alt": "testing image",
            "width": 1200,
            "height": 800
          }
        ]
      }
    ]
  }
];
