// Generated by the CU CMS. Do not edit.

import type { Research } from '../types/pages/research';

export type { Research };

export const RESEARCH: Research = {
  "eyebrow": "testing testing",
  "intro": "testing testing"
};
