// Generated by the CU CMS. Do not edit.

import type { FaqSection } from '../../types/pages/home/faq';

export type { FaqSection };

export const FAQ_SECTION: FaqSection = {
  "heading": "testing *testing*",
  "tabs": {
    "General": [
      {
        "question": "testing testing",
        "answer": "testing testing",
        "cta": {
          "label": "testing testing",
          "href": "#"
        }
      },
      {
        "question": "testing testing",
        "answer": "testing testing",
        "cta": null
      },
      {
        "question": "testing testing",
        "answer": "testing testing",
        "cta": null
      }
    ],
    "Admissions": [
      {
        "question": "testing testing",
        "answer": "testing testing",
        "cta": null
      },
      {
        "question": "testing testing",
        "answer": "testing testing",
        "cta": null
      },
      {
        "question": "testing testing",
        "answer": "testing testing",
        "cta": null
      }
    ],
    "Academics": [
      {
        "question": "testing testing",
        "answer": "testing testing",
        "cta": null
      },
      {
        "question": "testing testing",
        "answer": "testing testing",
        "cta": null
      },
      {
        "question": "testing testing",
        "answer": "testing testing",
        "cta": null
      }
    ],
    "Campus Life": [
      {
        "question": "testing testing",
        "answer": "testing testing",
        "cta": {
          "label": "testing testing",
          "href": "#"
        }
      },
      {
        "question": "testing testing",
        "answer": "testing testing",
        "cta": null
      }
    ]
  }
};
