// Generated by the CU CMS. Do not edit.

import type { HeroSection } from '../../types/pages/home/hero';

export type { HeroSection };

export const HERO_SECTION: HeroSection = {
  "heading": "testing *testing*",
  "subheading": "testing testing",
  "fallbackImage": {
    "url": "http://127.0.0.1:1337/uploads/testing_photo_1571260899304_425eee4c7efc_5ce92f65fd.jpg",
    "alt": "testing image",
    "width": 1200,
    "height": 800
  },
  "countdownDeadline": "2026-10-20T18:29:59.000Z",
  "countdownLabel": "0000",
  "countdownDateLabel": "0000"
};
