// Generated by the CU CMS. Do not edit.

import type { HeroSection } from '../../types/pages/home/hero';

export type { HeroSection };

export const HERO_SECTION: HeroSection = {
  "heading": "India's First *AI-Augmented\nMultidisciplinary University*",
  "subheading": "In an era propelled by the advent of artificial intelligence, Chandigarh University, Uttar Pradesh, has embraced a multidisciplinary education model enriched by AI integration, prioritising customised learning pathways, data-driven insights, virtual reality experiences, and real-world simulations to prepare global visionaries.",
  "fallbackImage": {
    "url": "http://127.0.0.1:1337/uploads/images_hero_bg_0f8469866c.webp",
    "alt": "Chandigarh University",
    "width": 1728,
    "height": 1151
  },
  "countdownDeadline": "2026-10-20T18:29:59.000Z",
  "countdownLabel": "Application Window For CUCET\n(Phase-I) Closes On",
  "countdownDateLabel": "15th October 2026"
};
