// Generated by the CU CMS. Do not edit.

import type { HeroBackgroundVideo } from '../../types/pages/home/hero-video';

export type { HeroBackgroundVideo };

export const HERO_BACKGROUND_VIDEO: HeroBackgroundVideo = {
  "video": {
    "url": "http://127.0.0.1:1337/uploads/images_header_vod_a3e95f51ba.mp4",
    "mime": "video/mp4"
  }
};
