// Generated by the CU CMS. Do not edit.

import type { InnovationStartupsSection } from '../../types/pages/home/innovation';

export type { InnovationStartupsSection };

export const INNOVATION_STARTUPS_SECTION: InnovationStartupsSection = {
  "ecosystemHeading": "testing *testing*",
  "ecosystemSubheading": "testing testing",
  "pillarsHeading": "testing *testing*",
  "pillarsSubheading": "testing testing",
  "startupsSubheading": "testing testing",
  "stats": [
    {
      "id": "1",
      "value": "0000",
      "prefix": "",
      "label": "testing testing",
      "tone": "plain"
    },
    {
      "id": "2",
      "value": "0000",
      "prefix": "",
      "label": "testing testing",
      "tone": "ink"
    },
    {
      "id": "3",
      "value": "0000",
      "prefix": "test",
      "label": "testing testing",
      "tone": "red"
    },
    {
      "id": "4",
      "value": "0000",
      "prefix": "",
      "label": "testing testing",
      "tone": "track"
    }
  ],
  "pillars": [
    {
      "id": "1",
      "title": "testing testing",
      "body": "testing testing",
      "chips": [
        "testing testing",
        "testing testing",
        "testing testing",
        "testing testing"
      ],
      "glyph": "lattice"
    },
    {
      "id": "2",
      "title": "testing testing",
      "body": "testing testing",
      "chips": [
        "testing testing",
        "testing testing",
        "testing testing",
        "testing testing"
      ],
      "glyph": "orbit"
    },
    {
      "id": "3",
      "title": "testing testing",
      "body": "testing testing",
      "chips": [
        "testing testing",
        "testing testing",
        "testing testing",
        "testing testing"
      ],
      "glyph": "ascent"
    },
    {
      "id": "4",
      "title": "testing testing",
      "body": "testing testing",
      "chips": [
        "testing testing",
        "testing testing",
        "testing testing",
        "testing testing"
      ],
      "glyph": "broadcast"
    }
  ],
  "startups": [
    {
      "id": "1",
      "name": "testing testing",
      "sector": "testing testing",
      "founders": "testing testing",
      "description": "testing testing",
      "videoUrl": "https://www.youtube.com/embed/9snJSH9CdUs",
      "clipSrc": "http://127.0.0.1:1337/uploads/images_innovation_startups_clips_better_idea_be421f832a.mp4",
      "clipPoster": "http://127.0.0.1:1337/uploads/testing_photo_1541339907198_e08756dedf3f_6466a1a79a.jpg"
    },
    {
      "id": "2",
      "name": "testing testing",
      "sector": "testing testing",
      "founders": "testing testing",
      "description": "testing testing",
      "videoUrl": "https://www.youtube.com/embed/xxXloEwplhk",
      "clipSrc": "http://127.0.0.1:1337/uploads/images_innovation_startups_clips_medoc_health_eff6bab230.mp4",
      "clipPoster": "http://127.0.0.1:1337/uploads/testing_photo_1519389950473_47ba0277781c_004043fca3.jpg"
    },
    {
      "id": "3",
      "name": "testing testing",
      "sector": "testing testing",
      "founders": "testing testing",
      "description": "testing testing",
      "videoUrl": "https://www.youtube.com/embed/-tDjE07JjBQ",
      "clipSrc": "http://127.0.0.1:1337/uploads/images_innovation_startups_clips_aurasm_523478d9d4.mp4",
      "clipPoster": "http://127.0.0.1:1337/uploads/testing_photo_1497366216548_37526070297c_cc9da0bc35.jpg"
    },
    {
      "id": "4",
      "name": "testing testing",
      "sector": "testing testing",
      "founders": "testing testing",
      "description": "testing testing",
      "videoUrl": "https://www.youtube.com/embed/T0GJ6qHNprA",
      "clipSrc": "http://127.0.0.1:1337/uploads/images_innovation_startups_clips_anon_ca10206a88.mp4",
      "clipPoster": "http://127.0.0.1:1337/uploads/testing_photo_1531482615713_2afd69097998_6b6c6f5768.jpg"
    }
  ],
  "tiles": [
    {
      "id": "1",
      "cover": "http://127.0.0.1:1337/uploads/testing_photo_1523240795612_9a054b0db644_4024e78648.jpg",
      "caption": "testing testing",
      "alt": "testing image",
      "gallery": [
        {
          "src": "http://127.0.0.1:1337/uploads/testing_photo_1523240795612_9a054b0db644_4024e78648.jpg",
          "alt": "testing image"
        }
      ]
    },
    {
      "id": "2",
      "cover": "http://127.0.0.1:1337/uploads/testing_photo_1524178232363_1fb2b075b655_4844aedea4.jpg",
      "caption": "testing testing",
      "alt": "testing image",
      "gallery": [
        {
          "src": "http://127.0.0.1:1337/uploads/testing_photo_1524178232363_1fb2b075b655_4844aedea4.jpg",
          "alt": "testing image"
        }
      ]
    },
    {
      "id": "3",
      "cover": "http://127.0.0.1:1337/uploads/testing_photo_1562774053_701939374585_d6c47bbbb9.jpg",
      "caption": "testing testing",
      "alt": "testing image",
      "gallery": [
        {
          "src": "http://127.0.0.1:1337/uploads/testing_photo_1562774053_701939374585_d6c47bbbb9.jpg",
          "alt": "testing image"
        }
      ]
    },
    {
      "id": "4",
      "cover": "http://127.0.0.1:1337/uploads/testing_photo_1513258496099_48168024aec0_38d2e4fa8c.jpg",
      "caption": "testing testing",
      "alt": "testing image",
      "gallery": [
        {
          "src": "http://127.0.0.1:1337/uploads/testing_photo_1513258496099_48168024aec0_38d2e4fa8c.jpg",
          "alt": "testing image"
        }
      ]
    }
  ]
};
