// Generated by the CU CMS. Do not edit.

import type { InternationalSection } from '../../types/pages/home/international';

export type { InternationalSection };

export const INTERNATIONAL_SECTION: InternationalSection = {
  "heading": "testing *testing*",
  "subheading": "testing testing",
  "cards": [
    {
      "id": "1",
      "title": "testing testing",
      "text": "testing testing",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1509062522246_3755977927d7_dd5c6e5f53.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 747
      },
      "link": null
    },
    {
      "id": "2",
      "title": "testing testing",
      "text": "testing testing",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1503676260728_1c00da094a0b_1593d6bdd5.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 847
      },
      "link": null
    },
    {
      "id": "3",
      "title": "testing testing",
      "text": "testing testing",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1571260899304_425eee4c7efc_5ce92f65fd.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      },
      "link": null
    },
    {
      "id": "4",
      "title": "testing testing",
      "text": "testing testing",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1506905925346_21bda4d32df4_3e7d976a76.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      },
      "link": null
    },
    {
      "id": "5",
      "title": "testing testing",
      "text": "testing testing",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1522202176988_66273c2fd55f_e8afb4bee4.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      },
      "link": null
    },
    {
      "id": "6",
      "title": "testing testing",
      "text": "testing testing",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1523050854058_8df90110c9f1_5d3933d7b4.png",
        "alt": "testing image",
        "width": 800,
        "height": 600
      },
      "link": null
    },
    {
      "id": "7",
      "title": "testing testing",
      "text": "testing testing",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1541339907198_e08756dedf3f_6466a1a79a.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      },
      "link": null
    },
    {
      "id": "8",
      "title": "testing testing",
      "text": "testing testing",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1519389950473_47ba0277781c_004043fca3.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      },
      "link": null
    }
  ],
  "partnerLogos": [
    {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1497366216548_37526070297c_cc9da0bc35.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 801
    }
  ]
};
