// Generated by the CU CMS. Do not edit.

import type { MomentsMilestoneSection } from '../../types/pages/home/moments';

export type { MomentsMilestoneSection };

export const MOMENTS_MILESTONE_SECTION: MomentsMilestoneSection = {
  "heading": "testing *testing*",
  "cards": [
    {
      "id": "1",
      "badge": "testing testing",
      "headSans": "testing testing",
      "headItalic": "testing testing",
      "headTail": null,
      "body": "testing testing",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1519389950473_47ba0277781c_004043fca3.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      },
      "imageMobile": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1524178232363_1fb2b075b655_4844aedea4.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      },
      "imageCaption": null,
      "imageTreatment": "cover",
      "tiles": [
        {
          "label": "testing testing",
          "value": "0000",
          "valueSuffix": "0000",
          "rows": []
        },
        {
          "label": "testing testing",
          "value": "0000",
          "valueSuffix": "0000",
          "rows": [
            {
              "label": "testing testing",
              "value": null
            },
            {
              "label": "testing testing",
              "value": null
            }
          ]
        }
      ]
    },
    {
      "id": "2",
      "badge": "testing testing",
      "headSans": "testing testing",
      "headItalic": "testing testing",
      "headTail": null,
      "body": "testing testing",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1497366216548_37526070297c_cc9da0bc35.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 801
      },
      "imageMobile": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1562774053_701939374585_d6c47bbbb9.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 786
      },
      "imageCaption": "testing testing",
      "imageTreatment": "cover",
      "tiles": [
        {
          "label": "testing testing",
          "value": "0000",
          "valueSuffix": "0000",
          "rows": [
            {
              "label": "testing testing",
              "value": "0000"
            },
            {
              "label": "testing testing",
              "value": "0000"
            }
          ]
        },
        {
          "label": "testing testing",
          "value": "0000",
          "valueSuffix": "0000",
          "rows": [
            {
              "label": "testing testing",
              "value": "0000"
            },
            {
              "label": "testing testing",
              "value": "0000"
            }
          ]
        }
      ]
    },
    {
      "id": "3",
      "badge": "testing testing",
      "headSans": "testing testing",
      "headItalic": "testing testing",
      "headTail": null,
      "body": "testing testing",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1531482615713_2afd69097998_6b6c6f5768.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      },
      "imageMobile": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1513258496099_48168024aec0_38d2e4fa8c.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      },
      "imageCaption": "testing testing",
      "imageTreatment": "cover",
      "tiles": [
        {
          "label": "testing testing",
          "value": "0000",
          "valueSuffix": "0000",
          "rows": [
            {
              "label": "testing testing",
              "value": "0000"
            },
            {
              "label": "testing testing",
              "value": "0000"
            }
          ]
        },
        {
          "label": "testing testing",
          "value": "0000",
          "valueSuffix": "0000",
          "rows": [
            {
              "label": "testing testing",
              "value": "0000"
            },
            {
              "label": "testing testing",
              "value": "0000"
            }
          ]
        }
      ]
    },
    {
      "id": "4",
      "badge": "testing testing",
      "headSans": "testing testing",
      "headItalic": "testing testing",
      "headTail": null,
      "body": "testing testing",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1523240795612_9a054b0db644_4024e78648.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      },
      "imageMobile": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1517486808906_6ca8b3f04846_4d025ae68f.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 1552
      },
      "imageCaption": "testing testing",
      "imageTreatment": "cover",
      "tiles": [
        {
          "label": "testing testing",
          "value": "0000",
          "valueSuffix": "0000",
          "rows": [
            {
              "label": "testing testing",
              "value": "0000"
            },
            {
              "label": "testing testing",
              "value": "0000"
            },
            {
              "label": "testing testing",
              "value": "0000"
            }
          ]
        },
        {
          "label": "testing testing",
          "value": "0000",
          "valueSuffix": "0000",
          "rows": [
            {
              "label": "testing testing",
              "value": "0000"
            },
            {
              "label": "testing testing",
              "value": "0000"
            }
          ]
        }
      ]
    }
  ]
};
