// Generated by the CU CMS. Do not edit.

import type { NewsSection } from '../../types/pages/home/news';

export type { NewsSection };

export const NEWS_SECTION: NewsSection = {
  "heading": "testing *testing*",
  "tabs": [
    {
      "id": 0,
      "label": "testing *testing*",
      "theme": "active",
      "stories": [
        {
          "title": "testing *testing*",
          "description": "testing testing",
          "image": {
            "url": "http://127.0.0.1:1337/uploads/testing_photo_1509062522246_3755977927d7_dd5c6e5f53.jpg",
            "alt": "testing image",
            "width": 1200,
            "height": 747
          }
        },
        {
          "title": "testing *testing*",
          "description": "testing testing",
          "image": {
            "url": "http://127.0.0.1:1337/uploads/testing_photo_1503676260728_1c00da094a0b_1593d6bdd5.jpg",
            "alt": "testing image",
            "width": 1200,
            "height": 847
          }
        },
        {
          "title": "testing *testing*",
          "description": "testing testing",
          "image": {
            "url": "http://127.0.0.1:1337/uploads/testing_photo_1571260899304_425eee4c7efc_5ce92f65fd.jpg",
            "alt": "testing image",
            "width": 1200,
            "height": 800
          }
        },
        {
          "title": "testing *testing*",
          "description": "testing testing",
          "image": {
            "url": "http://127.0.0.1:1337/uploads/testing_photo_1506905925346_21bda4d32df4_3e7d976a76.jpg",
            "alt": "testing image",
            "width": 1200,
            "height": 800
          }
        }
      ]
    },
    {
      "id": 1,
      "label": "testing *testing*",
      "theme": "light",
      "stories": [
        {
          "title": "testing *testing*",
          "description": "testing testing",
          "image": {
            "url": "http://127.0.0.1:1337/uploads/testing_photo_1522202176988_66273c2fd55f_e8afb4bee4.jpg",
            "alt": "testing image",
            "width": 1200,
            "height": 800
          }
        },
        {
          "title": "testing testing",
          "description": "testing testing",
          "image": {
            "url": "http://127.0.0.1:1337/uploads/testing_photo_1523050854058_8df90110c9f1_5d3933d7b4.png",
            "alt": "testing image",
            "width": 800,
            "height": 600
          }
        },
        {
          "title": "testing testing",
          "description": "testing testing",
          "image": {
            "url": "http://127.0.0.1:1337/uploads/testing_photo_1541339907198_e08756dedf3f_6466a1a79a.jpg",
            "alt": "testing image",
            "width": 1200,
            "height": 800
          }
        }
      ]
    },
    {
      "id": 2,
      "label": "testing *testing*",
      "theme": "white",
      "stories": [
        {
          "title": "testing testing",
          "description": "testing testing",
          "image": {
            "url": "http://127.0.0.1:1337/uploads/testing_photo_1519389950473_47ba0277781c_004043fca3.jpg",
            "alt": "testing image",
            "width": 1200,
            "height": 800
          }
        },
        {
          "title": "testing testing",
          "description": "testing testing",
          "image": {
            "url": "http://127.0.0.1:1337/uploads/testing_photo_1497366216548_37526070297c_cc9da0bc35.jpg",
            "alt": "testing image",
            "width": 1200,
            "height": 801
          }
        },
        {
          "title": "testing testing",
          "description": "testing testing",
          "image": {
            "url": "http://127.0.0.1:1337/uploads/testing_photo_1531482615713_2afd69097998_6b6c6f5768.jpg",
            "alt": "testing image",
            "width": 1200,
            "height": 800
          }
        }
      ]
    }
  ],
  "articles": [
    {
      "titleAccent": "testing testing",
      "titleLead": "testing testing",
      "titleHighlight": "testing testing",
      "titleTail": "",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1523240795612_9a054b0db644_4024e78648.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      },
      "author": {
        "name": "testing testing",
        "role": "testing testing",
        "avatar": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1509062522246_3755977927d7_dd5c6e5f53.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 747
        }
      }
    },
    {
      "titleAccent": "testing testing",
      "titleLead": "testing testing",
      "titleHighlight": "testing testing",
      "titleTail": "testing testing",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1524178232363_1fb2b075b655_4844aedea4.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      },
      "author": {
        "name": "testing testing",
        "role": "testing testing",
        "avatar": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1503676260728_1c00da094a0b_1593d6bdd5.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 847
        }
      }
    },
    {
      "titleAccent": "testing testing",
      "titleLead": "testing testing",
      "titleHighlight": "testing testing",
      "titleTail": "",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1562774053_701939374585_d6c47bbbb9.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 786
      },
      "author": {
        "name": "testing testing",
        "role": "testing testing",
        "avatar": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1571260899304_425eee4c7efc_5ce92f65fd.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        }
      }
    },
    {
      "titleAccent": "testing testing",
      "titleLead": "testing testing",
      "titleHighlight": "testing testing",
      "titleTail": "",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1513258496099_48168024aec0_38d2e4fa8c.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      },
      "author": {
        "name": "testing testing",
        "role": "testing testing",
        "avatar": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1506905925346_21bda4d32df4_3e7d976a76.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        }
      }
    },
    {
      "titleAccent": "testing testing",
      "titleLead": "testing testing",
      "titleHighlight": "testing testing",
      "titleTail": "",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1517486808906_6ca8b3f04846_4d025ae68f.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 1552
      },
      "author": {
        "name": "testing testing",
        "role": "testing testing",
        "avatar": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1522202176988_66273c2fd55f_e8afb4bee4.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        }
      }
    }
  ]
};
