// Generated by the CU CMS. Do not edit.

import type { NewsSection } from '../../types/pages/home/news';

export type { NewsSection };

export const NEWS_SECTION: NewsSection = {
  "heading": "*Breaking Barriers*, Shaping Futures! Latest News & Updates",
  "tabs": [
    {
      "id": 0,
      "label": "See Latest *Signature Events*",
      "theme": "active",
      "stories": [
        {
          "title": "From Classroom to Nestlé: CU-UP MBA\nStudents Are Already Making Their *Mark*.",
          "description": "Chandigarh University, Uttar Pradesh (CU-UP) has added another milestone to its placement journey as ten MBA students from the Flagship, Marketing, and Business Analytics programs secured internships at Nestlé India, one of the country's leading FMCG companies.",
          "image": {
            "url": "http://127.0.0.1:1337/uploads/images_news_section_From_Class_to_Nestle_Preview_d51cd464de.webp",
            "alt": "Campus Tank Uttar Pradesh",
            "width": 390,
            "height": 220
          }
        },
        {
          "title": "CU-UP's 21 MBA Students Land Early\nInternships at *Berger Paints*.",
          "description": "Twenty-one MBA students secured internships at Berger Paints, while two additional students earned individual internship offers from Vodafone and Lenovo, reflecting Chandigarh University, Uttar Pradesh's robust placement ecosystem.",
          "image": {
            "url": "http://127.0.0.1:1337/uploads/images_news_section_Berger_paint_preview_d6256fffa3.webp",
            "alt": "Global Academic Collaboration",
            "width": 350,
            "height": 270
          }
        },
        {
          "title": "CU-UP Launches Centre of Excellence\nfor *Smart Healthcare*.",
          "description": "Chandigarh University, Uttar Pradesh launched its Centre of Excellence in Smart Healthcare during the symposium on 'AI in Governance: Policy, Practice, and People-Centric Transformation', reinforcing its commitment to AI-driven healthcare innovation and ethical AI education.",
          "image": {
            "url": "http://127.0.0.1:1337/uploads/images_news_section_cu_up_launches_coe_in_smart_healthcare_centre_67c795e652.webp",
            "alt": "Next-Gen Tech Advancements",
            "width": 390,
            "height": 220
          }
        },
        {
          "title": "CU-UP Talent Shines Early:\nMBA Student Selected for *Vodafone Internship*.",
          "description": "Continuing its strong placement record, Chandigarh University, Uttar Pradesh celebrated the achievement of MBA student Shreya Bajpai, who secured an internship with Vodafone during the first year of her program.",
          "image": {
            "url": "http://127.0.0.1:1337/uploads/images_news_section_cu_up_talent_shines_early_3b59ffea49.webp",
            "alt": "Global Academic Collaboration",
            "width": 780,
            "height": 440
          }
        }
      ]
    },
    {
      "id": 1,
      "label": "See Latest *Celebrity News*",
      "theme": "light",
      "stories": [
        {
          "title": "Cricketer Kuldeep Yadav Visits CU-UP,\nLaunches Next-Gen Sports *Scholarship*",
          "description": "Indian international cricketer Kuldeep Yadav visited Chandigarh University, Uttar Pradesh to interact with young sports achievers and officially launch the prestigious CU Sports Scholarship program.",
          "image": {
            "url": "http://127.0.0.1:1337/uploads/images_Hackathon_2_2c7347399a.webp",
            "alt": "Celebrity Sports Guest",
            "width": 367,
            "height": 206
          }
        },
        {
          "title": "Chandigarh University, Uttar Pradesh - India’s First AI-Augmented Multidisciplinary Campus Inaugurated by Hon’ble Chief Minister of Uttar Pradesh, Yogi Adityanath.",
          "description": "A historic day unfolded in Uttar Pradesh, as Chandigarh University, Uttar Pradesh, opened its doors to its first batch of students with a grand and historic inauguration by the Honorable Chief Minister of Uttar Pradesh, Yogi Adityanath.",
          "image": {
            "url": "http://127.0.0.1:1337/uploads/images_news_section_investment_2ff8b71e2e.webp",
            "alt": "Bollywood Star Guest",
            "width": 2400,
            "height": 1600
          }
        },
        {
          "title": "Chandigarh University Uttar Pradesh Hosts ‘UP AI Synergy Conclave 2025’, Brings Key Stakeholders Together to Shape India’s AI Future",
          "description": "Uttar Pradesh is on a mission to become a global AI and IT hub, aligning with Prime Minister Narendra Modi’s vision for India’s AI leadership.",
          "image": {
            "url": "http://127.0.0.1:1337/uploads/images_news_section_UP_AI_Synergy_Conclave_news_eded53e4ba.webp",
            "alt": "Celebrity Tech Guest",
            "width": 610,
            "height": 407
          }
        }
      ]
    },
    {
      "id": 2,
      "label": "See Latest *Academic Archives*",
      "theme": "white",
      "stories": [
        {
          "title": "Chandigarh University, Uttar Pradesh, Hosts Agentic AI Founders’ Hackathon - ‘0 to 1: Hack with Uttar Pradesh’",
          "description": "India’s first AI-augmented multidisciplinary university, Chandigarh University, Uttar Pradesh, hosted a two-day agentic AI founders’ hackathon - ‘0 to 1: Hack with Uttar Pradesh’, organized by its Technology Business Incubator (TBI) and Student Innovation Cell (IEDC).",
          "image": {
            "url": "http://127.0.0.1:1337/uploads/images_Group_1000007997_310eaa4e16.webp",
            "alt": "Academic COE Launch",
            "width": 367,
            "height": 206
          }
        },
        {
          "title": "CU Uttar Pradesh Brings Academia, Industry, and Students Together on Engineers’ Day",
          "description": "Chandigarh University, Uttar Pradesh, India’s first AI-augmented multidisciplinary university, celebrated Engineer’s Day with a series of profound sessions, industry-academia interactions, and competitive events designed to inspire innovation among students & to send a message that engineering is not only about structures and systems, but about building a brighter tomorrow.",
          "image": {
            "url": "http://127.0.0.1:1337/uploads/images_news_section_engineers_day_2025_at_chandigarh_university_up_dd4d680e9e.webp",
            "alt": "Academic MBA Internships",
            "width": 600,
            "height": 400
          }
        },
        {
          "title": "Microsoft Organizes AI Bootcamp at Chandigarh University, Uttar Pradesh. MoU Signed Between CU-UP And Microsoft.",
          "description": "India’s First AI-Augmented Multidisciplinary University, Chandigarh University, Uttar Pradesh, steps towards building an AI-Driven India by hosting the groundbreaking ‘Unnati AI’ event. With Microsoft’s first-ever AI bootcamp, marking a historic milestone in CU-UP’s mission to build a future-ready, AI-skilled-based education & workforce.",
          "image": {
            "url": "http://127.0.0.1:1337/uploads/images_news_section_news_img9_4042a06e2a.webp",
            "alt": "Academic MBA Internships Berger",
            "width": 330,
            "height": 220
          }
        }
      ]
    }
  ],
  "articles": [
    {
      "titleAccent": "How to Join",
      "titleLead": "B.Des Interior Design After 12th:",
      "titleHighlight": "Step-by-Step Guide",
      "titleTail": "",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/images_news_section_how_to_join_b_des_interior_design_after_12th_complete_guide_656beff095.webp",
        "alt": "",
        "width": 892,
        "height": 446
      },
      "author": {
        "name": "CU-UP",
        "role": "Media Team",
        "avatar": {
          "url": "http://127.0.0.1:1337/uploads/images_herosectionmodal_c3855ef6ea.webp",
          "alt": "CU-UP",
          "width": 34,
          "height": 34
        }
      }
    },
    {
      "titleAccent": "Best B.Tech Civil Engineering",
      "titleLead": "Colleges in UP:",
      "titleHighlight": "Ranking, Fees & Career Scope",
      "titleTail": "in 2026",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/images_news_section_Best_B_Tech_CE_Colleges_in_UP_preview_c5486467e3.webp",
        "alt": "",
        "width": 350,
        "height": 270
      },
      "author": {
        "name": "CU-UP",
        "role": "Media Team",
        "avatar": {
          "url": "http://127.0.0.1:1337/uploads/images_herosectionmodal_c3855ef6ea.webp",
          "alt": "CU-UP",
          "width": 34,
          "height": 34
        }
      }
    },
    {
      "titleAccent": "Full Guide",
      "titleLead": "on how to check results &",
      "titleHighlight": "CUET 2026 Expected Cutoffs",
      "titleTail": "",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/images_news_section_cuet_2026_expected_cutoffs_preview_293e746c39.webp",
        "alt": "",
        "width": 892,
        "height": 446
      },
      "author": {
        "name": "CU-UP",
        "role": "Media Team",
        "avatar": {
          "url": "http://127.0.0.1:1337/uploads/images_herosectionmodal_c3855ef6ea.webp",
          "alt": "CU-UP",
          "width": 34,
          "height": 34
        }
      }
    },
    {
      "titleAccent": "Best Pharmacy Colleges",
      "titleLead": "in Lucknow After 12th 2026:",
      "titleHighlight": "Fees, Eligibility & Career Scope",
      "titleTail": "",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/images_news_section_Best_Pharmacy_Colleges_preview_774a9b2ed0.webp",
        "alt": "",
        "width": 892,
        "height": 446
      },
      "author": {
        "name": "CU-UP",
        "role": "Media Team",
        "avatar": {
          "url": "http://127.0.0.1:1337/uploads/images_herosectionmodal_c3855ef6ea.webp",
          "alt": "CU-UP",
          "width": 34,
          "height": 34
        }
      }
    },
    {
      "titleAccent": "Top Engineering Colleges",
      "titleLead": "in Lucknow Offering",
      "titleHighlight": "Aerospace Engineering",
      "titleTail": "",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/images_news_section_Top_Aerospace_Engineering_Colleges_preview_57c55ad322.webp",
        "alt": "",
        "width": 370,
        "height": 250
      },
      "author": {
        "name": "CU-UP",
        "role": "Media Team",
        "avatar": {
          "url": "http://127.0.0.1:1337/uploads/images_herosectionmodal_c3855ef6ea.webp",
          "alt": "CU-UP",
          "width": 34,
          "height": 34
        }
      }
    }
  ]
};
