// Generated by the CU CMS. Do not edit.

import type { PlacementSection } from '../../types/pages/home/placement';

export type { PlacementSection };

export const PLACEMENT_SECTION: PlacementSection = {
  "heading": "testing *testing*",
  "subheading": "testing testing",
  "ctaLabel": "testing testing",
  "alumniHeading": "testing testing",
  "alumniSubheading": "testing testing",
  "storiesHeading": "testing *testing*",
  "storiesCtaLabel": "testing testing",
  "networkHeading": "testing *testing*",
  "recruiters": [
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1524178232363_1fb2b075b655_4844aedea4.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1562774053_701939374585_d6c47bbbb9.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 786
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1513258496099_48168024aec0_38d2e4fa8c.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1517486808906_6ca8b3f04846_4d025ae68f.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 1552
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1509062522246_3755977927d7_dd5c6e5f53.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 747
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1503676260728_1c00da094a0b_1593d6bdd5.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 847
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1571260899304_425eee4c7efc_5ce92f65fd.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1506905925346_21bda4d32df4_3e7d976a76.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1522202176988_66273c2fd55f_e8afb4bee4.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1523050854058_8df90110c9f1_5d3933d7b4.png",
        "alt": "testing image",
        "width": 800,
        "height": 600
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1541339907198_e08756dedf3f_6466a1a79a.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1519389950473_47ba0277781c_004043fca3.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1497366216548_37526070297c_cc9da0bc35.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 801
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1531482615713_2afd69097998_6b6c6f5768.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1523240795612_9a054b0db644_4024e78648.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1524178232363_1fb2b075b655_4844aedea4.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1562774053_701939374585_d6c47bbbb9.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 786
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1513258496099_48168024aec0_38d2e4fa8c.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1517486808906_6ca8b3f04846_4d025ae68f.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 1552
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1509062522246_3755977927d7_dd5c6e5f53.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 747
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1503676260728_1c00da094a0b_1593d6bdd5.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 847
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1571260899304_425eee4c7efc_5ce92f65fd.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1506905925346_21bda4d32df4_3e7d976a76.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1522202176988_66273c2fd55f_e8afb4bee4.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1523050854058_8df90110c9f1_5d3933d7b4.png",
        "alt": "testing image",
        "width": 800,
        "height": 600
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1541339907198_e08756dedf3f_6466a1a79a.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1519389950473_47ba0277781c_004043fca3.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1497366216548_37526070297c_cc9da0bc35.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 801
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1531482615713_2afd69097998_6b6c6f5768.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1523240795612_9a054b0db644_4024e78648.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1524178232363_1fb2b075b655_4844aedea4.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1562774053_701939374585_d6c47bbbb9.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 786
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1513258496099_48168024aec0_38d2e4fa8c.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1517486808906_6ca8b3f04846_4d025ae68f.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 1552
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1509062522246_3755977927d7_dd5c6e5f53.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 747
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1503676260728_1c00da094a0b_1593d6bdd5.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 847
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1571260899304_425eee4c7efc_5ce92f65fd.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1506905925346_21bda4d32df4_3e7d976a76.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1522202176988_66273c2fd55f_e8afb4bee4.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    }
  ],
  "metrics": [
    {
      "value": "0000",
      "label": "testing testing"
    },
    {
      "value": "0000",
      "label": "testing testing"
    },
    {
      "value": "0000",
      "label": "testing testing"
    },
    {
      "value": "0000",
      "label": "testing testing"
    }
  ],
  "years": [
    {
      "year": "0000",
      "companiesVisited": 0,
      "studentsPlaced": 0,
      "highestPackage": "0000",
      "highestPackageIntl": null,
      "packages": [
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        }
      ]
    },
    {
      "year": "0000",
      "companiesVisited": 0,
      "studentsPlaced": 0,
      "highestPackage": "0000",
      "highestPackageIntl": null,
      "packages": [
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        }
      ]
    },
    {
      "year": "0000",
      "companiesVisited": 0,
      "studentsPlaced": 0,
      "highestPackage": "0000",
      "highestPackageIntl": null,
      "packages": [
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        }
      ]
    },
    {
      "year": "0000",
      "companiesVisited": 0,
      "studentsPlaced": 0,
      "highestPackage": "0000",
      "highestPackageIntl": null,
      "packages": [
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        }
      ]
    },
    {
      "year": "0000",
      "companiesVisited": 0,
      "studentsPlaced": 0,
      "highestPackage": "0000",
      "highestPackageIntl": null,
      "packages": [
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        }
      ]
    },
    {
      "year": "0000",
      "companiesVisited": 0,
      "studentsPlaced": 0,
      "highestPackage": "0000",
      "highestPackageIntl": null,
      "packages": [
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        }
      ]
    },
    {
      "year": "0000",
      "companiesVisited": 0,
      "studentsPlaced": 0,
      "highestPackage": "0000",
      "highestPackageIntl": null,
      "packages": [
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        }
      ]
    },
    {
      "year": "0000",
      "companiesVisited": 0,
      "studentsPlaced": 0,
      "highestPackage": "0000",
      "highestPackageIntl": null,
      "packages": [
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        }
      ]
    },
    {
      "year": "0000",
      "companiesVisited": 0,
      "studentsPlaced": 0,
      "highestPackage": "0000",
      "highestPackageIntl": "0000",
      "packages": [
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        }
      ]
    },
    {
      "year": "0000",
      "companiesVisited": 0,
      "studentsPlaced": 0,
      "highestPackage": "0000",
      "highestPackageIntl": "0000",
      "packages": [
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        }
      ]
    },
    {
      "year": "0000",
      "companiesVisited": 0,
      "studentsPlaced": 0,
      "highestPackage": "0000",
      "highestPackageIntl": "0000",
      "packages": [
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        }
      ]
    },
    {
      "year": "0000",
      "companiesVisited": 0,
      "studentsPlaced": 0,
      "highestPackage": "0000",
      "highestPackageIntl": "0000",
      "packages": [
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        }
      ]
    },
    {
      "year": "0000",
      "companiesVisited": 0,
      "studentsPlaced": 0,
      "highestPackage": "0000",
      "highestPackageIntl": "0000",
      "packages": [
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        },
        {
          "name": "0000",
          "value": 0
        }
      ]
    }
  ],
  "achievers": [
    {
      "name": "testing testing",
      "designation": "testing testing",
      "placedIn": "testing testing",
      "salaryValue": "0000",
      "salaryUnit": "testing te",
      "companyLogo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1523050854058_8df90110c9f1_5d3933d7b4.png",
        "alt": "testing image",
        "width": 800,
        "height": 600
      },
      "personImage": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1497366216548_37526070297c_cc9da0bc35.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 801
      }
    },
    {
      "name": "testing testing",
      "designation": "testing testing",
      "placedIn": "testing testing",
      "salaryValue": "0000",
      "salaryUnit": "testing te",
      "companyLogo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1541339907198_e08756dedf3f_6466a1a79a.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      },
      "personImage": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1531482615713_2afd69097998_6b6c6f5768.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "designation": "testing testing",
      "placedIn": "testing testing",
      "salaryValue": "0000",
      "salaryUnit": "testing te",
      "companyLogo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1519389950473_47ba0277781c_004043fca3.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      },
      "personImage": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1523240795612_9a054b0db644_4024e78648.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    }
  ],
  "stories": {
    "Engineering": [
      {
        "id": 1,
        "name": "testing testing",
        "designation": "testing testing",
        "companyImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1524178232363_1fb2b075b655_4844aedea4.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "personImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1524178232363_1fb2b075b655_4844aedea4.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "successfulSessions": 0
      },
      {
        "id": 2,
        "name": "testing testing",
        "designation": "testing testing",
        "companyImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1562774053_701939374585_d6c47bbbb9.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 786
        },
        "personImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1562774053_701939374585_d6c47bbbb9.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 786
        },
        "successfulSessions": 0
      },
      {
        "id": 3,
        "name": "testing testing",
        "designation": "testing testing",
        "companyImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1513258496099_48168024aec0_38d2e4fa8c.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "personImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1513258496099_48168024aec0_38d2e4fa8c.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "successfulSessions": 0
      },
      {
        "id": 4,
        "name": "testing testing",
        "designation": "testing testing",
        "companyImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1517486808906_6ca8b3f04846_4d025ae68f.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 1552
        },
        "personImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1517486808906_6ca8b3f04846_4d025ae68f.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 1552
        },
        "successfulSessions": 0
      },
      {
        "id": 5,
        "name": "testing testing",
        "designation": "testing testing",
        "companyImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1509062522246_3755977927d7_dd5c6e5f53.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 747
        },
        "personImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1509062522246_3755977927d7_dd5c6e5f53.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 747
        },
        "successfulSessions": 0
      }
    ],
    "Business Management": [
      {
        "id": 1,
        "name": "testing testing",
        "designation": "testing testing",
        "companyImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1503676260728_1c00da094a0b_1593d6bdd5.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 847
        },
        "personImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1503676260728_1c00da094a0b_1593d6bdd5.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 847
        },
        "successfulSessions": 0
      },
      {
        "id": 2,
        "name": "testing testing",
        "designation": "testing testing",
        "companyImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1571260899304_425eee4c7efc_5ce92f65fd.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "personImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1571260899304_425eee4c7efc_5ce92f65fd.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "successfulSessions": 0
      },
      {
        "id": 3,
        "name": "testing testing",
        "designation": "testing testing",
        "companyImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1506905925346_21bda4d32df4_3e7d976a76.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "personImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1506905925346_21bda4d32df4_3e7d976a76.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "successfulSessions": 0
      },
      {
        "id": 4,
        "name": "testing testing",
        "designation": "testing testing",
        "companyImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1522202176988_66273c2fd55f_e8afb4bee4.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "personImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1522202176988_66273c2fd55f_e8afb4bee4.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "successfulSessions": 0
      },
      {
        "id": 5,
        "name": "testing testing",
        "designation": "testing testing",
        "companyImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1523050854058_8df90110c9f1_5d3933d7b4.png",
          "alt": "testing image",
          "width": 800,
          "height": 600
        },
        "personImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1523050854058_8df90110c9f1_5d3933d7b4.png",
          "alt": "testing image",
          "width": 800,
          "height": 600
        },
        "successfulSessions": 0
      }
    ],
    "Marketing": [
      {
        "id": 1,
        "name": "testing testing",
        "designation": "testing testing",
        "companyImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1541339907198_e08756dedf3f_6466a1a79a.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "personImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1541339907198_e08756dedf3f_6466a1a79a.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "successfulSessions": 0
      },
      {
        "id": 2,
        "name": "testing testing",
        "designation": "testing testing",
        "companyImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1519389950473_47ba0277781c_004043fca3.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "personImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1519389950473_47ba0277781c_004043fca3.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "successfulSessions": 0
      },
      {
        "id": 3,
        "name": "testing testing",
        "designation": "testing testing",
        "companyImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1497366216548_37526070297c_cc9da0bc35.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 801
        },
        "personImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1497366216548_37526070297c_cc9da0bc35.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 801
        },
        "successfulSessions": 0
      },
      {
        "id": 4,
        "name": "testing testing",
        "designation": "testing testing",
        "companyImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1531482615713_2afd69097998_6b6c6f5768.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "personImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1531482615713_2afd69097998_6b6c6f5768.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "successfulSessions": 0
      },
      {
        "id": 5,
        "name": "testing testing",
        "designation": "testing testing",
        "companyImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1523240795612_9a054b0db644_4024e78648.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "personImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1523240795612_9a054b0db644_4024e78648.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "successfulSessions": 0
      }
    ],
    "Applied Sciences": [
      {
        "id": 1,
        "name": "testing testing",
        "designation": "testing testing",
        "companyImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1524178232363_1fb2b075b655_4844aedea4.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "personImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1524178232363_1fb2b075b655_4844aedea4.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "successfulSessions": 0
      },
      {
        "id": 2,
        "name": "testing testing",
        "designation": "testing testing",
        "companyImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1562774053_701939374585_d6c47bbbb9.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 786
        },
        "personImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1562774053_701939374585_d6c47bbbb9.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 786
        },
        "successfulSessions": 0
      },
      {
        "id": 3,
        "name": "testing testing",
        "designation": "testing testing",
        "companyImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1513258496099_48168024aec0_38d2e4fa8c.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "personImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1513258496099_48168024aec0_38d2e4fa8c.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "successfulSessions": 0
      },
      {
        "id": 4,
        "name": "testing testing",
        "designation": "testing testing",
        "companyImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1517486808906_6ca8b3f04846_4d025ae68f.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 1552
        },
        "personImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1517486808906_6ca8b3f04846_4d025ae68f.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 1552
        },
        "successfulSessions": 0
      },
      {
        "id": 5,
        "name": "testing testing",
        "designation": "testing testing",
        "companyImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1509062522246_3755977927d7_dd5c6e5f53.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 747
        },
        "personImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1509062522246_3755977927d7_dd5c6e5f53.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 747
        },
        "successfulSessions": 0
      }
    ],
    "Hotel Management": [
      {
        "id": 1,
        "name": "testing testing",
        "designation": "testing testing",
        "companyImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1503676260728_1c00da094a0b_1593d6bdd5.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 847
        },
        "personImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1503676260728_1c00da094a0b_1593d6bdd5.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 847
        },
        "successfulSessions": 0
      },
      {
        "id": 2,
        "name": "testing testing",
        "designation": "testing testing",
        "companyImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1571260899304_425eee4c7efc_5ce92f65fd.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "personImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1571260899304_425eee4c7efc_5ce92f65fd.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "successfulSessions": 0
      },
      {
        "id": 3,
        "name": "testing testing",
        "designation": "testing testing",
        "companyImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1506905925346_21bda4d32df4_3e7d976a76.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "personImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1506905925346_21bda4d32df4_3e7d976a76.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "successfulSessions": 0
      },
      {
        "id": 4,
        "name": "testing testing",
        "designation": "testing testing",
        "companyImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1522202176988_66273c2fd55f_e8afb4bee4.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "personImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1522202176988_66273c2fd55f_e8afb4bee4.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "successfulSessions": 0
      },
      {
        "id": 5,
        "name": "testing testing",
        "designation": "testing testing",
        "companyImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1523050854058_8df90110c9f1_5d3933d7b4.png",
          "alt": "testing image",
          "width": 800,
          "height": 600
        },
        "personImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1523050854058_8df90110c9f1_5d3933d7b4.png",
          "alt": "testing image",
          "width": 800,
          "height": 600
        },
        "successfulSessions": 0
      }
    ],
    "Pharma": [
      {
        "id": 1,
        "name": "testing testing",
        "designation": "testing testing",
        "companyImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1541339907198_e08756dedf3f_6466a1a79a.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "personImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1541339907198_e08756dedf3f_6466a1a79a.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "successfulSessions": 0
      },
      {
        "id": 2,
        "name": "testing testing",
        "designation": "testing testing",
        "companyImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1519389950473_47ba0277781c_004043fca3.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "personImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1519389950473_47ba0277781c_004043fca3.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "successfulSessions": 0
      },
      {
        "id": 3,
        "name": "testing testing",
        "designation": "testing testing",
        "companyImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1497366216548_37526070297c_cc9da0bc35.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 801
        },
        "personImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1497366216548_37526070297c_cc9da0bc35.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 801
        },
        "successfulSessions": 0
      },
      {
        "id": 4,
        "name": "testing testing",
        "designation": "testing testing",
        "companyImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1531482615713_2afd69097998_6b6c6f5768.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "personImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1531482615713_2afd69097998_6b6c6f5768.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "successfulSessions": 0
      },
      {
        "id": 5,
        "name": "testing testing",
        "designation": "testing testing",
        "companyImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1523240795612_9a054b0db644_4024e78648.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "personImage": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1523240795612_9a054b0db644_4024e78648.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        },
        "successfulSessions": 0
      }
    ]
  }
};
