// Generated by the CU CMS. Do not edit.

import type { TestimonialSection } from '../../types/pages/home/testimonials';

export type { TestimonialSection };

export const TESTIMONIAL_SECTION: TestimonialSection = {
  "heading": "testing *testing*",
  "testimonials": [
    {
      "id": "1",
      "title": "testing testing",
      "videoLink": "https://www.youtube.com/shorts/VVIlL3j3-XQ",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1513258496099_48168024aec0_38d2e4fa8c.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "id": "2",
      "title": "testing testing",
      "videoLink": "https://www.youtube.com/shorts/oc4_vS5KO7g",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1517486808906_6ca8b3f04846_4d025ae68f.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 1552
      }
    },
    {
      "id": "3",
      "title": "testing testing",
      "videoLink": "https://www.youtube.com/shorts/dacn9B4u11c",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1509062522246_3755977927d7_dd5c6e5f53.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 747
      }
    },
    {
      "id": "4",
      "title": "testing testing",
      "videoLink": "https://www.youtube.com/shorts/gNoXGW8IwjI",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1503676260728_1c00da094a0b_1593d6bdd5.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 847
      }
    },
    {
      "id": "5",
      "title": "testing testing",
      "videoLink": "https://www.youtube.com/shorts/OrG1H355sQI",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1571260899304_425eee4c7efc_5ce92f65fd.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "id": "6",
      "title": "testing testing",
      "videoLink": "https://www.youtube.com/shorts/kPS8vdwNEhc",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1506905925346_21bda4d32df4_3e7d976a76.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "id": "7",
      "title": "testing testing",
      "videoLink": "https://www.youtube.com/shorts/O7tx4o8rkV8",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1522202176988_66273c2fd55f_e8afb4bee4.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "id": "8",
      "title": "testing testing",
      "videoLink": "https://www.youtube.com/shorts/wMQyGZJxPBo",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1523050854058_8df90110c9f1_5d3933d7b4.png",
        "alt": "testing image",
        "width": 800,
        "height": 600
      }
    },
    {
      "id": "9",
      "title": "testing testing",
      "videoLink": "https://www.youtube.com/shorts/zxcTBzrZySo",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1541339907198_e08756dedf3f_6466a1a79a.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "id": "10",
      "title": "testing testing",
      "videoLink": "https://www.youtube.com/shorts/Q416qnLQS1Q",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1519389950473_47ba0277781c_004043fca3.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "id": "11",
      "title": "testing testing",
      "videoLink": "https://www.youtube.com/shorts/gVnchHzZdEU",
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1497366216548_37526070297c_cc9da0bc35.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 801
      }
    }
  ],
  "achieversHeading": "testing *testing*",
  "achievers": [
    {
      "id": "1",
      "videoTitle": "testing testing",
      "videoLink": "https://www.youtube.com/embed/neHlU694OTI?si=WP8yBauNLrtWS8nH",
      "category": "Stories"
    },
    {
      "id": "2",
      "videoTitle": "testing testing",
      "videoLink": "https://www.youtube.com/embed/YnZHx2p0ebI?si=590_O8mhVorbZdm3",
      "category": "Shorts"
    },
    {
      "id": "3",
      "videoTitle": "testing testing",
      "videoLink": "https://www.youtube.com/embed/YnZHx2p0ebI?si=590_O8mhVorbZdm3",
      "category": "Stories"
    },
    {
      "id": "4",
      "videoTitle": "testing testing",
      "videoLink": "https://www.youtube.com/embed/4I4lVHC73ws?si=K49tvZdDMUBz8vl2",
      "category": "Placement"
    },
    {
      "id": "5",
      "videoTitle": "testing testing",
      "videoLink": "https://www.youtube.com/embed/gu91b9abGl8?si=W2JN6vpB1PzAyCDo",
      "category": "Cultural"
    },
    {
      "id": "6",
      "videoTitle": "testing testing",
      "videoLink": "https://www.youtube.com/embed/4I4lVHC73ws?si=K49tvZdDMUBz8vl2",
      "category": "Stories"
    },
    {
      "id": "7",
      "videoTitle": "testing testing",
      "videoLink": "https://www.youtube.com/embed/7ETwwidTik0",
      "category": "Stories"
    },
    {
      "id": "8",
      "videoTitle": "testing testing",
      "videoLink": "https://www.youtube.com/embed/BHZ_B_ZU1S8",
      "category": "Shorts"
    },
    {
      "id": "9",
      "videoTitle": "testing testing",
      "videoLink": "https://www.youtube.com/embed/oQi2w3kBXFQ",
      "category": "Shorts"
    },
    {
      "id": "10",
      "videoTitle": "testing testing",
      "videoLink": "https://www.youtube.com/embed/XRq5SR09V3g",
      "category": "Stories"
    }
  ],
  "reels": [
    {
      "id": "1",
      "title": "testing testing",
      "name": "testing testing",
      "url": "https://www.instagram.com/reel/DapKpUzJjZI/",
      "poster": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1531482615713_2afd69097998_6b6c6f5768.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "id": "2",
      "title": "testing testing",
      "name": "testing testing",
      "url": "https://www.instagram.com/reel/DaAL8uUpIMy/",
      "poster": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1523240795612_9a054b0db644_4024e78648.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "id": "3",
      "title": "testing testing",
      "name": "testing testing",
      "url": "https://www.instagram.com/reel/DZ1zsqtpQbe/",
      "poster": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1524178232363_1fb2b075b655_4844aedea4.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "id": "4",
      "title": "testing testing",
      "name": "testing testing",
      "url": "https://www.instagram.com/reel/DX52JQDpmD7/",
      "poster": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1562774053_701939374585_d6c47bbbb9.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 786
      }
    },
    {
      "id": "5",
      "title": "testing testing",
      "name": "testing testing",
      "url": "https://www.instagram.com/reel/DXVwQouibuE/",
      "poster": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1513258496099_48168024aec0_38d2e4fa8c.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "id": "6",
      "title": "testing testing",
      "name": "testing testing",
      "url": "https://www.instagram.com/reel/DW58feJiV-M/",
      "poster": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1517486808906_6ca8b3f04846_4d025ae68f.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 1552
      }
    }
  ],
  "quotes": {
    "Alumni": [
      {
        "id": "1",
        "quote": "testing testing",
        "name": "testing testing",
        "role": "testing testing",
        "affiliation": "testing testing",
        "photo": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1509062522246_3755977927d7_dd5c6e5f53.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 747
        }
      },
      {
        "id": "2",
        "quote": "testing testing",
        "name": "testing testing",
        "role": "testing testing",
        "affiliation": "testing testing",
        "photo": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1503676260728_1c00da094a0b_1593d6bdd5.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 847
        }
      },
      {
        "id": "3",
        "quote": "testing testing",
        "name": "testing testing",
        "role": "testing testing",
        "affiliation": "testing testing",
        "photo": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1571260899304_425eee4c7efc_5ce92f65fd.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        }
      },
      {
        "id": "4",
        "quote": "testing testing",
        "name": "testing testing",
        "role": "testing testing",
        "affiliation": "testing testing",
        "photo": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1506905925346_21bda4d32df4_3e7d976a76.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        }
      },
      {
        "id": "5",
        "quote": "testing testing",
        "name": "testing testing",
        "role": "testing testing",
        "affiliation": "testing testing",
        "photo": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1522202176988_66273c2fd55f_e8afb4bee4.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        }
      },
      {
        "id": "6",
        "quote": "testing testing",
        "name": "testing testing",
        "role": "testing testing",
        "affiliation": "testing testing",
        "photo": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1523050854058_8df90110c9f1_5d3933d7b4.png",
          "alt": "testing image",
          "width": 800,
          "height": 600
        }
      },
      {
        "id": "7",
        "quote": "testing testing",
        "name": "testing testing",
        "role": "testing testing",
        "affiliation": "testing testing",
        "photo": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1541339907198_e08756dedf3f_6466a1a79a.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        }
      },
      {
        "id": "8",
        "quote": "testing testing",
        "name": "testing testing",
        "role": "testing testing",
        "affiliation": "testing testing",
        "photo": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1519389950473_47ba0277781c_004043fca3.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        }
      },
      {
        "id": "13",
        "quote": "testing testing",
        "name": "testing testing",
        "role": "testing testing",
        "affiliation": "testing testing",
        "photo": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1562774053_701939374585_d6c47bbbb9.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 786
        }
      },
      {
        "id": "14",
        "quote": "testing testing",
        "name": "testing testing",
        "role": "testing testing",
        "affiliation": "testing testing",
        "photo": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1513258496099_48168024aec0_38d2e4fa8c.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        }
      },
      {
        "id": "15",
        "quote": "testing testing",
        "name": "testing testing",
        "role": "testing testing",
        "affiliation": "testing testing",
        "photo": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1517486808906_6ca8b3f04846_4d025ae68f.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 1552
        }
      },
      {
        "id": "16",
        "quote": "testing testing",
        "name": "testing testing",
        "role": "testing testing",
        "affiliation": "testing testing",
        "photo": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1509062522246_3755977927d7_dd5c6e5f53.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 747
        }
      },
      {
        "id": "25",
        "quote": "testing testing",
        "name": "testing testing",
        "role": "testing testing",
        "affiliation": "testing testing",
        "photo": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1531482615713_2afd69097998_6b6c6f5768.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        }
      },
      {
        "id": "26",
        "quote": "testing testing",
        "name": "testing testing",
        "role": "testing testing",
        "affiliation": "testing testing",
        "photo": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1523240795612_9a054b0db644_4024e78648.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        }
      },
      {
        "id": "27",
        "quote": "testing testing",
        "name": "testing testing",
        "role": "testing testing",
        "affiliation": "testing testing",
        "photo": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1524178232363_1fb2b075b655_4844aedea4.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        }
      },
      {
        "id": "28",
        "quote": "testing testing",
        "name": "testing testing",
        "role": "testing testing",
        "affiliation": "testing testing",
        "photo": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1562774053_701939374585_d6c47bbbb9.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 786
        }
      },
      {
        "id": "29",
        "quote": "testing testing",
        "name": "testing testing",
        "role": "testing testing",
        "affiliation": "testing testing",
        "photo": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1513258496099_48168024aec0_38d2e4fa8c.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        }
      },
      {
        "id": "30",
        "quote": "testing testing",
        "name": "testing testing",
        "role": "testing testing",
        "affiliation": "testing testing",
        "photo": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1517486808906_6ca8b3f04846_4d025ae68f.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 1552
        }
      },
      {
        "id": "31",
        "quote": "testing testing",
        "name": "testing testing",
        "role": "testing testing",
        "affiliation": "testing testing",
        "photo": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1509062522246_3755977927d7_dd5c6e5f53.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 747
        }
      }
    ],
    "Clubs": [
      {
        "id": "9",
        "quote": "testing testing",
        "name": "testing testing",
        "role": "testing testing",
        "affiliation": "testing testing",
        "photo": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1497366216548_37526070297c_cc9da0bc35.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 801
        }
      },
      {
        "id": "10",
        "quote": "testing testing",
        "name": "testing testing",
        "role": "testing testing",
        "affiliation": "testing testing",
        "photo": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1531482615713_2afd69097998_6b6c6f5768.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        }
      },
      {
        "id": "17",
        "quote": "testing testing",
        "name": "testing testing",
        "role": "testing testing",
        "affiliation": "testing testing",
        "photo": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1503676260728_1c00da094a0b_1593d6bdd5.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 847
        }
      },
      {
        "id": "18",
        "quote": "testing testing",
        "name": "testing testing",
        "role": "testing testing",
        "affiliation": "testing testing",
        "photo": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1571260899304_425eee4c7efc_5ce92f65fd.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        }
      },
      {
        "id": "19",
        "quote": "testing testing",
        "name": "testing testing",
        "role": "testing testing",
        "affiliation": "testing testing",
        "photo": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1506905925346_21bda4d32df4_3e7d976a76.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        }
      },
      {
        "id": "20",
        "quote": "testing testing",
        "name": "testing testing",
        "role": "testing testing",
        "affiliation": "testing testing",
        "photo": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1522202176988_66273c2fd55f_e8afb4bee4.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        }
      }
    ],
    "Guests": [
      {
        "id": "11",
        "quote": "testing testing",
        "name": "testing testing",
        "role": "testing testing",
        "affiliation": "testing testing",
        "photo": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1523240795612_9a054b0db644_4024e78648.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        }
      },
      {
        "id": "12",
        "quote": "testing testing",
        "name": "testing testing",
        "role": "testing testing",
        "affiliation": "testing testing",
        "photo": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1524178232363_1fb2b075b655_4844aedea4.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        }
      },
      {
        "id": "21",
        "quote": "testing testing",
        "name": "testing testing",
        "role": "testing testing",
        "affiliation": "testing testing",
        "photo": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1523050854058_8df90110c9f1_5d3933d7b4.png",
          "alt": "testing image",
          "width": 800,
          "height": 600
        }
      },
      {
        "id": "22",
        "quote": "testing testing",
        "name": "testing testing",
        "role": "testing testing",
        "affiliation": "testing testing",
        "photo": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1541339907198_e08756dedf3f_6466a1a79a.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        }
      },
      {
        "id": "23",
        "quote": "testing testing",
        "name": "testing testing",
        "role": "testing testing",
        "affiliation": "testing testing",
        "photo": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1519389950473_47ba0277781c_004043fca3.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 800
        }
      },
      {
        "id": "24",
        "quote": "testing testing",
        "name": "testing testing",
        "role": "testing testing",
        "affiliation": "testing testing",
        "photo": {
          "url": "http://127.0.0.1:1337/uploads/testing_photo_1497366216548_37526070297c_cc9da0bc35.jpg",
          "alt": "testing image",
          "width": 1200,
          "height": 801
        }
      }
    ]
  }
};
