// Generated by the CU CMS. Do not edit.

import type { TraditionSection } from '../../types/pages/home/tradition';

export type { TraditionSection };

export const TRADITION_SECTION: TraditionSection = {
  "heading": "testing *testing*",
  "filmHeading": "testing *testing*",
  "ctaLabel": "testing testing",
  "opportunitiesText": "testing testing",
  "stats": [
    {
      "value": "0000",
      "label": "testing testing",
      "note": "testing testing"
    },
    {
      "value": "0000",
      "label": "testing testing",
      "note": "testing testing"
    },
    {
      "value": "0000",
      "label": "testing testing",
      "note": "testing testing"
    },
    {
      "value": "0000",
      "label": "testing testing",
      "note": "testing testing"
    }
  ],
  "slides": [
    {
      "title": "testing *testing*",
      "description": "testing testing"
    },
    {
      "title": "testing *testing*",
      "description": "testing testing"
    },
    {
      "title": "testing *testing*",
      "description": "testing testing"
    }
  ],
  "alumni": [
    {
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1503676260728_1c00da094a0b_1593d6bdd5.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 847
      },
      "name": "testing testing",
      "role": "testing testing",
      "status": "0000"
    },
    {
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1571260899304_425eee4c7efc_5ce92f65fd.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      },
      "name": "testing testing",
      "role": "testing testing",
      "status": "0000"
    },
    {
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1506905925346_21bda4d32df4_3e7d976a76.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      },
      "name": "testing testing",
      "role": "testing testing",
      "status": "0000"
    },
    {
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1522202176988_66273c2fd55f_e8afb4bee4.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      },
      "name": "testing testing",
      "role": "testing testing",
      "status": "0000"
    },
    {
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1523050854058_8df90110c9f1_5d3933d7b4.png",
        "alt": "testing image",
        "width": 800,
        "height": 600
      },
      "name": "testing testing",
      "role": "testing testing",
      "status": "0000"
    },
    {
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1541339907198_e08756dedf3f_6466a1a79a.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      },
      "name": "testing testing",
      "role": "testing testing",
      "status": "0000"
    },
    {
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1519389950473_47ba0277781c_004043fca3.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      },
      "name": "testing testing",
      "role": "testing testing",
      "status": "0000"
    }
  ],
  "highlights": [
    {
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1497366216548_37526070297c_cc9da0bc35.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 801
      },
      "title": "testing testing"
    },
    {
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1531482615713_2afd69097998_6b6c6f5768.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      },
      "title": "testing testing"
    },
    {
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1523240795612_9a054b0db644_4024e78648.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      },
      "title": "testing testing"
    },
    {
      "image": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1524178232363_1fb2b075b655_4844aedea4.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      },
      "title": "testing testing"
    }
  ],
  "quickLinks": [
    {
      "label": "testing testing",
      "href": "#programs-section"
    },
    {
      "label": "testing testing",
      "href": "#international-section"
    },
    {
      "label": "testing testing",
      "href": "#news-section"
    },
    {
      "label": "testing testing",
      "href": "#campus-life-section"
    }
  ],
  "placementMetrics": [
    {
      "value": "0000",
      "label": "testing testing",
      "note": "testing testing"
    },
    {
      "value": "0000",
      "label": "testing testing",
      "note": "testing testing"
    },
    {
      "value": "0000",
      "label": "testing testing",
      "note": "testing testing"
    },
    {
      "value": "0000",
      "label": "0000",
      "note": "testing testing"
    }
  ],
  "departments": [
    {
      "name": "testing testing",
      "companies": 0,
      "students": 0
    },
    {
      "name": "testing testing",
      "companies": 0,
      "students": 0
    },
    {
      "name": "testing testing",
      "companies": 0,
      "students": 0
    },
    {
      "name": "testing testing",
      "companies": 0,
      "students": 0
    },
    {
      "name": "testing testing",
      "companies": 0,
      "students": 0
    },
    {
      "name": "testing testing",
      "companies": 0,
      "students": 0
    },
    {
      "name": "testing testing",
      "companies": 0,
      "students": 0
    }
  ],
  "overviewMetrics": [
    {
      "value": "0000",
      "label": "testing testing",
      "note": "testing testing"
    },
    {
      "value": "0000",
      "label": "testing testing",
      "note": "testing testing"
    },
    {
      "value": "0000",
      "label": "testing testing",
      "note": "testing testing"
    },
    {
      "value": "0000",
      "label": "testing testing",
      "note": "testing testing"
    }
  ],
  "researchMetrics": [
    {
      "value": "0000",
      "label": "testing testing",
      "note": "testing testing"
    },
    {
      "value": "0000",
      "label": "testing testing",
      "note": "testing testing"
    },
    {
      "value": "0000",
      "label": "testing testing",
      "note": "testing testing"
    },
    {
      "value": "0000",
      "label": "testing testing",
      "note": "testing testing"
    }
  ],
  "impactRings": [
    {
      "label": "testing testing",
      "value": 0,
      "total": 1
    },
    {
      "label": "testing testing",
      "value": 0,
      "total": 1
    },
    {
      "label": "testing testing",
      "value": 0,
      "total": 1
    }
  ],
  "patents": [
    {
      "title": "testing testing",
      "applicationId": "201811031386",
      "author": "testing testing"
    },
    {
      "title": "testing testing",
      "applicationId": "201811040359",
      "author": "testing testing"
    },
    {
      "title": "testing testing",
      "applicationId": "202311024727",
      "author": "testing testing"
    },
    {
      "title": "testing testing",
      "applicationId": "201811040604",
      "author": "testing testing"
    },
    {
      "title": "testing testing",
      "applicationId": "201811040364",
      "author": "testing testing"
    },
    {
      "title": "testing testing",
      "applicationId": "202011009961",
      "author": "testing testing"
    },
    {
      "title": "testing testing",
      "applicationId": "201811031413",
      "author": "testing testing"
    },
    {
      "title": "testing testing",
      "applicationId": "201911054747",
      "author": "testing testing"
    },
    {
      "title": "testing testing",
      "applicationId": "202011009967",
      "author": "testing testing"
    },
    {
      "title": "testing testing",
      "applicationId": "201811040358",
      "author": "testing testing"
    },
    {
      "title": "testing testing",
      "applicationId": "438059-001",
      "author": "testing testing"
    },
    {
      "title": "testing testing",
      "applicationId": "20251109432A",
      "author": "testing testing"
    },
    {
      "title": "testing testing",
      "applicationId": "542190-008",
      "author": "testing testing"
    },
    {
      "title": "testing testing",
      "applicationId": "PAT-BUS-101",
      "author": "testing testing"
    },
    {
      "title": "testing testing",
      "applicationId": "PAT-HTL-102",
      "author": "testing testing"
    },
    {
      "title": "testing testing",
      "applicationId": "PAT-HTL-103",
      "author": "testing testing"
    },
    {
      "title": "testing testing",
      "applicationId": "PAT-MKT-104",
      "author": "testing testing"
    },
    {
      "title": "testing testing",
      "applicationId": "PAT-MKT-105",
      "author": "testing testing"
    },
    {
      "title": "testing testing",
      "applicationId": "PAT-HLH-106",
      "author": "testing testing"
    },
    {
      "title": "testing testing",
      "applicationId": "PAT-BUS-107",
      "author": "testing testing"
    }
  ],
  "researchDomains": [
    "testing testing",
    "testing testing",
    "testing testing",
    "testing testing",
    "testing testing",
    "testing testing",
    "testing testing",
    "testing testing",
    "testing testing",
    "testing testing",
    "testing testing"
  ],
  "researchClusters": [
    "testing testing",
    "testing testing",
    "testing testing",
    "testing testing",
    "testing testing",
    "testing testing"
  ],
  "labImages": [
    {
      "url": "http://127.0.0.1:1337/uploads/testing_photo_1562774053_701939374585_d6c47bbbb9.jpg",
      "alt": "testing image",
      "width": 1200,
      "height": 786
    }
  ],
  "companyLogos": [
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1513258496099_48168024aec0_38d2e4fa8c.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1517486808906_6ca8b3f04846_4d025ae68f.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 1552
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1509062522246_3755977927d7_dd5c6e5f53.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 747
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1503676260728_1c00da094a0b_1593d6bdd5.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 847
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1571260899304_425eee4c7efc_5ce92f65fd.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1506905925346_21bda4d32df4_3e7d976a76.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1522202176988_66273c2fd55f_e8afb4bee4.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1523050854058_8df90110c9f1_5d3933d7b4.png",
        "alt": "testing image",
        "width": 800,
        "height": 600
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1541339907198_e08756dedf3f_6466a1a79a.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1519389950473_47ba0277781c_004043fca3.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1497366216548_37526070297c_cc9da0bc35.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 801
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1531482615713_2afd69097998_6b6c6f5768.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1523240795612_9a054b0db644_4024e78648.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1524178232363_1fb2b075b655_4844aedea4.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1562774053_701939374585_d6c47bbbb9.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 786
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1513258496099_48168024aec0_38d2e4fa8c.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1517486808906_6ca8b3f04846_4d025ae68f.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 1552
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1509062522246_3755977927d7_dd5c6e5f53.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 747
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1503676260728_1c00da094a0b_1593d6bdd5.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 847
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1571260899304_425eee4c7efc_5ce92f65fd.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1506905925346_21bda4d32df4_3e7d976a76.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1522202176988_66273c2fd55f_e8afb4bee4.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1523050854058_8df90110c9f1_5d3933d7b4.png",
        "alt": "testing image",
        "width": 800,
        "height": 600
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1541339907198_e08756dedf3f_6466a1a79a.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1519389950473_47ba0277781c_004043fca3.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1497366216548_37526070297c_cc9da0bc35.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 801
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1531482615713_2afd69097998_6b6c6f5768.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1523240795612_9a054b0db644_4024e78648.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1524178232363_1fb2b075b655_4844aedea4.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1562774053_701939374585_d6c47bbbb9.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 786
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1513258496099_48168024aec0_38d2e4fa8c.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1517486808906_6ca8b3f04846_4d025ae68f.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 1552
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1509062522246_3755977927d7_dd5c6e5f53.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 747
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1503676260728_1c00da094a0b_1593d6bdd5.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 847
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1571260899304_425eee4c7efc_5ce92f65fd.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    }
  ],
  "partnerLogos": [
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1506905925346_21bda4d32df4_3e7d976a76.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1522202176988_66273c2fd55f_e8afb4bee4.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1523050854058_8df90110c9f1_5d3933d7b4.png",
        "alt": "testing image",
        "width": 800,
        "height": 600
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1541339907198_e08756dedf3f_6466a1a79a.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1519389950473_47ba0277781c_004043fca3.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1497366216548_37526070297c_cc9da0bc35.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 801
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1531482615713_2afd69097998_6b6c6f5768.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1523240795612_9a054b0db644_4024e78648.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1524178232363_1fb2b075b655_4844aedea4.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1562774053_701939374585_d6c47bbbb9.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 786
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1513258496099_48168024aec0_38d2e4fa8c.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1517486808906_6ca8b3f04846_4d025ae68f.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 1552
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1509062522246_3755977927d7_dd5c6e5f53.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 747
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1503676260728_1c00da094a0b_1593d6bdd5.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 847
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1571260899304_425eee4c7efc_5ce92f65fd.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1506905925346_21bda4d32df4_3e7d976a76.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1522202176988_66273c2fd55f_e8afb4bee4.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1523050854058_8df90110c9f1_5d3933d7b4.png",
        "alt": "testing image",
        "width": 800,
        "height": 600
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1541339907198_e08756dedf3f_6466a1a79a.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1519389950473_47ba0277781c_004043fca3.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1497366216548_37526070297c_cc9da0bc35.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 801
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1531482615713_2afd69097998_6b6c6f5768.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1523240795612_9a054b0db644_4024e78648.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1524178232363_1fb2b075b655_4844aedea4.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1562774053_701939374585_d6c47bbbb9.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 786
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1513258496099_48168024aec0_38d2e4fa8c.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1517486808906_6ca8b3f04846_4d025ae68f.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 1552
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1509062522246_3755977927d7_dd5c6e5f53.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 747
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1503676260728_1c00da094a0b_1593d6bdd5.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 847
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1571260899304_425eee4c7efc_5ce92f65fd.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1506905925346_21bda4d32df4_3e7d976a76.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1522202176988_66273c2fd55f_e8afb4bee4.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1523050854058_8df90110c9f1_5d3933d7b4.png",
        "alt": "testing image",
        "width": 800,
        "height": 600
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1541339907198_e08756dedf3f_6466a1a79a.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    },
    {
      "name": "testing testing",
      "logo": {
        "url": "http://127.0.0.1:1337/uploads/testing_photo_1519389950473_47ba0277781c_004043fca3.jpg",
        "alt": "testing image",
        "width": 1200,
        "height": 800
      }
    }
  ]
};
