// Generated by the CU CMS. Do not edit.

import type { TraditionSection } from '../../types/pages/home/tradition';

export type { TraditionSection };

export const TRADITION_SECTION: TraditionSection = {
  "heading": "*Illustrious Legacy* of\nChandigarh University",
  "filmHeading": "Welcome to \n*Chandigarh University, Uttar Pradesh*",
  "ctaLabel": "Apply Now",
  "opportunitiesText": "From securing a dream job with the world's leading companies to serving in the defence forces or pursuing your passion as an artist, CU offers diverse opportunities to fulfil your aspirations.",
  "stats": [
    {
      "value": "100 K",
      "label": "ALUMNI",
      "note": "Accomplished Alumni Across the Globe"
    },
    {
      "value": "250+",
      "label": "STARTUPS",
      "note": "Startups Incubated"
    },
    {
      "value": "1.7 CR",
      "label": "PLACEMENT",
      "note": "Highest Package Offered (International)"
    },
    {
      "value": "980+",
      "label": "STALWARTS",
      "note": "Industry Stalwarts for Top-Tier Mentorship"
    }
  ],
  "slides": [
    {
      "title": "India's First *AI-Integrated* \nMultidisciplinary University",
      "description": "In an era propelled by the advent of artificial intelligence, Chandigarh University, Uttar Pradesh, has embraced a multidisciplinary education model enriched by AI integration, preparing students to lead the future."
    },
    {
      "title": "Scholarship Worth *100 Crore* \nto Unlock Your Potential",
      "description": "To unlock your scholarly potential and pave the way for your bright future at Chandigarh University, Uttar Pradesh, with up to 100% scholarship opportunities."
    },
    {
      "title": "*India's No.1* Private University \nnow in *Uttar Pradesh*",
      "description": "A new era of academic excellence begins as the legacy of India's No. 1 leading private university expands to UP, built on world-class education, industry-aligned programs and exceptional placement outcomes."
    }
  ],
  "alumni": [
    {
      "image": {
        "url": "http://127.0.0.1:1337/uploads/legacy_Aluminus_Anusha_Raj_Judicial_Magistrate_Government_of_Bihar_Patna_1_88b757eb1a.webp",
        "alt": "Anusha Raj",
        "width": 600,
        "height": 600
      },
      "name": "Anusha Raj",
      "role": "Judicial Magistrate",
      "status": "Government of Bihar, Patna"
    },
    {
      "image": {
        "url": "http://127.0.0.1:1337/uploads/legacy_Aluminus_Jaspreet_Singh_Atlassian_Package_59_9_Lakh_1_b4766fe164.webp",
        "alt": "Jaspreet Singh",
        "width": 600,
        "height": 600
      },
      "name": "Jaspreet Singh",
      "role": "Atlassian Package",
      "status": "₹59.9 Lakh"
    },
    {
      "image": {
        "url": "http://127.0.0.1:1337/uploads/legacy_Aluminus_Kshitij_Rasal_Tesla_USA_70_Lakh_1_23d198de00.webp",
        "alt": "Kshitij Rasal",
        "width": 600,
        "height": 600
      },
      "name": "Kshitij Rasal",
      "role": "Tesla, USA",
      "status": "70 Lakh"
    },
    {
      "image": {
        "url": "http://127.0.0.1:1337/uploads/legacy_Aluminus_Pawan_Sehrawat_Arjun_Awardee_Key_Player_of_Indian_Kabaddi_Team_1_be964fd1b0.webp",
        "alt": "Pawan Sehrawat",
        "width": 600,
        "height": 600
      },
      "name": "Pawan Sehrawat",
      "role": "Arjun Awardee",
      "status": "Indian Kabaddi Team"
    },
    {
      "image": {
        "url": "http://127.0.0.1:1337/uploads/legacy_Aluminus_Sanjay_Arjuna_Awardee_Key_Player_of_Indian_Hockey_Team_1_6905ee59a0.webp",
        "alt": "Sanjay",
        "width": 600,
        "height": 600
      },
      "name": "Sanjay",
      "role": "Arjuna Awardee",
      "status": "Indian Hockey Team"
    },
    {
      "image": {
        "url": "http://127.0.0.1:1337/uploads/legacy_Aluminus_Utkarsh_Luthra_Entrepreneur_Medoc_Health_1_Cr_Turnover_1_229d7566fd.webp",
        "alt": "Utkarsh Luthra",
        "width": 600,
        "height": 600
      },
      "name": "Utkarsh Luthra",
      "role": "Entrepreneur - Medoc Health",
      "status": "1 Cr Turnover"
    },
    {
      "image": {
        "url": "http://127.0.0.1:1337/uploads/legacy_Aluminus_Vishwas_Khatak_Civil_Judge_cum_Judicial_Magistrate_Government_of_Haryana_1_6ff01f45cb.webp",
        "alt": "Vishwas Khatak",
        "width": 600,
        "height": 600
      },
      "name": "Vishwas Khatak",
      "role": "Civil Judge cum Judicial Magistrate",
      "status": "Government of Haryana"
    }
  ],
  "highlights": [
    {
      "image": {
        "url": "http://127.0.0.1:1337/uploads/images_traditon_section_india_first_ai_fest_cb12e97f56.jpg",
        "alt": "India First AI Fest at Chandigarh University",
        "width": 1920,
        "height": 960
      },
      "title": "India First AI Fest"
    },
    {
      "image": {
        "url": "http://127.0.0.1:1337/uploads/images_traditon_section_Overall_Champian_a9af3ece4d.jpg",
        "alt": "Chandigarh University students with the overall championship trophy",
        "width": 2160,
        "height": 1080
      },
      "title": "39th AIU Inter-University North Zone"
    },
    {
      "image": {
        "url": "http://127.0.0.1:1337/uploads/images_traditon_section_Khelo_Indian_2_3b69e7a720.jpg",
        "alt": "Khelo India celebration at Chandigarh University",
        "width": 2160,
        "height": 1080
      },
      "title": "Khelo India Celebration"
    },
    {
      "image": {
        "url": "http://127.0.0.1:1337/uploads/images_traditon_section_NIRF_RANKING_1_2ccf653fe5.jpg",
        "alt": "NIRF ranking celebration at Chandigarh University",
        "width": 2160,
        "height": 1080
      },
      "title": "NIRF Ranking Celebration"
    }
  ],
  "quickLinks": [
    {
      "label": "Explore Careers",
      "href": "#programs-section"
    },
    {
      "label": "International Edge",
      "href": "#international-section"
    },
    {
      "label": "In the News",
      "href": "#news-section"
    },
    {
      "label": "Glimpse of Student Life",
      "href": "#campus-life-section"
    }
  ],
  "placementMetrics": [
    {
      "value": "10,000+",
      "label": "OFFERS",
      "note": "Placement Offers Made to Our Students"
    },
    {
      "value": "1,300+",
      "label": "COMPANIES",
      "note": "Company Visits for Campus Recruitment"
    },
    {
      "value": "₹1.7 CR",
      "label": "HIGHEST",
      "note": "Highest International Package Offered"
    },
    {
      "value": "180+",
      "label": "10+ LPA",
      "note": "Companies Offering Above 10 LPA"
    }
  ],
  "departments": [
    {
      "name": "CSE & IT",
      "companies": 122,
      "students": 2030
    },
    {
      "name": "Management",
      "companies": 400,
      "students": 1427
    },
    {
      "name": "Electrical",
      "companies": 37,
      "students": 628
    },
    {
      "name": "Mechanical",
      "companies": 115,
      "students": 530
    },
    {
      "name": "Hotel Mgmt",
      "companies": 106,
      "students": 294
    },
    {
      "name": "Civil/Chem",
      "companies": 35,
      "students": 178
    },
    {
      "name": "Pharma",
      "companies": 27,
      "students": 159
    }
  ],
  "overviewMetrics": [
    {
      "value": "100 K",
      "label": "ALUMNI",
      "note": "Accomplished Alumni Across the Globe"
    },
    {
      "value": "250+",
      "label": "STARTUPS",
      "note": "Startups Incubated at Chandigarh University"
    },
    {
      "value": "980+",
      "label": "STALWARTS",
      "note": "Industry Stalwarts for Top-Tier Mentorship"
    },
    {
      "value": "1.7 CR",
      "label": "PLACEMENT",
      "note": "Highest International Package Offered"
    }
  ],
  "researchMetrics": [
    {
      "value": "24,000",
      "label": "PAPERS",
      "note": "Publications in National and International Journals"
    },
    {
      "value": "5,900",
      "label": "PATENTS",
      "note": "Patents Filed From Campus Labs"
    },
    {
      "value": "200",
      "label": "GROUPS",
      "note": "Active Interdisciplinary Research Groups"
    },
    {
      "value": "2M+",
      "label": "CITATIONS",
      "note": "Citations of Chandigarh University Research"
    }
  ],
  "impactRings": [
    {
      "label": "Citations per publication",
      "value": 83,
      "total": 100
    },
    {
      "label": "Publications per research group",
      "value": 120,
      "total": 200
    },
    {
      "label": "Patents per 100 publications",
      "value": 25,
      "total": 100
    }
  ],
  "patents": [
    {
      "title": "Toilet Flushing System And A Method Thereof",
      "applicationId": "201811031386",
      "author": "Lohit Gaurav"
    },
    {
      "title": "A Solar Powered Traffic Light Control System",
      "applicationId": "201811040359",
      "author": "Dr. Sanjeet Singh"
    },
    {
      "title": "Automated Soil Levelling Device",
      "applicationId": "202311024727",
      "author": "Amanpreet Singh"
    },
    {
      "title": "Automatic Irrigation System And A Method For The Same",
      "applicationId": "201811040604",
      "author": "Dr. Seema"
    },
    {
      "title": "Bill Estimation System",
      "applicationId": "201811040364",
      "author": "Khushal Thakur"
    },
    {
      "title": "Comb Cleaning Device",
      "applicationId": "202011009961",
      "author": "Dr. Inderpreet Kaur"
    },
    {
      "title": "Fermented Herbal Drink And Preparation Thereof",
      "applicationId": "201811031413",
      "author": "Dr. Tarun Kumar"
    },
    {
      "title": "Heat Absorption Covering Apparatus",
      "applicationId": "201911054747",
      "author": "Sahil Dogra"
    },
    {
      "title": "Intelligent Shopping System",
      "applicationId": "202011009967",
      "author": "Arun Kumar"
    },
    {
      "title": "Locker Security System",
      "applicationId": "201811040358",
      "author": "Khushal Thakur"
    },
    {
      "title": "Artificial Intelligence Based Market Forecasting Devices and Frameworks",
      "applicationId": "438059-001",
      "author": "Dr. Uma Shankar"
    },
    {
      "title": "IoT-Enabled Smart Agriculture Monitoring System Using Deep Learning Networks",
      "applicationId": "20251109432A",
      "author": "Dr. Neha Gupta"
    },
    {
      "title": "Graphene-Based Nanocomposites for High-Efficiency Lithium-Ion Battery Electrodes",
      "applicationId": "542190-008",
      "author": "Dr. Sandeep Kumar"
    },
    {
      "title": "Dynamic Revenue Management and Automated Room Pricing System",
      "applicationId": "PAT-BUS-101",
      "author": "Dr. Vivek Agnihotri"
    },
    {
      "title": "Smart Room Sanitation Status Indicator Device and Method",
      "applicationId": "PAT-HTL-102",
      "author": "Dr. Inderpreet Kaur"
    },
    {
      "title": "Smart Kitchen Inventory Sensor Shelf for Dynamic Menu Pricing",
      "applicationId": "PAT-HTL-103",
      "author": "Chef Kabir Anand"
    },
    {
      "title": "Automated Customer Sentiment Analysis Interface for Retail Counters",
      "applicationId": "PAT-MKT-104",
      "author": "Dr. Preeti Sharma"
    },
    {
      "title": "Dynamic Advertising Board with Interactive Customer Scanning",
      "applicationId": "PAT-MKT-105",
      "author": "Dr. Rajat Verma"
    },
    {
      "title": "Wearable Glucose Monitor with Real-Time Haptic Alert System",
      "applicationId": "PAT-HLH-106",
      "author": "Dr. Preeti Sharma"
    },
    {
      "title": "Automated Employee Attendance and Smart Locker Access System",
      "applicationId": "PAT-BUS-107",
      "author": "Lohit Gaurav"
    }
  ],
  "researchDomains": [
    "AI-ML",
    "Autonomous Agents",
    "AR-VR",
    "Robotics",
    "Sustainability",
    "Data Science",
    "Quantum Computing",
    "Cybersecurity",
    "Biotechnology",
    "Renewable Energy",
    "Healthcare AI"
  ],
  "researchClusters": [
    "Artificial Intelligence",
    "Medicine",
    "Chemistry",
    "Augmented Reality",
    "Robotics",
    "Biotechnology"
  ],
  "labImages": [
    {
      "url": "http://127.0.0.1:1337/uploads/images_campus_life_ai_labs_SYP_7751_3498f39456.webp",
      "alt": "",
      "width": 2560,
      "height": 1707
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_campus_life_ai_labs_SYP_6859_5b0979e6ee.webp",
      "alt": "AI lab workstations at Chandigarh University, Uttar Pradesh",
      "width": 2457,
      "height": 1638
    },
    {
      "url": "http://127.0.0.1:1337/uploads/images_campus_life_ai_labs_SYP_7760_6452537816.webp",
      "alt": "",
      "width": 2560,
      "height": 1707
    }
  ]
};
